// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

package domain

import (
	"encoding/base64"
	"fmt"
)

// ExternalIDByteLen is the byte width used for server-generated external ids:
// 128 bits of randomness before base64url encoding. Caller-supplied external ids
// are opaque strings and are not constrained to this size.
const ExternalIDByteLen = 16

// ExternalIDStringLen is the width of server-generated external ids: 16 random
// bytes in base64url without padding render to exactly 22 characters.
const ExternalIDStringLen = 22

// externalIDCodec encodes server-generated random bytes as URL-safe base64 with
// no padding. Caller-supplied external ids are kept verbatim.
var externalIDCodec = base64.RawURLEncoding

// ExternalID is the non-guessable, opaque identity of a machine-generated
// record whose existence is exposed on the wire (orders, trades, order events,
// adjustments, audit rows, market-data instances, and the realm row). It backs
// an opaque string supplied by the caller or generated by Officer. It replaces
// the leaky autoincrement primary key on the wire: the internal surrogate key
// never leaves the store.
//
// Server-generated ids use 128 bits of randomness encoded as 22-char base64url,
// but caller-supplied ids are accepted verbatim; uniqueness is enforced by the
// store. A zero value is invalid and means "unset".
type ExternalID string

// String renders the external id exactly as it appears on the wire.
func (id ExternalID) String() string {
	return string(id)
}

// IsZero reports whether the external id is the unset zero value.
func (id ExternalID) IsZero() bool {
	return id == ""
}

// Bytes returns a copy of the external id bytes for storage.
func (id ExternalID) Bytes() []byte {
	return []byte(id)
}

// ExternalIDFromBytes builds an ExternalID from stored bytes.
func ExternalIDFromBytes(b []byte) (ExternalID, error) {
	if len(b) == 0 {
		return "", fmt.Errorf(
			"external id must not be empty: %w",
			ErrInvalid,
		)
	}
	return ExternalID(string(b)), nil
}

// GeneratedExternalIDFromBytes encodes random bytes into Officer's generated-id
// wire form.
func GeneratedExternalIDFromBytes(b []byte) (ExternalID, error) {
	if len(b) != ExternalIDByteLen {
		return "", fmt.Errorf(
			"generated external id needs %d random bytes, got %d: %w",
			ExternalIDByteLen, len(b), ErrInvalid,
		)
	}
	return ExternalID(externalIDCodec.EncodeToString(b)), nil
}

// ParseExternalID turns a non-empty wire id into an ExternalID. Caller-supplied
// ids are opaque and have no format restriction beyond being present; uniqueness
// is enforced by the store.
func ParseExternalID(s string) (ExternalID, error) {
	if s == "" {
		return "", fmt.Errorf("external id must not be empty: %w", ErrInvalid)
	}
	return ExternalID(s), nil
}

// ValidateExternalID returns nil when s is a present external-id wire value. It
// never checks existence or uniqueness.
func ValidateExternalID(s string) error {
	_, err := ParseExternalID(s)
	return err
}
