-- Copyright The Pit Project Owners. All rights reserved.
-- SPDX-License-Identifier: Apache-2.0
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--
-- Please see https://openpit.dev and the OWNERS file for details.

-- Add the cumulative settlement-asset realized P&L to spot-funds balances.
-- The column is delta-accumulated: each operation's realized-PnL delta is added
-- to the stored value, never overwritten with the engine's reported absolute. A
-- fresh row starts at '0', so the accumulated deltas equal the cumulative.
ALTER TABLE balances ADD COLUMN realized_pnl TEXT NOT NULL DEFAULT '0';
