// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

// Adjustments group of the SQLite store. Adjustments are machine records
// addressed by their opaque external id (22-char base64url, assigned at insert
// by the connector). Account and asset references cascade on delete; the
// optional principal reference is cleared (SET NULL) when the principal is
// removed. The request and outcome columns are opaque JSON stored whole; this
// package never decodes them — callers supply pre-marshalled JSON and receive
// it back byte-for-byte.

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"time"

	"go.openpit.dev/officer/internal/domain"
)

// adjustmentSelect is the shared projection for adjustment reads. The JOINs
// surface the account, asset, and optional principal as their codes so the
// surrogate ids never leave the store. The LEFT JOIN on principals yields NULL
// when the reference was cleared or never set.
const adjustmentSelect = `
SELECT adj.external_id, a.code, ast.code, p.code,
       adj.at, adj.source, adj.status, adj.request, adj.outcome
FROM adjustments adj
JOIN accounts  a   ON a.id   = adj.account_id
JOIN assets    ast ON ast.id = adj.asset_id
LEFT JOIN principals p ON p.id = adj.principal_id`

// AppendAdjustment records one adjustment outcome and its timestamp. The caller
// populates the typed Request and Accepted/Rejected fields; the store marshals
// them to opaque JSON for the request and outcome columns. A caller-supplied
// rec.ExternalID is used verbatim so the operator owns the handle; a zero id is
// generated by the connector. A duplicate supplied id is rejected with
// domain.ErrAlreadyExists (the external_id UNIQUE constraint, no pre-insert
// probe). The stored record with ExternalID and At populated is returned.
func (r *realmStore) AppendAdjustment(
	ctx context.Context, rec domain.AccountAdjustmentRecord,
) (domain.AccountAdjustmentRecord, error) {
	accountID, err := resolveAccountID(ctx, r.db(), rec.Account)
	if err != nil {
		return rec, err
	}
	assetID, err := resolveAssetID(ctx, r.db(), rec.Asset)
	if err != nil {
		return rec, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, r.db(), rec.Principal)
	if err != nil {
		return rec, err
	}

	reqJSON, err := json.Marshal(rec.Request)
	if err != nil {
		return rec, fmt.Errorf("store: marshal adjustment request: %w", err)
	}
	outcomeJSON, err := marshalAdjustmentOutcome(rec)
	if err != nil {
		return rec, err
	}

	status := adjustmentStatus(rec)

	xid, err := externalIDForInsert(rec.ExternalID)
	if err != nil {
		return rec, err
	}
	at := nowStr()

	if _, err := r.db().ExecContext(
		ctx,
		`INSERT INTO adjustments
		 (external_id, account_id, asset_id, principal_id,
		  at, source, status, request, outcome)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), accountID, assetID, principalID,
		at, string(rec.Source), string(status),
		string(reqJSON), string(outcomeJSON),
	); err != nil {
		if isSQLiteUnique(err) {
			return rec, fmt.Errorf(
				"adjustment %q: %w", xid.String(), domain.ErrAlreadyExists,
			)
		}
		return rec, fmt.Errorf("store: append adjustment: %w", err)
	}

	rec.ExternalID = xid
	rec.At = mustParseTime(at)
	return rec, nil
}

// ListAdjustments returns the most recent n adjustments, newest first. A
// non-empty account or source filters to that value; a non-positive n returns
// an empty slice.
func (r *realmStore) ListAdjustments(
	ctx context.Context,
	account domain.AccountID,
	source domain.Source,
	n int,
) ([]domain.AccountAdjustmentRecord, error) {
	if n <= 0 {
		return make([]domain.AccountAdjustmentRecord, 0), nil
	}

	q := adjustmentSelect + ` WHERE 1 = 1`
	args := make([]any, 0, 3)
	if account != "" {
		q += ` AND a.code = ?`
		args = append(args, account.String())
	}
	if source != "" {
		q += ` AND adj.source = ?`
		args = append(args, string(source))
	}
	q += ` ORDER BY adj.at DESC, adj.id DESC LIMIT ?`
	args = append(args, n)

	rows, err := r.db().QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list adjustments: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.AccountAdjustmentRecord, 0, n)
	for rows.Next() {
		rec, err := scanAdjustment(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, rec)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate adjustments: %w", err)
	}
	return result, nil
}

// --- Adjustment helpers ------------------------------------------------------

// adjustmentStatus returns the status string for a record whose outcome is
// determined by whether Accepted or Rejected is set.
func adjustmentStatus(rec domain.AccountAdjustmentRecord) domain.AdjustmentStatus {
	if rec.Rejected != nil {
		return domain.AdjustmentStatusRejected
	}
	return domain.AdjustmentStatusAccepted
}

// adjustmentOutcomeEnvelope is the JSON envelope written to the outcome column.
// Exactly one of Accepted and Rejected is non-nil; this shape is the opaque
// contract between AppendAdjustment and the ListAdjustments read-back path.
type adjustmentOutcomeEnvelope struct {
	Accepted *domain.AdjustmentOutcomeAccepted `json:"accepted,omitempty"`
	Rejected *domain.AdjustmentOutcomeRejected `json:"rejected,omitempty"`
}

// marshalAdjustmentOutcome marshals the outcome fields into the opaque JSON
// envelope that is stored in the outcome column.
func marshalAdjustmentOutcome(rec domain.AccountAdjustmentRecord) ([]byte, error) {
	env := adjustmentOutcomeEnvelope{
		Accepted: rec.Accepted,
		Rejected: rec.Rejected,
	}
	b, err := json.Marshal(env)
	if err != nil {
		return nil, fmt.Errorf("store: marshal adjustment outcome: %w", err)
	}
	return b, nil
}

// scanAdjustment scans one adjustment projection, decoding the external-id
// BLOB, the nullable principal code, the at timestamp, and the opaque JSON
// request and outcome columns.
func scanAdjustment(rows *sql.Rows) (domain.AccountAdjustmentRecord, error) {
	var (
		extID                                      []byte
		accountCode, assetCode                     string
		principal                                  sql.NullString
		at, source, status, requestStr, outcomeStr string
	)
	if err := rows.Scan(
		&extID, &accountCode, &assetCode, &principal,
		&at, &source, &status, &requestStr, &outcomeStr,
	); err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf("store: scan adjustment: %w", err)
	}

	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: decode adjustment external id: %w", err,
		)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: parse adjustment at %q: %w", at, err,
		)
	}

	var req domain.AdjustmentRequest
	if err := json.Unmarshal([]byte(requestStr), &req); err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: unmarshal adjustment request: %w", err,
		)
	}

	var env adjustmentOutcomeEnvelope
	if err := json.Unmarshal([]byte(outcomeStr), &env); err != nil {
		// A malformed outcome column is a corrupt row; surface it as an error
		// rather than masking it.
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: unmarshal adjustment outcome: %w", err,
		)
	}

	rec := domain.AccountAdjustmentRecord{
		ExternalID: xid,
		Account:    domain.AccountID(accountCode),
		Asset:      assetCode,
		Principal:  principal.String,
		At:         parsedAt,
		Source:     domain.Source(source),
		Request:    req,
		Accepted:   env.Accepted,
		Rejected:   env.Rejected,
	}
	_ = status // status is derived from Accepted/Rejected; stored for indexing
	return rec, nil
}
