// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

// Orders group of the SQLite store: orders and their 1:1 signed approval, the
// immutable order-event stream, per-fill trades ("reports"), order counts and
// the atomic fill/settlement write. Every record here is machine-generated and
// addressed by its opaque external id; the surrogate key joins rows internally
// and never crosses the interface boundary. Account, asset and principal
// references are resolved by code on write and surfaced as code on read, so a
// surrogate id never leaks. The SDK-serialized reservation lock is persisted
// verbatim as a BLOB and read back byte-identical; this package never decodes it.

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"go.openpit.dev/officer/framework/domain"
)

// --- Orders -----------------------------------------------------------------

// orderSelect is the shared projection for order reads. The JOINs surface the
// account, base/quote asset and (optional) principal as their codes so the
// surrogate ids never leave the store; the LEFT JOIN on principals yields NULL
// when the reference was cleared or never set. The lock BLOB is read back
// verbatim into the domain []byte.
const orderSelect = `
SELECT o.external_id, a.code, ba.code, qa.code, p.code,
       o.at, o.source, o.side, o.amount_kind, o.amount_value,
       o.price, o.status, o.lock
FROM orders o
JOIN accounts a       ON a.id = o.account_id
JOIN assets ba        ON ba.id = o.base_asset_id
JOIN assets qa        ON qa.id = o.quote_asset_id
LEFT JOIN principals p ON p.id = o.principal_id`

// CreateOrder inserts a new order and its submission time. It resolves the
// account and both assets by code to their surrogate ids and the optional
// principal to a nullable id, then persists the SDK-serialized lock blob
// verbatim. A caller-supplied o.ExternalID is used verbatim so the operator owns
// the handle; a zero id is generated by the connector. A duplicate supplied id
// is rejected with domain.ErrAlreadyExists (the external_id UNIQUE constraint,
// no pre-insert probe). It returns the order with ExternalID and At populated;
// the surrogate id is never surfaced.
func (r *realmStore) CreateOrder(
	ctx context.Context, o domain.Order,
) (domain.Order, error) {
	accountID, err := resolveAccountID(ctx, r.db(), o.Account)
	if err != nil {
		return o, err
	}
	baseID, err := resolveAssetID(ctx, r.db(), o.BaseAsset)
	if err != nil {
		return o, err
	}
	quoteID, err := resolveAssetID(ctx, r.db(), o.QuoteAsset)
	if err != nil {
		return o, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, r.db(), o.Principal)
	if err != nil {
		return o, err
	}
	xid, err := externalIDForInsert(o.ExternalID)
	if err != nil {
		return o, err
	}
	at := nowStr()
	if _, err := r.db().ExecContext(
		ctx,
		`INSERT INTO orders
		 (external_id, account_id, base_asset_id, quote_asset_id, principal_id,
		  at, source, side, amount_kind, amount_value, price, status, lock)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), accountID, baseID, quoteID, principalID,
		at, string(o.Source), string(o.Side), string(o.AmountKind),
		o.AmountValue, o.Price, string(o.Status), nullableBlob(o.Lock),
	); err != nil {
		if isSQLiteUnique(err) {
			return o, fmt.Errorf(
				"order %q: %w", xid.String(), domain.ErrAlreadyExists,
			)
		}
		return o, fmt.Errorf("store: create order: %w", err)
	}
	o.ExternalID = xid
	o.At = mustParseTime(at)
	return o, nil
}

// UpdateOrderStatus updates the status of the order addressed by external id.
func (r *realmStore) UpdateOrderStatus(
	ctx context.Context, id domain.ExternalID, status domain.OrderStatus,
) error {
	res, err := r.db().ExecContext(
		ctx,
		`UPDATE orders SET status = ? WHERE external_id = ?`,
		string(status), id.Bytes(),
	)
	if err != nil {
		return fmt.Errorf("store: update order status: %w", err)
	}
	return notFoundIfNoRows(res, "order", id.String())
}

// SetOrderLock replaces the persisted SDK-serialized lock blob of the order
// addressed by external id, writing the bytes verbatim. A nil lock clears the
// column.
func (r *realmStore) SetOrderLock(
	ctx context.Context, id domain.ExternalID, lock []byte,
) error {
	res, err := r.db().ExecContext(
		ctx,
		`UPDATE orders SET lock = ? WHERE external_id = ?`,
		nullableBlob(lock), id.Bytes(),
	)
	if err != nil {
		return fmt.Errorf("store: set order lock: %w", err)
	}
	return notFoundIfNoRows(res, "order", id.String())
}

// PutOrderApproval stamps the signed approval envelope onto the order addressed
// by external id, write-once: it inserts the 1:1 order_approvals row only when
// the order carries none yet (INSERT OR IGNORE on the order_id primary key), so
// a retry or a later write never clobbers an already-issued envelope. A no-op
// (already stamped, or missing order) is not an error: the envelope is
// best-effort and the order is the durable trail.
func (r *realmStore) PutOrderApproval(
	ctx context.Context, id domain.ExternalID, env domain.OrderApproval,
) error {
	orderID, err := lookupOrderID(ctx, r.db(), id)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			// Missing order is a tolerated no-op, not an error.
			return nil
		}
		return err
	}
	signingKeyID, err := resolveSigningKeyID(ctx, r.db(), env.KeyID)
	if err != nil {
		return err
	}
	if _, err := r.db().ExecContext(
		ctx,
		`INSERT OR IGNORE INTO order_approvals
		 (order_id, token, signing_key_id, alg, mode, issued_at, expires_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		orderID, env.Token, signingKeyID, env.Alg, env.Mode,
		env.IssuedAt, env.ExpiresAt,
	); err != nil {
		return fmt.Errorf("store: put order approval: %w", err)
	}
	return nil
}

// GetOrder returns the order addressed by external id together with its events,
// trades, and its 1:1 signed approval when one was issued. Returns
// domain.ErrNotFound when the order is absent.
//
// The order's signed approval is persisted in order_approvals (written by
// PutOrderApproval, write-once). It is read back through the getOrderApproval
// seam and folded into OrderDetail.Approval (nil when the order is unsigned), so
// a caller presenting an order gets its envelope metadata without a second
// round-trip.
func (r *realmStore) GetOrder(
	ctx context.Context, id domain.ExternalID,
) (domain.OrderDetail, error) {
	row := r.db().QueryRowContext(ctx, orderSelect+` WHERE o.external_id = ?`, id.Bytes())
	o, err := scanOrderRow(row)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.OrderDetail{}, fmt.Errorf("order %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return domain.OrderDetail{}, fmt.Errorf("store: get order: %w", err)
	}

	events, err := r.ListOrderEvents(ctx, id)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	trades, err := r.listTradesByOrder(ctx, id)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	detail := domain.OrderDetail{Order: o, Events: events, Trades: trades}
	if env, ok, aerr := r.getOrderApproval(ctx, id); aerr != nil {
		return domain.OrderDetail{}, aerr
	} else if ok {
		detail.Approval = &env
	}
	return detail, nil
}

// ListOrders returns the most recent n orders for an account, newest first. An
// empty account spans every account; an empty source spans every source; a
// non-positive n returns an empty slice.
func (r *realmStore) ListOrders(
	ctx context.Context, account domain.AccountID, source domain.Source, n int,
) ([]domain.Order, error) {
	if n <= 0 {
		return make([]domain.Order, 0), nil
	}
	return r.listOrders(ctx, account, source, n)
}

// ListAllOrders returns every order for an account, newest first. It is used by
// exports that must not inherit UI display limits.
func (r *realmStore) ListAllOrders(
	ctx context.Context, account domain.AccountID, source domain.Source,
) ([]domain.Order, error) {
	return r.listOrders(ctx, account, source, 0)
}

// listOrders is the shared order-list query: it filters by the non-empty
// account and source, orders newest first by (at, id) per the §9 index, and
// applies the optional positive limit.
func (r *realmStore) listOrders(
	ctx context.Context, account domain.AccountID, source domain.Source, limit int,
) ([]domain.Order, error) {
	q := orderSelect + ` WHERE 1 = 1`
	args := make([]any, 0, 3)
	if account != "" {
		q += ` AND a.code = ?`
		args = append(args, account.String())
	}
	if source != "" {
		q += ` AND o.source = ?`
		args = append(args, string(source))
	}
	q += ` ORDER BY o.at DESC, o.id DESC`
	if limit > 0 {
		q += ` LIMIT ?`
		args = append(args, limit)
	}

	rows, err := r.db().QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list orders: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.Order, 0)
	for rows.Next() {
		o, err := scanOrder(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, o)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate orders: %w", err)
	}
	return result, nil
}

// CountOrders returns the total number of orders recorded in the realm.
func (r *realmStore) CountOrders(ctx context.Context) (int, error) {
	var n int
	if err := r.db().QueryRowContext(
		ctx, `SELECT COUNT(*) FROM orders`,
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count orders: %w", err)
	}
	return n, nil
}

// CountOrdersSince returns the number of orders whose at timestamp is at or
// after since. The at column is RFC3339Nano UTC text, so the boundary is
// formatted the same way for a lexicographic comparison.
func (r *realmStore) CountOrdersSince(ctx context.Context, since time.Time) (int, error) {
	var n int
	if err := r.db().QueryRowContext(
		ctx,
		`SELECT COUNT(*) FROM orders WHERE at >= ?`,
		since.UTC().Format(time.RFC3339Nano),
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count orders since: %w", err)
	}
	return n, nil
}

// getOrderApproval returns the 1:1 approval of the order addressed by external
// id. The bool is false when the order carries no signed envelope.
func (r *realmStore) getOrderApproval(
	ctx context.Context, id domain.ExternalID,
) (domain.OrderApproval, bool, error) {
	var env domain.OrderApproval
	err := r.db().QueryRowContext(
		ctx,
		`SELECT ap.token, sk.key_id, ap.alg, ap.mode, ap.issued_at, ap.expires_at
		 FROM order_approvals ap
		 JOIN signing_keys sk ON sk.id = ap.signing_key_id
		 JOIN orders o ON o.id = ap.order_id
		 WHERE o.external_id = ?`,
		id.Bytes(),
	).Scan(&env.Token, &env.KeyID, &env.Alg, &env.Mode, &env.IssuedAt, &env.ExpiresAt)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.OrderApproval{}, false, nil
	}
	if err != nil {
		return domain.OrderApproval{}, false, fmt.Errorf("store: get order approval: %w", err)
	}
	return env, true, nil
}

func scanOrder(rows *sql.Rows) (domain.Order, error) {
	var o domain.Order
	if err := scanOrderInto(rows.Scan, &o); err != nil {
		return domain.Order{}, fmt.Errorf("store: scan order: %w", err)
	}
	return o, nil
}

func scanOrderRow(row *sql.Row) (domain.Order, error) {
	var o domain.Order
	if err := scanOrderInto(row.Scan, &o); err != nil {
		return domain.Order{}, err
	}
	return o, nil
}

// scanOrderInto scans one order projection through scan into o, decoding the
// external-id BLOB, the nullable principal code and the nullable lock BLOB and
// parsing the submission time. The scan func is *sql.Row.Scan or *sql.Rows.Scan.
func scanOrderInto(scan func(...any) error, o *domain.Order) error {
	var (
		extID                                []byte
		principal                            sql.NullString
		at, source, side, amountKind, status string
		amountValue, price                   string
		lock                                 []byte
	)
	if err := scan(
		&extID, &o.Account, &o.BaseAsset, &o.QuoteAsset, &principal,
		&at, &source, &side, &amountKind, &amountValue,
		&price, &status, &lock,
	); err != nil {
		return err
	}
	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return fmt.Errorf("store: decode order external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return fmt.Errorf("store: parse order at %q: %w", at, err)
	}
	o.ExternalID = xid
	o.At = parsedAt
	o.Principal = principal.String
	o.Source = domain.Source(source)
	o.Side = domain.OrderSide(side)
	o.AmountKind = domain.OrderAmountKind(amountKind)
	o.AmountValue = amountValue
	o.Price = price
	o.Status = domain.OrderStatus(status)
	o.Lock = lock
	return nil
}

// --- Order events -----------------------------------------------------------

// orderEventSelect is the shared projection for event reads. The event links to
// its order through the surrogate FK internally; reads surface only the event's
// own fields plus the optional principal code.
const orderEventSelect = `
SELECT e.external_id, e.at, e.type, e.source, p.code, e.payload
FROM order_events e
LEFT JOIN principals p ON p.id = e.principal_id`

// AppendOrderEvent adds an event to the stream of the order named by ev.Order,
// assigning the event's external id and timestamp. The payload is marshalled to
// opaque JSON and stored whole.
func (r *realmStore) AppendOrderEvent(
	ctx context.Context, ev domain.OrderEvent,
) (domain.OrderEvent, error) {
	orderID, err := lookupOrderID(ctx, r.db(), ev.Order)
	if err != nil {
		return ev, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, r.db(), ev.Principal)
	if err != nil {
		return ev, err
	}
	xid, err := newExternalID()
	if err != nil {
		return ev, err
	}
	payloadJSON, err := json.Marshal(ev.Payload)
	if err != nil {
		return ev, fmt.Errorf("store: marshal event payload: %w", err)
	}
	at := nowStr()
	if _, err := r.db().ExecContext(
		ctx,
		`INSERT INTO order_events
		 (external_id, order_id, principal_id, at, type, source, payload)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, principalID, at,
		string(ev.Type), string(ev.Source), string(payloadJSON),
	); err != nil {
		return ev, fmt.Errorf("store: append order event: %w", err)
	}
	ev.ExternalID = xid
	ev.At = mustParseTime(at)
	return ev, nil
}

// ListOrderEvents returns all events for the order addressed by external id,
// oldest first by (at, id).
func (r *realmStore) ListOrderEvents(
	ctx context.Context, order domain.ExternalID,
) ([]domain.OrderEvent, error) {
	rows, err := r.db().QueryContext(
		ctx,
		orderEventSelect+`
		 JOIN orders o ON o.id = e.order_id
		 WHERE o.external_id = ?
		 ORDER BY e.at ASC, e.id ASC`,
		order.Bytes(),
	)
	if err != nil {
		return nil, fmt.Errorf("store: list order events: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.OrderEvent, 0)
	for rows.Next() {
		ev, err := scanOrderEvent(rows, order)
		if err != nil {
			return nil, err
		}
		result = append(result, ev)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate order events: %w", err)
	}
	return result, nil
}

// scanOrderEvent scans one event projection. The parent order's external id is
// carried in by the caller (it is the query key) so it need not be re-selected.
func scanOrderEvent(rows *sql.Rows, order domain.ExternalID) (domain.OrderEvent, error) {
	var (
		extID           []byte
		at, typ, source string
		principal       sql.NullString
		payloadStr      string
	)
	if err := rows.Scan(&extID, &at, &typ, &source, &principal, &payloadStr); err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: scan order event: %w", err)
	}
	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: decode event external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: parse event at %q: %w", at, err)
	}
	var payload domain.OrderEventPayload
	if err := json.Unmarshal([]byte(payloadStr), &payload); err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: unmarshal event payload: %w", err)
	}
	return domain.OrderEvent{
		ExternalID: xid,
		Order:      order,
		At:         parsedAt,
		Type:       domain.OrderEventType(typ),
		Source:     domain.Source(source),
		Principal:  principal.String,
		Payload:    payload,
	}, nil
}

// --- Trades -----------------------------------------------------------------

// tradeSelect is the shared projection for trade reads. The order reference is
// surfaced outward as the order's external id (order_external_id); the surrogate
// order id never leaves the store. Account, both assets and the optional
// principal are surfaced as codes.
const tradeSelect = `
SELECT t.external_id, o.external_id, a.code, ba.code, qa.code, p.code,
       t.at, t.source, t.side, t.quantity, t.price, t.lock_price
FROM trades t
JOIN orders o          ON o.id = t.order_id
JOIN accounts a        ON a.id = t.account_id
JOIN assets ba         ON ba.id = t.base_asset_id
JOIN assets qa         ON qa.id = t.quote_asset_id
LEFT JOIN principals p ON p.id = t.principal_id`

// CreateTrade records a fill as a standalone trade row, assigning its external
// id and timestamp. It links to the originating order (surrogate id resolved
// from the order's external id), the account and both assets by code, and the
// optional principal.
func (r *realmStore) CreateTrade(
	ctx context.Context, t domain.Trade,
) (domain.Trade, error) {
	xid, at, err := r.insertTrade(ctx, r.db(), t)
	if err != nil {
		return t, err
	}
	t.ExternalID = xid
	t.At = mustParseTime(at)
	return t, nil
}

// insertTrade resolves a trade's foreign keys and inserts the row through exec
// (a *sql.DB or *sql.Tx), returning the assigned external id and timestamp text.
// It is shared by CreateTrade and the settlement transaction so both write an
// identical row.
func (r *realmStore) insertTrade(
	ctx context.Context, exec interface {
		sqlQueryer
		sqlExecer
	}, t domain.Trade,
) (domain.ExternalID, string, error) {
	orderID, err := lookupOrderID(ctx, exec, t.Order)
	if err != nil {
		return domain.ExternalID{}, "", err
	}
	accountID, err := resolveAccountID(ctx, exec, t.Account)
	if err != nil {
		return domain.ExternalID{}, "", err
	}
	baseID, err := resolveAssetID(ctx, exec, t.BaseAsset)
	if err != nil {
		return domain.ExternalID{}, "", err
	}
	quoteID, err := resolveAssetID(ctx, exec, t.QuoteAsset)
	if err != nil {
		return domain.ExternalID{}, "", err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, exec, t.Principal)
	if err != nil {
		return domain.ExternalID{}, "", err
	}
	xid, err := newExternalID()
	if err != nil {
		return domain.ExternalID{}, "", err
	}
	at := nowStr()
	if _, err := exec.ExecContext(
		ctx,
		`INSERT INTO trades
		 (external_id, order_id, account_id, base_asset_id, quote_asset_id,
		  principal_id, at, source, side, quantity, price, lock_price)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, accountID, baseID, quoteID, principalID,
		at, string(t.Source), string(t.Side), t.Quantity, t.Price, t.LockPrice,
	); err != nil {
		return domain.ExternalID{}, "", fmt.Errorf("store: create trade: %w", err)
	}
	return xid, at, nil
}

// ListTrades returns the most recent n trades for an account, newest first. An
// empty account spans every account; an empty source spans every source; a
// non-positive n returns an empty slice.
func (r *realmStore) ListTrades(
	ctx context.Context, account domain.AccountID, source domain.Source, n int,
) ([]domain.Trade, error) {
	if n <= 0 {
		return make([]domain.Trade, 0), nil
	}
	return r.listTrades(ctx, account, source, n)
}

// ListAllTrades returns every trade for an account, newest first. It is used by
// exports that must not inherit UI display limits.
func (r *realmStore) ListAllTrades(
	ctx context.Context, account domain.AccountID, source domain.Source,
) ([]domain.Trade, error) {
	return r.listTrades(ctx, account, source, 0)
}

// listTrades is the shared trade-list query: it filters by the non-empty account
// and source, orders newest first by (at, id) per the §9 index, and applies the
// optional positive limit.
func (r *realmStore) listTrades(
	ctx context.Context, account domain.AccountID, source domain.Source, limit int,
) ([]domain.Trade, error) {
	q := tradeSelect + ` WHERE 1 = 1`
	args := make([]any, 0, 3)
	if account != "" {
		q += ` AND a.code = ?`
		args = append(args, account.String())
	}
	if source != "" {
		q += ` AND t.source = ?`
		args = append(args, string(source))
	}
	q += ` ORDER BY t.at DESC, t.id DESC`
	if limit > 0 {
		q += ` LIMIT ?`
		args = append(args, limit)
	}

	rows, err := r.db().QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list trades: %w", err)
	}
	defer func() { _ = rows.Close() }()
	return scanTrades(rows)
}

// listTradesByOrder returns all trades for one order (addressed by its external
// id), oldest first by (at, id). It backs GetOrder's trade list.
func (r *realmStore) listTradesByOrder(
	ctx context.Context, order domain.ExternalID,
) ([]domain.Trade, error) {
	rows, err := r.db().QueryContext(
		ctx,
		tradeSelect+` WHERE o.external_id = ? ORDER BY t.at ASC, t.id ASC`,
		order.Bytes(),
	)
	if err != nil {
		return nil, fmt.Errorf("store: list trades by order: %w", err)
	}
	defer func() { _ = rows.Close() }()
	return scanTrades(rows)
}

func scanTrades(rows *sql.Rows) ([]domain.Trade, error) {
	result := make([]domain.Trade, 0)
	for rows.Next() {
		tr, err := scanTrade(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, tr)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate trades: %w", err)
	}
	return result, nil
}

func scanTrade(rows *sql.Rows) (domain.Trade, error) {
	var (
		tradeExtID, orderExtID                    []byte
		account                                   string
		baseAsset, quoteAsset                     string
		principal                                 sql.NullString
		at, source, side, quantity, price, lockPx string
	)
	if err := rows.Scan(
		&tradeExtID, &orderExtID, &account, &baseAsset, &quoteAsset, &principal,
		&at, &source, &side, &quantity, &price, &lockPx,
	); err != nil {
		return domain.Trade{}, fmt.Errorf("store: scan trade: %w", err)
	}
	tradeXID, err := domain.ExternalIDFromBytes(tradeExtID)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: decode trade external id: %w", err)
	}
	orderXID, err := domain.ExternalIDFromBytes(orderExtID)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: decode trade order external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: parse trade at %q: %w", at, err)
	}
	return domain.Trade{
		ExternalID: tradeXID,
		Order:      orderXID,
		Account:    domain.AccountID(account),
		BaseAsset:  baseAsset,
		QuoteAsset: quoteAsset,
		Principal:  principal.String,
		At:         parsedAt,
		Source:     domain.Source(source),
		Side:       domain.OrderSide(side),
		Quantity:   quantity,
		Price:      price,
		LockPrice:  lockPx,
	}, nil
}

// --- Settlement -------------------------------------------------------------

// RecordOrderSettlement persists one fill/settlement atomically in a single
// transaction: per-asset balances (realized P&L delta-accumulated inside the
// tx), the engine-applied account blocks, the optional trade, the fill event(s),
// the optional lock rewrite and the order status advance commit or roll back
// together. A zero st.Order is an in-memory-only hold with no order row: the
// order/event/lock writes are skipped and only the balance and block effects
// run. When AllowedFrom is non-empty the status UPDATE is guarded and a
// disallowed current status yields domain.ErrConflict with nothing written;
// otherwise a missing order yields domain.ErrNotFound. The block-audit row is
// NOT part of this tx; callers write it separately after a successful commit.
func (r *realmStore) RecordOrderSettlement(
	ctx context.Context, st domain.OrderSettlement,
) error {
	tx, err := r.db().BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("store: begin record_order_settlement: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	// Resolve the settling account once; balances and blocks reuse it. The
	// account is the fill's account, always present on a settlement.
	accountID, err := resolveAccountID(ctx, tx, st.Account)
	if err != nil {
		return err
	}

	// Per-asset balances: read-modify-write inside the tx so the realized-P&L
	// accumulate is consistent under the tx snapshot (SQLite serializes writers).
	for _, bal := range st.Balances {
		if err := settleBalanceTx(ctx, tx, accountID, bal); err != nil {
			return err
		}
	}

	// Mirror engine-applied account blocks (the block UPDATE only; the audit row
	// stays a post-commit write owned by the caller). A block names its own
	// account, which may differ from the fill account in principle, so resolve it.
	for _, blk := range st.Blocks {
		blkAccountID, err := resolveAccountID(ctx, tx, blk.Account)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE accounts SET blocked = ?, block_reason = ? WHERE id = ?`,
			true, blk.Reason, blkAccountID,
		); err != nil {
			return fmt.Errorf("store: settlement mirror block %q: %w", blk.Account, err)
		}
	}

	// Trade row.
	if st.Trade != nil {
		if _, _, err := r.insertTrade(ctx, tx, *st.Trade); err != nil {
			return err
		}
	}

	// The remaining writes touch the order row; an in-memory-only hold (zero
	// Order) carries no order row, so skip them and only the balance/block
	// effects above run.
	if st.Order.IsZero() {
		if err := tx.Commit(); err != nil {
			return fmt.Errorf("store: commit record_order_settlement: %w", err)
		}
		return nil
	}

	// Resolve the order surrogate id once; events, the optional lock rewrite and
	// the status advance all reuse it.
	orderID, err := lookupOrderID(ctx, tx, st.Order)
	if err != nil {
		return err
	}

	// Fill event(s).
	for _, ev := range st.Events {
		if err := appendOrderEventTx(ctx, tx, orderID, ev); err != nil {
			return err
		}
	}

	// Lock rewrite: only when explicitly requested (nil-vs-empty matters: an
	// empty non-nil slice clears the column, nil leaves it).
	if st.SetLock {
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE orders SET lock = ? WHERE id = ?`,
			nullableBlob(st.Lock), orderID,
		); err != nil {
			return fmt.Errorf("store: settlement lock: %w", err)
		}
	}

	// Status advance last; guarded only when AllowedFrom is set.
	if err := guardedOrderStatus(
		ctx, tx, orderID, st.Order, st.OrderStatus, st.AllowedFrom,
	); err != nil {
		return err
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("store: commit record_order_settlement: %w", err)
	}
	return nil
}

// guardedOrderStatus advances an order's status inside tx, addressing it by its
// already-resolved surrogate id. When allowedFrom is non-empty the UPDATE only
// matches rows already in one of those statuses; a 0-rows result then means
// either the order is missing (domain.ErrNotFound) or its current status is
// disallowed (domain.ErrConflict), distinguished by a follow-up SELECT in the
// same tx. When allowedFrom is empty the UPDATE is unguarded and 0 rows means a
// missing order. The order external id is carried for error messages only.
func guardedOrderStatus(
	ctx context.Context,
	tx *sql.Tx,
	orderID int64,
	order domain.ExternalID,
	status domain.OrderStatus,
	allowedFrom []domain.OrderStatus,
) error {
	args := []any{string(status), orderID}
	q := `UPDATE orders SET status = ? WHERE id = ?`
	if len(allowedFrom) > 0 {
		placeholders := strings.TrimSuffix(strings.Repeat("?,", len(allowedFrom)), ",")
		q += fmt.Sprintf(` AND status IN (%s)`, placeholders)
		for _, s := range allowedFrom {
			args = append(args, string(s))
		}
	}
	res, err := tx.ExecContext(ctx, q, args...)
	if err != nil {
		return fmt.Errorf("store: resolve order %q status: %w", order.String(), err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("store: resolve order %q status rows: %w", order.String(), err)
	}
	if n > 0 {
		return nil
	}
	// No row advanced: distinguish a missing order from a disallowed status.
	var cur string
	err = tx.QueryRowContext(
		ctx, `SELECT status FROM orders WHERE id = ?`, orderID,
	).Scan(&cur)
	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("order %q: %w", order.String(), domain.ErrNotFound)
	}
	if err != nil {
		return fmt.Errorf("store: resolve order %q status probe: %w", order.String(), err)
	}
	return fmt.Errorf(
		"store: resolve order %q: status %q: %w", order.String(), cur, domain.ErrConflict,
	)
}

// appendOrderEventTx inserts one order event inside tx against the already-
// resolved order surrogate id, mirroring AppendOrderEvent's external-id, payload
// and timestamp handling.
func appendOrderEventTx(
	ctx context.Context, tx *sql.Tx, orderID int64, ev domain.OrderEvent,
) error {
	principalID, err := resolveOptionalPrincipalID(ctx, tx, ev.Principal)
	if err != nil {
		return err
	}
	xid, err := newExternalID()
	if err != nil {
		return err
	}
	payloadJSON, err := json.Marshal(ev.Payload)
	if err != nil {
		return fmt.Errorf("store: marshal event payload: %w", err)
	}
	if _, err := tx.ExecContext(
		ctx,
		`INSERT INTO order_events
		 (external_id, order_id, principal_id, at, type, source, payload)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, principalID, nowStr(),
		string(ev.Type), string(ev.Source), string(payloadJSON),
	); err != nil {
		return fmt.Errorf("store: append order event: %w", err)
	}
	return nil
}

// settleBalanceTx applies one per-asset fill outcome inside tx. It resolves the
// asset code to its surrogate id, reads the prior row (zero-value on absence),
// accumulates realized P&L by delta, takes available/held/incoming from the
// outcome's *Result with the prior value carried forward when a result is empty,
// carries average_entry_price forward (a fill does not restate it) and writes
// the row back. This is the node's former read-modify-write fill persistence,
// moved inside the tx so the accumulate cannot lose an update. The balances
// table is owned by another store group; this method touches it with direct SQL
// (never the public balance methods) to keep the whole settlement atomic.
func settleBalanceTx(
	ctx context.Context,
	tx *sql.Tx,
	accountID int64,
	bal domain.BalanceSettlement,
) error {
	assetID, err := resolveAssetID(ctx, tx, bal.Asset)
	if err != nil {
		return err
	}
	var prevAvail, prevHeld, prevIncoming, prevRealized, prevAvgPx string
	err = tx.QueryRowContext(
		ctx,
		`SELECT available, held, incoming, realized_pnl, average_entry_price
		 FROM balances WHERE account_id = ? AND asset_id = ?`,
		accountID, assetID,
	).Scan(&prevAvail, &prevHeld, &prevIncoming, &prevRealized, &prevAvgPx)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("store: settle balance %q read: %w", bal.Asset, err)
	}

	realized, err := domain.AddDecimals(prevRealized, bal.Outcome.RealizedPnlDelta)
	if err != nil {
		return fmt.Errorf("store: settle balance %q realized_pnl: %w", bal.Asset, err)
	}
	if _, err := tx.ExecContext(
		ctx,
		`INSERT OR REPLACE INTO balances
		 (account_id, asset_id, available, held, incoming, realized_pnl,
		  average_entry_price, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		accountID, assetID,
		settleOrZero(settlePick(bal.Outcome.BalanceResult, prevAvail)),
		settleOrZero(settlePick(bal.Outcome.HeldResult, prevHeld)),
		settleOrZero(settlePick(bal.Outcome.IncomingResult, prevIncoming)),
		settleOrZero(realized),
		prevAvgPx,
		nowStr(),
	); err != nil {
		return fmt.Errorf("store: settle balance %q write: %w", bal.Asset, err)
	}
	return nil
}

// --- Orders-group small helpers ---------------------------------------------

// lookupOrderID resolves an order's external id to its surrogate id, mapping a
// missing order onto domain.ErrNotFound. It is the orders-group analogue of the
// dictionary resolvers in sqlite.go; it joins the order's children and the
// settlement writes to the order without exposing the surrogate id.
func lookupOrderID(
	ctx context.Context, q sqlQueryer, id domain.ExternalID,
) (int64, error) {
	var orderID int64
	err := q.QueryRowContext(
		ctx, `SELECT id FROM orders WHERE external_id = ?`, id.Bytes(),
	).Scan(&orderID)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, fmt.Errorf("order %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return 0, fmt.Errorf("store: resolve order %q: %w", id.String(), err)
	}
	return orderID, nil
}

// nullableBlob maps a nil byte slice to a NULL column value and a non-nil slice
// (including an empty one) to itself, so the lock column distinguishes "no lock"
// (NULL) from a present-but-empty serialized lock.
func nullableBlob(b []byte) any {
	if b == nil {
		return nil
	}
	return b
}

// mustParseTime parses an RFC3339Nano string the store itself just formatted via
// nowStr; the format is guaranteed, so a parse error is impossible and the zero
// time is returned defensively rather than panicking on the write path.
func mustParseTime(s string) time.Time {
	t, _ := time.Parse(time.RFC3339Nano, s)
	return t
}

// settlePick returns next when it is non-empty, otherwise the carried-forward
// prev. A fill outcome leaves a field's *Result empty when the fill did not move
// that field, so the prior stored value is retained.
func settlePick(next, prev string) string {
	if next != "" {
		return next
	}
	return prev
}

// settleOrZero maps an empty amount string to "0" so a balance column is never
// written empty.
func settleOrZero(s string) string {
	if s == "" {
		return "0"
	}
	return s
}
