// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

// Orders group of the SQLite store: orders and their 1:1 signed approval, the
// immutable order-event stream, per-fill trade ("reports"), order counts and
// the atomic fill/settlement write. Every record here is machine-generated and
// addressed by its opaque external id; the surrogate key joins rows internally
// and never crosses the interface boundary. Account, asset and principal
// references are resolved by code on write and surfaced as code on read, so a
// surrogate id never leaks. The SDK-serialized reservation lock is persisted
// verbatim as a BLOB and read back byte-identical; this package never decodes it.

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/shopspring/decimal"

	"go.openpit.dev/officer/framework/domain"
	fwstore "go.openpit.dev/officer/framework/store"
)

// --- Orders -----------------------------------------------------------------

// orderSelect is the shared projection for order reads. The JOINs surface the
// account, base/quote asset and (optional) principal as their codes so the
// surrogate ids never leave the store; the LEFT JOIN on principal yields NULL
// when the reference was cleared or never set. The lock BLOB is read back
// verbatim into the domain []byte.
const orderSelect = `
SELECT o.external_id, a.code, ba.code, qa.code, p.code,
       o.at, o.source, o.side, o.amount_kind, o.amount_value,
       o.leaves_quantity, o.price, o.status, o.lock
FROM order_record o
JOIN account a       ON a.id = o.account_id
JOIN asset ba        ON ba.id = o.base_asset_id
JOIN asset qa        ON qa.id = o.quote_asset_id
LEFT JOIN principal p ON p.id = o.principal_id`

// orderListSelect extends orderSelect with a "signed" rollup so the paged list
// view can report whether the order carries at least one Ed25519-signed event
// attestation without a second query per order. The correlated subquery is 1
// when any of the order's events has a signed attestation, else 0.
const orderListSelect = `
SELECT o.external_id, a.code, ba.code, qa.code, p.code,
       o.at, o.source, o.side, o.amount_kind, o.amount_value,
       o.leaves_quantity, o.price, o.status, o.lock,
       EXISTS (
           SELECT 1 FROM order_event e
           JOIN event_attestation ea ON ea.event_id = e.id
           WHERE e.order_id = o.id AND ea.alg = 'ed25519'
       ) AS signed
FROM order_record o
JOIN account a       ON a.id = o.account_id
JOIN asset ba        ON ba.id = o.base_asset_id
JOIN asset qa        ON qa.id = o.quote_asset_id
LEFT JOIN principal p ON p.id = o.principal_id`

// CreateOrder inserts a new order and its submission time. It resolves the
// account and both assets by code to their surrogate ids and the optional
// principal to a nullable id, then persists the SDK-serialized lock blob
// verbatim. A caller-supplied o.ExternalID is used verbatim so the operator owns
// the handle; a zero id is generated by the connector. A duplicate supplied id
// is rejected with domain.ErrAlreadyExists (the external_id UNIQUE constraint,
// no pre-insert probe). It returns the order with ExternalID and At populated;
// the surrogate id is never surfaced.
func (r *realmStore) CreateOrder(
	ctx context.Context, o domain.Order,
) (domain.Order, error) {
	db, err := r.db()
	if err != nil {
		return domain.Order{}, err
	}
	return createOrderTx(ctx, db, o)
}

func createOrderTx(ctx context.Context, q sqlReadWriter, o domain.Order) (domain.Order, error) {
	accountID, err := resolveAccountID(ctx, q, o.Account)
	if err != nil {
		return o, err
	}
	baseID, err := resolveAssetID(ctx, q, o.BaseAsset)
	if err != nil {
		return o, err
	}
	quoteID, err := resolveAssetID(ctx, q, o.QuoteAsset)
	if err != nil {
		return o, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, q, o.Principal)
	if err != nil {
		return o, err
	}
	xid, err := externalIDForInsert(o.ExternalID)
	if err != nil {
		return o, err
	}
	at := nowStr()
	if _, err := q.ExecContext(
		ctx,
		`INSERT INTO order_record
		 (external_id, account_id, base_asset_id, quote_asset_id, principal_id,
		  at, source, side, amount_kind, amount_value,
		  leaves_quantity, price, status, lock)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), accountID, baseID, quoteID, principalID,
		at, string(o.Source), string(o.Side), string(o.AmountKind),
		o.AmountValue, o.Leaves, o.Price,
		string(o.Status), nullableBlob(o.Lock),
	); err != nil {
		if isSQLiteUnique(err) {
			return o, fmt.Errorf(
				"order %q: %w", xid.String(), domain.ErrAlreadyExists,
			)
		}
		return o, fmt.Errorf("store: create order: %w", err)
	}
	o.ExternalID = xid
	o.At = mustParseTime(at)
	return o, nil
}

func (r *realmStore) RecordOrderSubmission(
	ctx context.Context,
	o domain.Order,
	submitted domain.OrderEvent,
	apply func(domain.Order) (domain.OrderSettlement, error),
) (domain.Order, error) {
	return r.recordOrderSubmission(ctx, o, submitted, apply, nil)
}

func (r *realmStore) RecordOrderSubmissionWithAttestation(
	ctx context.Context,
	o domain.Order,
	submitted domain.OrderEvent,
	apply func(domain.Order) (domain.OrderSettlement, error),
	attest fwstore.EventAttestor,
) (domain.Order, error) {
	return r.recordOrderSubmission(ctx, o, submitted, apply, attest)
}

func (r *realmStore) recordOrderSubmission(
	ctx context.Context,
	o domain.Order,
	submitted domain.OrderEvent,
	apply func(domain.Order) (domain.OrderSettlement, error),
	attest fwstore.EventAttestor,
) (domain.Order, error) {
	db, err := r.db()
	if err != nil {
		return domain.Order{}, err
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return domain.Order{}, fmt.Errorf("store: begin order submission: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	order, err := createOrderTx(ctx, tx, o)
	if err != nil {
		return domain.Order{}, err
	}
	orderID, err := lookupOrderID(ctx, tx, order.ExternalID)
	if err != nil {
		return domain.Order{}, err
	}
	if submitted.Order.IsZero() {
		submitted.Order = order.ExternalID
	}
	recordedSubmitted, err := appendOrderEventReturningTx(ctx, tx, orderID, submitted)
	if err != nil {
		return domain.Order{}, err
	}

	settlement, err := apply(order)
	if err != nil {
		return domain.Order{}, err
	}
	if err := attestOrderEventTx(ctx, tx, recordedSubmitted, attest); err != nil {
		return domain.Order{}, err
	}
	if settlement.Order.IsZero() {
		settlement.Order = order.ExternalID
	}
	if settlement.Account == "" {
		settlement.Account = order.Account
	}
	if err := r.recordOrderSettlementTx(ctx, tx, settlement, attest); err != nil {
		return domain.Order{}, err
	}
	if err := tx.Commit(); err != nil {
		return domain.Order{}, fmt.Errorf("store: commit order submission: %w", err)
	}

	order.Status = settlement.OrderStatus
	order.Lock = settlement.Lock
	if settlement.Leaves != "" {
		order.Leaves = settlement.Leaves
	}
	return order, nil
}

// UpdateOrderStatus updates the status of the order addressed by external id.
func (r *realmStore) UpdateOrderStatus(
	ctx context.Context, id domain.ExternalID, status domain.OrderStatus,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`UPDATE order_record SET status = ? WHERE external_id = ?`,
		string(status), id.Bytes(),
	)
	if err != nil {
		return fmt.Errorf("store: update order status: %w", err)
	}
	return notFoundIfNoRows(res, "order", id.String())
}

// SetOrderLock replaces the persisted SDK-serialized lock blob of the order
// addressed by external id, writing the bytes verbatim. A nil lock clears the
// column.
func (r *realmStore) SetOrderLock(
	ctx context.Context, id domain.ExternalID, lock []byte,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`UPDATE order_record SET lock = ? WHERE external_id = ?`,
		nullableBlob(lock), id.Bytes(),
	)
	if err != nil {
		return fmt.Errorf("store: set order lock: %w", err)
	}
	return notFoundIfNoRows(res, "order", id.String())
}

// PutEventAttestation stamps the attestation envelope onto the order-history
// event addressed by external id, write-once: it inserts the 1:1
// event_attestation row only when the event carries none yet (only event_id
// conflicts are ignored), so a retry or a later write never clobbers an
// already-issued envelope. An already-stamped event is a no-op; a missing event
// returns domain.ErrNotFound so callers cannot silently commit an unsigned
// event.
func (r *realmStore) PutEventAttestation(
	ctx context.Context, eventID domain.ExternalID, att domain.EventAttestation,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	return putEventAttestationTx(ctx, db, eventID, att)
}

func putEventAttestationTx(
	ctx context.Context,
	q sqlReadWriter,
	eventID domain.ExternalID,
	att domain.EventAttestation,
) error {
	surrogate, err := lookupOrderEventID(ctx, q, eventID)
	if err != nil {
		return err
	}
	var signingKeyID sql.NullInt64
	if att.KeyID != "" {
		id, err := resolveSigningKeyID(ctx, q, att.KeyID)
		if err != nil {
			return err
		}
		signingKeyID = sql.NullInt64{Int64: id, Valid: true}
	}
	if _, err := q.ExecContext(
		ctx,
		`INSERT INTO event_attestation
		 (event_id, token, signing_key_id, alg, request_type, mode, issued_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?)
		 ON CONFLICT(event_id) DO NOTHING`,
		surrogate, att.Token, signingKeyID, att.Alg, string(att.RequestType),
		att.Mode, att.IssuedAt,
	); err != nil {
		return fmt.Errorf("store: put event attestation: %w", err)
	}
	return nil
}

// GetOrder returns the order addressed by external id together with its events
// (each carrying its 1:1 signed attestation when one was issued) and trades.
// Returns domain.ErrNotFound when the order is absent.
//
// Each event's attestation is persisted in event_attestation (written by
// PutEventAttestation, write-once) and folded into OrderEvent.Attestation by the
// event read (nil when the event is unattested), so a caller presenting an order
// gets every event's envelope metadata without a second round-trip.
func (r *realmStore) GetOrder(
	ctx context.Context, id domain.ExternalID,
) (domain.OrderDetail, error) {
	db, err := r.db()
	if err != nil {
		return domain.OrderDetail{}, err
	}
	row := db.QueryRowContext(ctx, orderSelect+` WHERE o.external_id = ?`, id.Bytes())
	o, err := scanOrderRow(row)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.OrderDetail{}, fmt.Errorf("order %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return domain.OrderDetail{}, fmt.Errorf("store: get order: %w", err)
	}

	events, err := r.ListOrderEvents(ctx, id)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	trades, err := r.listTradesByOrder(ctx, id)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	o.CommissionSubtotals, err = commissionSubtotals(trades)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	return domain.OrderDetail{Order: o, Events: events, Trades: trades}, nil
}

// ListOrders returns the most recent n orders for an account, newest first. An
// empty account spans every account; an empty source spans every source; a
// non-positive n returns an empty slice.
func (r *realmStore) ListOrders(
	ctx context.Context, account domain.AccountID, source domain.Source, n int,
) ([]domain.Order, error) {
	if n <= 0 {
		return make([]domain.Order, 0), nil
	}
	return r.listOrders(ctx, account, source, n)
}

// ListAllOrders returns every order for an account, newest first. It is used by
// exports that must not inherit UI display limits.
func (r *realmStore) ListAllOrders(
	ctx context.Context, account domain.AccountID, source domain.Source,
) ([]domain.Order, error) {
	return r.listOrders(ctx, account, source, 0)
}

// ListOrderRows returns orders matching filter, with total count before paging.
func (r *realmStore) ListOrderRows(
	ctx context.Context, filter fwstore.OrderListFilter,
) (fwstore.OrderListPage, error) {
	where, args := orderListWhere(filter)
	countQuery := `SELECT COUNT(*)
FROM order_record o
JOIN account a       ON a.id = o.account_id
JOIN asset ba        ON ba.id = o.base_asset_id
JOIN asset qa        ON qa.id = o.quote_asset_id
LEFT JOIN principal p ON p.id = o.principal_id` + where
	db, err := r.db()
	if err != nil {
		return fwstore.OrderListPage{}, err
	}
	var total int
	if err := db.QueryRowContext(ctx, countQuery, args...).Scan(&total); err != nil {
		return fwstore.OrderListPage{}, fmt.Errorf("store: count order rows: %w", err)
	}

	queryArgs := append([]any{}, args...)
	query := orderListSelect + where + orderListOrderBy(filter.Sort)
	if filter.Page.Limit > 0 {
		query += ` LIMIT ? OFFSET ?`
		queryArgs = append(queryArgs, filter.Page.Limit, max(filter.Page.Offset, 0))
	}
	rows, err := db.QueryContext(ctx, query, queryArgs...)
	if err != nil {
		return fwstore.OrderListPage{}, fmt.Errorf("store: list order rows: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]fwstore.OrderListRow, 0)
	orderIDs := make([]domain.ExternalID, 0)
	for rows.Next() {
		o, signed, err := scanOrderListRow(rows)
		if err != nil {
			return fwstore.OrderListPage{}, err
		}
		result = append(result, fwstore.OrderListRow{Order: o, Signed: signed})
		orderIDs = append(orderIDs, o.ExternalID)
	}
	if err := rows.Err(); err != nil {
		return fwstore.OrderListPage{}, fmt.Errorf("store: iterate order rows: %w", err)
	}
	subtotals, err := commissionSubtotalsByOrder(ctx, db, orderIDs)
	if err != nil {
		return fwstore.OrderListPage{}, err
	}
	for i := range result {
		result[i].Order.CommissionSubtotals = subtotals[result[i].Order.ExternalID]
	}
	return fwstore.OrderListPage{Rows: result, Total: total}, nil
}

// listOrders is the shared order-list query: it filters by the non-empty
// account and source, orders newest first by (at, id) per the §9 index, and
// applies the optional positive limit.
func (r *realmStore) listOrders(
	ctx context.Context, account domain.AccountID, source domain.Source, limit int,
) ([]domain.Order, error) {
	page, err := r.ListOrderRows(ctx, fwstore.OrderListFilter{
		Account: account,
		Source:  source,
		Sort:    fwstore.SortSpec{Column: "at", Descending: true},
		Page:    fwstore.PageSpec{Limit: limit},
	})
	if err != nil {
		return nil, err
	}
	result := make([]domain.Order, 0, len(page.Rows))
	for _, row := range page.Rows {
		result = append(result, row.Order)
	}
	return result, nil
}

func orderListWhere(filter fwstore.OrderListFilter) (string, []any) {
	clauses := make([]string, 0)
	args := make([]any, 0)
	if filter.Account != "" {
		clauses = append(clauses, "a.code = ?")
		args = append(args, filter.Account.String())
	}
	if filter.Source != "" {
		clauses = append(clauses, "o.source = ?")
		args = append(args, string(filter.Source))
	}
	if filter.Side != nil {
		clauses = append(clauses, "o.side = ?")
		args = append(args, string(*filter.Side))
	}
	if len(filter.Status) > 0 {
		placeholders := strings.TrimRight(strings.Repeat("?,", len(filter.Status)), ",")
		clauses = append(clauses, "o.status IN ("+placeholders+")")
		for _, status := range filter.Status {
			args = append(args, string(status))
		}
	}
	appendMatcher(&clauses, &args, "ba.code", filter.BaseAsset)
	appendMatcher(&clauses, &args, "qa.code", filter.QuoteAsset)
	appendDecimalRangeFilter(&clauses, &args, "o.amount_value", filter.Amount)
	appendDecimalRangeFilter(&clauses, &args, "o.price", filter.Price)
	appendTimeRangeFilter(&clauses, &args, "o.at", filter.At)
	if len(clauses) == 0 {
		return "", args
	}
	return "\nWHERE " + strings.Join(clauses, " AND "), args
}

func orderListOrderBy(sort fwstore.SortSpec) string {
	columns := map[string]string{
		"account":     "a.code",
		"at":          "o.at",
		"baseAsset":   "ba.code",
		"price":       "o.price",
		"quoteAsset":  "qa.code",
		"side":        "o.side",
		"source":      "o.source",
		"status":      "o.status",
		"amountValue": "o.amount_value",
	}
	column := columns[sort.Column]
	if column == "" {
		column = "o.at"
		sort.Descending = true
	}
	direction := "ASC"
	tieDirection := "ASC"
	if sort.Descending {
		direction = "DESC"
		tieDirection = "DESC"
	}
	return "\nORDER BY " + column + " " + direction + ", o.id " + tieDirection
}

// CountOrders returns the total number of orders recorded in the realm.
func (r *realmStore) CountOrders(ctx context.Context) (int, error) {
	db, err := r.db()
	if err != nil {
		return 0, err
	}
	var n int
	if err := db.QueryRowContext(
		ctx, `SELECT COUNT(*) FROM order_record`,
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count orders: %w", err)
	}
	return n, nil
}

// CountActiveOrders returns orders in the working lifecycle set.
func (r *realmStore) CountActiveOrders(ctx context.Context) (int, error) {
	db, err := r.db()
	if err != nil {
		return 0, err
	}
	var n int
	if err := db.QueryRowContext(
		ctx,
		`SELECT COUNT(*) FROM order_record
		 WHERE status IN (?, ?, ?)`,
		domain.OrderStatusSubmitted,
		domain.OrderStatusAccepted,
		domain.OrderStatusPartiallyFilled,
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count active orders: %w", err)
	}
	return n, nil
}

// CountOrdersSince returns the number of orders whose at timestamp is at or
// after since. The at column is RFC3339Nano UTC text, so the boundary is
// formatted the same way for a lexicographic comparison.
func (r *realmStore) CountOrdersSince(ctx context.Context, since time.Time) (int, error) {
	db, err := r.db()
	if err != nil {
		return 0, err
	}
	var n int
	if err := db.QueryRowContext(
		ctx,
		`SELECT COUNT(*) FROM order_record WHERE at >= ?`,
		since.UTC().Format(time.RFC3339Nano),
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count orders since: %w", err)
	}
	return n, nil
}

func scanOrderRow(row *sql.Row) (domain.Order, error) {
	var o domain.Order
	if err := scanOrderInto(row.Scan, &o); err != nil {
		return domain.Order{}, err
	}
	return o, nil
}

// scanOrderListRow scans one orderListSelect projection, returning the order
// plus the "signed" rollup: whether any of its events carries an Ed25519-signed
// attestation. An order with no attestation, or only eSign-off ("none")
// attestations, reports false.
func scanOrderListRow(rows *sql.Rows) (domain.Order, bool, error) {
	var o domain.Order
	var signed bool
	if err := scanOrderInto(func(dest ...any) error {
		return rows.Scan(append(dest, &signed)...)
	}, &o); err != nil {
		return domain.Order{}, false, fmt.Errorf("store: scan order list row: %w", err)
	}
	return o, signed, nil
}

// scanOrderInto scans one order projection through scan into o, decoding the
// external-id BLOB, the nullable principal code and the nullable lock BLOB and
// parsing the submission time. The scan func is *sql.Row.Scan or *sql.Rows.Scan.
func scanOrderInto(scan func(...any) error, o *domain.Order) error {
	var (
		extID                                []byte
		principal                            sql.NullString
		at, source, side, amountKind, status string
		amountValue, leaves, price           string
		lock                                 []byte
	)
	if err := scan(
		&extID, &o.Account, &o.BaseAsset, &o.QuoteAsset, &principal,
		&at, &source, &side, &amountKind, &amountValue,
		&leaves, &price, &status, &lock,
	); err != nil {
		return err
	}
	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return fmt.Errorf("store: decode order external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return fmt.Errorf("store: parse order at %q: %w", at, err)
	}
	o.ExternalID = xid
	o.At = parsedAt
	o.Principal = principal.String
	o.Source = domain.Source(source)
	o.Side = domain.OrderSide(side)
	o.AmountKind = domain.OrderAmountKind(amountKind)
	o.AmountValue = amountValue
	o.Leaves = leaves
	o.Price = price
	o.Status = domain.OrderStatus(status)
	o.Lock = lock
	return nil
}

// --- Order events -----------------------------------------------------------

// orderEventSelect is the shared projection for event reads. The event links to
// its order through the surrogate FK internally; reads surface only the event's
// own fields plus the optional principal code and, when present, the event's 1:1
// signed attestation metadata (token verbatim, key UUID, alg, request type,
// mode, issued-at). A NULL token means the event carries no attestation.
const orderEventSelect = `
SELECT e.external_id, e.at, e.type, e.source, p.code, e.payload,
       ea.token, sk.key_id, ea.alg, ea.request_type, ea.mode,
       ea.issued_at
FROM order_event e
LEFT JOIN principal p ON p.id = e.principal_id
LEFT JOIN event_attestation ea ON ea.event_id = e.id
LEFT JOIN signing_key sk ON sk.id = ea.signing_key_id`

// AppendOrderEvent adds an event to the stream of the order named by ev.Order,
// assigning the event's external id and timestamp. The payload is marshalled to
// opaque JSON and stored whole.
func (r *realmStore) AppendOrderEvent(
	ctx context.Context, ev domain.OrderEvent,
) (domain.OrderEvent, error) {
	db, err := r.db()
	if err != nil {
		return domain.OrderEvent{}, err
	}
	orderID, err := lookupOrderID(ctx, db, ev.Order)
	if err != nil {
		return ev, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, db, ev.Principal)
	if err != nil {
		return ev, err
	}
	xid, err := newExternalID()
	if err != nil {
		return ev, err
	}
	payloadJSON, err := json.Marshal(ev.Payload)
	if err != nil {
		return ev, fmt.Errorf("store: marshal event payload: %w", err)
	}
	at := nowStr()
	if _, err := db.ExecContext(
		ctx,
		`INSERT INTO order_event
		 (external_id, order_id, principal_id, at, type, source, payload)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, principalID, at,
		string(ev.Type), string(ev.Source), string(payloadJSON),
	); err != nil {
		return ev, fmt.Errorf("store: append order event: %w", err)
	}
	ev.ExternalID = xid
	ev.At = mustParseTime(at)
	return ev, nil
}

// ListOrderEvents returns all events for the order addressed by external id,
// oldest first by (at, id).
func (r *realmStore) ListOrderEvents(
	ctx context.Context, order domain.ExternalID,
) ([]domain.OrderEvent, error) {
	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(
		ctx,
		orderEventSelect+`
		 JOIN order_record o ON o.id = e.order_id
		 WHERE o.external_id = ?
		 ORDER BY e.at ASC, e.id ASC`,
		order.Bytes(),
	)
	if err != nil {
		return nil, fmt.Errorf("store: list order events: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.OrderEvent, 0)
	for rows.Next() {
		ev, err := scanOrderEvent(rows, order)
		if err != nil {
			return nil, err
		}
		result = append(result, ev)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate order events: %w", err)
	}
	return result, nil
}

// scanOrderEvent scans one event projection, folding in the event's 1:1
// attestation when present. The parent order's external id is carried in by the
// caller (it is the query key) so it need not be re-selected.
func scanOrderEvent(rows *sql.Rows, order domain.ExternalID) (domain.OrderEvent, error) {
	var (
		extID           []byte
		at, typ, source string
		principal       sql.NullString
		payloadStr      string
		attToken        sql.NullString
		attKeyID        sql.NullString
		attAlg          sql.NullString
		attRequestType  sql.NullString
		attMode         sql.NullString
		attIssuedAt     sql.NullString
	)
	if err := rows.Scan(
		&extID, &at, &typ, &source, &principal, &payloadStr,
		&attToken, &attKeyID, &attAlg, &attRequestType, &attMode,
		&attIssuedAt,
	); err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: scan order event: %w", err)
	}
	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: decode event external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: parse event at %q: %w", at, err)
	}
	var payload domain.OrderEventPayload
	if err := json.Unmarshal([]byte(payloadStr), &payload); err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: unmarshal event payload: %w", err)
	}
	ev := domain.OrderEvent{
		ExternalID: xid,
		Order:      order,
		At:         parsedAt,
		Type:       domain.OrderEventType(typ),
		Source:     domain.Source(source),
		Principal:  principal.String,
		Payload:    payload,
	}
	if attToken.Valid {
		ev.Attestation = &domain.EventAttestation{
			Token:       attToken.String,
			KeyID:       attKeyID.String,
			Alg:         attAlg.String,
			RequestType: domain.AttestationRequestType(attRequestType.String),
			Mode:        attMode.String,
			IssuedAt:    attIssuedAt.String,
		}
	}
	return ev, nil
}

// --- Trades -----------------------------------------------------------------

// tradeSelect is the shared projection for trade reads. The order reference is
// surfaced outward as the order's external id (order_external_id); the surrogate
// order id never leaves the store. Account, both assets and the optional
// principal are surfaced as codes.
const tradeSelect = `
SELECT t.external_id, o.external_id, a.code, ba.code, qa.code, p.code,
       t.at, t.source, t.side, t.quantity, t.price, t.lock_price,
       t.commission_amount, t.commission_currency
FROM trade t
JOIN order_record o          ON o.id = t.order_id
JOIN account a        ON a.id = t.account_id
JOIN asset ba         ON ba.id = t.base_asset_id
JOIN asset qa         ON qa.id = t.quote_asset_id
LEFT JOIN principal p ON p.id = t.principal_id`

// CreateTrade records a fill as a standalone trade row, assigning its external
// id and timestamp. It links to the originating order (surrogate id resolved
// from the order's external id), the account and both assets by code, and the
// optional principal.
func (r *realmStore) CreateTrade(
	ctx context.Context, t domain.Trade,
) (domain.Trade, error) {
	db, err := r.db()
	if err != nil {
		return domain.Trade{}, err
	}
	xid, at, err := r.insertTrade(ctx, db, t)
	if err != nil {
		return t, err
	}
	t.ExternalID = xid
	t.At = mustParseTime(at)
	return t, nil
}

// insertTrade resolves a trade's foreign keys and inserts the row through exec
// (a *sql.DB or *sql.Tx), returning the assigned external id and timestamp text.
// It is shared by CreateTrade and the settlement transaction so both write an
// identical row.
func (r *realmStore) insertTrade(
	ctx context.Context, exec interface {
		sqlQueryer
		sqlExecer
	}, t domain.Trade,
) (domain.ExternalID, string, error) {
	if err := validateCommission(t.Commission); err != nil {
		return domain.ExternalID(""), "", err
	}
	orderID, err := lookupOrderID(ctx, exec, t.Order)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	accountID, err := resolveAccountID(ctx, exec, t.Account)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	baseID, err := resolveAssetID(ctx, exec, t.BaseAsset)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	quoteID, err := resolveAssetID(ctx, exec, t.QuoteAsset)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, exec, t.Principal)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	xid, err := newExternalID()
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	at := nowStr()
	if _, err := exec.ExecContext(
		ctx,
		`INSERT INTO trade
	 (external_id, order_id, account_id, base_asset_id, quote_asset_id,
	  principal_id, at, source, side, quantity, price, lock_price,
	  commission_amount, commission_currency)
	 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, accountID, baseID, quoteID, principalID,
		at, string(t.Source), string(t.Side), t.Quantity, t.Price, t.LockPrice,
		commissionAmount(t.Commission), commissionCurrency(t.Commission),
	); err != nil {
		return domain.ExternalID(""), "", fmt.Errorf("store: create trade: %w", err)
	}
	return xid, at, nil
}

// ListTrades returns the most recent n trade for an account, newest first. An
// empty account spans every account; an empty source spans every source; a
// non-positive n returns an empty slice.
func (r *realmStore) ListTrades(
	ctx context.Context, account domain.AccountID, source domain.Source, n int,
) ([]domain.Trade, error) {
	if n <= 0 {
		return make([]domain.Trade, 0), nil
	}
	return r.listTrades(ctx, account, source, n)
}

// ListAllTrades returns every trade for an account, newest first. It is used by
// exports that must not inherit UI display limits.
func (r *realmStore) ListAllTrades(
	ctx context.Context, account domain.AccountID, source domain.Source,
) ([]domain.Trade, error) {
	return r.listTrades(ctx, account, source, 0)
}

// ListTradeRows returns trade rows matching filter, with total count before
// paging.
func (r *realmStore) ListTradeRows(
	ctx context.Context, filter fwstore.TradeListFilter,
) (fwstore.TradeListPage, error) {
	clauses, args := tradeListClauses(filter)
	countQuery := `SELECT COUNT(*)
FROM trade t
JOIN order_record o          ON o.id = t.order_id
JOIN account a        ON a.id = t.account_id
JOIN asset ba         ON ba.id = t.base_asset_id
JOIN asset qa         ON qa.id = t.quote_asset_id
LEFT JOIN principal p ON p.id = t.principal_id` + whereFromClauses(clauses)
	db, err := r.db()
	if err != nil {
		return fwstore.TradeListPage{}, err
	}
	var total int
	if err := db.QueryRowContext(ctx, countQuery, args...).Scan(&total); err != nil {
		return fwstore.TradeListPage{}, fmt.Errorf("store: count trade rows: %w", err)
	}

	queryArgs := append([]any{}, args...)
	sortColumn := tradeListSortColumn(filter.Sort)
	query := `
SELECT t.external_id, o.external_id, a.code, ba.code, qa.code, p.code,
       t.at, t.source, t.side, t.quantity, t.price, t.lock_price,
       t.commission_amount, t.commission_currency
FROM trade t
JOIN order_record o          ON o.id = t.order_id
JOIN account a        ON a.id = t.account_id
JOIN asset ba         ON ba.id = t.base_asset_id
JOIN asset qa         ON qa.id = t.quote_asset_id
LEFT JOIN principal p ON p.id = t.principal_id` +
		whereFromClauses(clauses) +
		tradeListOrderBy(sortColumn, filter.Sort)
	if filter.Page.Limit > 0 {
		query += ` LIMIT ? OFFSET ?`
		queryArgs = append(queryArgs, filter.Page.Limit, max(filter.Page.Offset, 0))
	}
	rows, err := db.QueryContext(ctx, query, queryArgs...)
	if err != nil {
		return fwstore.TradeListPage{}, fmt.Errorf("store: list trade rows: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.Trade, 0)
	for rows.Next() {
		row, err := scanTradeListRow(rows)
		if err != nil {
			return fwstore.TradeListPage{}, err
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return fwstore.TradeListPage{}, fmt.Errorf("store: iterate trade rows: %w", err)
	}
	return fwstore.TradeListPage{
		Rows:  result,
		Total: total,
	}, nil
}

func tradeListClauses(filter fwstore.TradeListFilter) ([]string, []any) {
	clauses := make([]string, 0)
	args := make([]any, 0)
	if !filter.ExternalID.IsZero() {
		clauses = append(clauses, "t.external_id = ?")
		args = append(args, filter.ExternalID.Bytes())
	}
	appendMatcher(&clauses, &args, "a.code", filter.Account)
	appendMatcher(&clauses, &args, "ba.code", filter.BaseAsset)
	appendMatcher(&clauses, &args, "qa.code", filter.QuoteAsset)
	if filter.Side != nil {
		clauses = append(clauses, "t.side = ?")
		args = append(args, string(*filter.Side))
	}
	if filter.Source != "" {
		clauses = append(clauses, "t.source = ?")
		args = append(args, string(filter.Source))
	}
	appendTimeRangeFilter(&clauses, &args, "t.at", filter.At)
	appendDecimalRangeFilter(&clauses, &args, "t.quantity COLLATE DECIMAL", filter.Quantity)
	appendDecimalRangeFilter(&clauses, &args, "t.price COLLATE DECIMAL", filter.Price)
	appendDecimalRangeFilter(&clauses, &args, "t.lock_price COLLATE DECIMAL", filter.LockPrice)
	return clauses, args
}

func tradeListSortColumn(sort fwstore.SortSpec) string {
	columns := map[string]string{
		"account":    "a.code",
		"at":         "t.at",
		"baseAsset":  "ba.code",
		"lockPrice":  "t.lock_price COLLATE DECIMAL",
		"price":      "t.price COLLATE DECIMAL",
		"quantity":   "t.quantity COLLATE DECIMAL",
		"quoteAsset": "qa.code",
		"side":       "t.side",
		"source":     "t.source",
	}
	column := columns[sort.Column]
	if column == "" {
		column = "t.at"
	}
	return column
}

func tradeListOrderBy(sortColumn string, sort fwstore.SortSpec) string {
	direction := "ASC"
	tieDirection := "ASC"
	if sort.Column == "" ||
		(sortColumn == "t.at" && sort.Column != "at") ||
		sort.Descending {
		direction = "DESC"
		tieDirection = "DESC"
	}
	return "\nORDER BY " + sortColumn + " " + direction + ", t.id " + tieDirection
}

// listTrades is the shared trade-list query: it filters by the non-empty account
// and source, orders newest first by (at, id) per the §9 index, and applies the
// optional positive limit.
func (r *realmStore) listTrades(
	ctx context.Context, account domain.AccountID, source domain.Source, limit int,
) ([]domain.Trade, error) {
	q := tradeSelect + ` WHERE 1 = 1`
	args := make([]any, 0, 3)
	if account != "" {
		q += ` AND a.code = ?`
		args = append(args, account.String())
	}
	if source != "" {
		q += ` AND t.source = ?`
		args = append(args, string(source))
	}
	q += ` ORDER BY t.at DESC, t.id DESC`
	if limit > 0 {
		q += ` LIMIT ?`
		args = append(args, limit)
	}

	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list trades: %w", err)
	}
	defer func() { _ = rows.Close() }()
	return scanTrades(rows)
}

// listTradesByOrder returns all trade for one order (addressed by its external
// id), oldest first by (at, id). It backs GetOrder's trade list.
func (r *realmStore) listTradesByOrder(
	ctx context.Context, order domain.ExternalID,
) ([]domain.Trade, error) {
	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(
		ctx,
		tradeSelect+` WHERE o.external_id = ? ORDER BY t.at ASC, t.id ASC`,
		order.Bytes(),
	)
	if err != nil {
		return nil, fmt.Errorf("store: list trades by order: %w", err)
	}
	defer func() { _ = rows.Close() }()
	return scanTrades(rows)
}

func scanTrades(rows *sql.Rows) ([]domain.Trade, error) {
	result := make([]domain.Trade, 0)
	for rows.Next() {
		tr, err := scanTrade(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, tr)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate trades: %w", err)
	}
	return result, nil
}

func scanTradeListRow(rows *sql.Rows) (domain.Trade, error) {
	var (
		tradeExtID, orderExtID                    []byte
		account                                   string
		baseAsset, quoteAsset                     string
		principal                                 sql.NullString
		at, source, side, quantity, price, lockPx string
		commissionAmount, commissionCurrency      string
	)
	if err := rows.Scan(
		&tradeExtID, &orderExtID, &account, &baseAsset,
		&quoteAsset, &principal, &at, &source, &side, &quantity, &price, &lockPx,
		&commissionAmount, &commissionCurrency,
	); err != nil {
		return domain.Trade{}, fmt.Errorf("store: scan trade row: %w", err)
	}
	trade, err := tradeFromScanned(
		tradeExtID, orderExtID, account, baseAsset, quoteAsset, principal,
		at, source, side, quantity, price, lockPx, commissionAmount, commissionCurrency,
	)
	if err != nil {
		return domain.Trade{}, err
	}
	return trade, nil
}

func scanTrade(rows *sql.Rows) (domain.Trade, error) {
	var (
		tradeExtID, orderExtID                    []byte
		account                                   string
		baseAsset, quoteAsset                     string
		principal                                 sql.NullString
		at, source, side, quantity, price, lockPx string
		commissionAmount, commissionCurrency      string
	)
	if err := rows.Scan(
		&tradeExtID, &orderExtID, &account, &baseAsset, &quoteAsset, &principal,
		&at, &source, &side, &quantity, &price, &lockPx,
		&commissionAmount, &commissionCurrency,
	); err != nil {
		return domain.Trade{}, fmt.Errorf("store: scan trade: %w", err)
	}
	return tradeFromScanned(
		tradeExtID, orderExtID, account, baseAsset, quoteAsset, principal,
		at, source, side, quantity, price, lockPx, commissionAmount, commissionCurrency,
	)
}

func tradeFromScanned(
	tradeExtID []byte,
	orderExtID []byte,
	account string,
	baseAsset string,
	quoteAsset string,
	principal sql.NullString,
	at string,
	source string,
	side string,
	quantity string,
	price string,
	lockPx string,
	commissionAmount string,
	commissionCurrency string,
) (domain.Trade, error) {
	tradeXID, err := domain.ExternalIDFromBytes(tradeExtID)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: decode trade external id: %w", err)
	}
	orderXID, err := domain.ExternalIDFromBytes(orderExtID)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: decode trade order external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: parse trade at %q: %w", at, err)
	}
	trade := domain.Trade{
		ExternalID: tradeXID,
		Order:      orderXID,
		Account:    domain.AccountID(account),
		BaseAsset:  baseAsset,
		QuoteAsset: quoteAsset,
		Principal:  principal.String,
		At:         parsedAt,
		Source:     domain.Source(source),
		Side:       domain.OrderSide(side),
		Quantity:   quantity,
		Price:      price,
		LockPrice:  lockPx,
	}
	if commissionAmount != "" || commissionCurrency != "" {
		trade.Commission = &domain.Commission{
			Amount:   commissionAmount,
			Currency: commissionCurrency,
		}
	}
	return trade, nil
}

func commissionAmount(c *domain.Commission) string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func commissionCurrency(c *domain.Commission) string {
	if c == nil {
		return ""
	}
	return c.Currency
}

// validateCommission enforces the write-time Commission invariant shared by
// insertTrade and restoreTrade: a commission is either fully absent (both amount
// and currency empty) or fully present, and a present amount must be a valid
// decimal. A one-sided commission (exactly one of amount/currency set) would be
// silently dropped from the CommissionSubtotals rollup, understating the order
// commission, so it is rejected as invalid input rather than persisted.
func validateCommission(c *domain.Commission) error {
	amount := commissionAmount(c)
	currency := commissionCurrency(c)
	if (amount == "") != (currency == "") {
		return fmt.Errorf(
			"store: commission requires both amount and currency: %w",
			domain.ErrInvalid,
		)
	}
	if amount == "" {
		return nil
	}
	if _, err := decimal.NewFromString(amount); err != nil {
		return fmt.Errorf(
			"store: commission amount %q is not a valid decimal: %w",
			amount, domain.ErrInvalid,
		)
	}
	return nil
}

func commissionSubtotals(trades []domain.Trade) ([]domain.Commission, error) {
	amounts := make(map[string]decimal.Decimal)
	for _, trade := range trades {
		if trade.Commission == nil {
			continue
		}
		c := trade.Commission
		if c.Amount == "" || c.Currency == "" {
			continue
		}
		amount, err := decimal.NewFromString(c.Amount)
		if err != nil {
			return nil, fmt.Errorf(
				"store: parse commission amount %q: %w", c.Amount, err)
		}
		amounts[c.Currency] = amounts[c.Currency].Add(amount)
	}
	return commissionsFromAmountMap(amounts), nil
}

func commissionSubtotalsByOrder(
	ctx context.Context,
	q sqlQueryer,
	orders []domain.ExternalID,
) (map[domain.ExternalID][]domain.Commission, error) {
	result := make(map[domain.ExternalID][]domain.Commission, len(orders))
	if len(orders) == 0 {
		return result, nil
	}

	amountsByOrder := make(
		map[domain.ExternalID]map[string]decimal.Decimal,
		len(orders),
	)
	for start := 0; start < len(orders); start += commissionSubtotalOrderBatchSize {
		end := start + commissionSubtotalOrderBatchSize
		if end > len(orders) {
			end = len(orders)
		}
		if err := accumulateCommissionSubtotalsByOrder(
			ctx, q, orders[start:end], amountsByOrder,
		); err != nil {
			return nil, err
		}
	}
	for _, order := range orders {
		result[order] = commissionsFromAmountMap(amountsByOrder[order])
	}
	return result, nil
}

const commissionSubtotalOrderBatchSize = 500

func accumulateCommissionSubtotalsByOrder(
	ctx context.Context,
	q sqlQueryer,
	orders []domain.ExternalID,
	amountsByOrder map[domain.ExternalID]map[string]decimal.Decimal,
) error {
	placeholders := strings.TrimRight(strings.Repeat("?,", len(orders)), ",")
	args := make([]any, 0, len(orders))
	for _, order := range orders {
		args = append(args, order.Bytes())
	}
	rows, err := q.QueryContext(
		ctx,
		`SELECT o.external_id, t.commission_amount, t.commission_currency
FROM trade t
JOIN order_record o ON o.id = t.order_id
WHERE t.commission_amount <> ''
  AND t.commission_currency <> ''
  AND o.external_id IN (`+placeholders+`)`,
		args...,
	)
	if err != nil {
		return fmt.Errorf("store: list order commission subtotals: %w", err)
	}
	for rows.Next() {
		var orderBytes []byte
		var amountText, currency string
		if err := rows.Scan(&orderBytes, &amountText, &currency); err != nil {
			_ = rows.Close()
			return fmt.Errorf("store: scan order commission subtotal: %w", err)
		}
		order, err := domain.ExternalIDFromBytes(orderBytes)
		if err != nil {
			_ = rows.Close()
			return fmt.Errorf(
				"store: decode order commission external id: %w", err)
		}
		amount, err := decimal.NewFromString(amountText)
		if err != nil {
			_ = rows.Close()
			return fmt.Errorf(
				"store: parse commission amount %q: %w", amountText, err)
		}
		amounts := amountsByOrder[order]
		if amounts == nil {
			amounts = make(map[string]decimal.Decimal)
			amountsByOrder[order] = amounts
		}
		amounts[currency] = amounts[currency].Add(amount)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return fmt.Errorf("store: iterate order commission subtotals: %w", err)
	}
	if err := rows.Close(); err != nil {
		return fmt.Errorf("store: close order commission subtotals: %w", err)
	}
	return nil
}

func commissionsFromAmountMap(amounts map[string]decimal.Decimal) []domain.Commission {
	if len(amounts) == 0 {
		return []domain.Commission{}
	}
	currencies := make([]string, 0, len(amounts))
	for currency := range amounts {
		currencies = append(currencies, currency)
	}
	sort.Strings(currencies)
	out := make([]domain.Commission, 0, len(currencies))
	for _, currency := range currencies {
		out = append(out, domain.Commission{
			Amount:   amounts[currency].String(),
			Currency: currency,
		})
	}
	return out
}

// --- Settlement -------------------------------------------------------------

// RecordOrderSettlement persists one fill/settlement atomically in a single
// transaction: per-asset balance (realized P&L delta-accumulated inside the
// tx), the engine-applied account blocks, the optional trade, the fill event(s),
// the optional lock rewrite and the order
// status advance commit or roll back together. A zero st.Order is an
// in-memory-only hold with no order row: the order/event/lock writes are skipped
// and only the balance and block effects run. When AllowedFrom is
// non-empty the status UPDATE is guarded and a disallowed current status yields
// domain.ErrConflict with nothing written; otherwise a missing order yields
// domain.ErrNotFound. The block-audit row is NOT part of this tx; callers write
// it separately after a successful commit.
func (r *realmStore) RecordOrderSettlement(
	ctx context.Context, st domain.OrderSettlement,
) error {
	return r.recordOrderSettlement(ctx, st, nil)
}

func (r *realmStore) RecordOrderSettlementWithAttestation(
	ctx context.Context, st domain.OrderSettlement, attest fwstore.EventAttestor,
) error {
	return r.recordOrderSettlement(ctx, st, attest)
}

func (r *realmStore) recordOrderSettlement(
	ctx context.Context, st domain.OrderSettlement, attest fwstore.EventAttestor,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("store: begin record_order_settlement: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	if err := r.recordOrderSettlementTx(ctx, tx, st, attest); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("store: commit record_order_settlement: %w", err)
	}
	return nil
}

func (r *realmStore) recordOrderSettlementTx(
	ctx context.Context, tx *sql.Tx, st domain.OrderSettlement, attest fwstore.EventAttestor,
) error {
	// Resolve the settling account once; balance and blocks reuse it. The
	// account is the fill's account, always present on a settlement.
	accountID, err := resolveAccountID(ctx, tx, st.Account)
	if err != nil {
		return err
	}

	if st.ReservationApprovalID != "" {
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE reservation_intent SET state = ? WHERE approval_id = ?`,
			string(st.ReservationIntentState), st.ReservationApprovalID,
		); err != nil {
			return fmt.Errorf("store: settlement reservation intent state: %w", err)
		}
	}

	// Insert the initial held-intent row for a hold-accept settlement in the same
	// transaction as the order, so the order row and its durable reservation record
	// are atomic. The engine builds the intent but never writes it (a nested write
	// would self-deadlock on the single connection held by this transaction).
	if st.ReservationIntentUpsert != nil {
		if err := upsertReservationIntentTx(ctx, tx, *st.ReservationIntentUpsert); err != nil {
			return err
		}
	}

	// Per-asset balance: read-modify-write inside the tx so the realized-P&L
	// accumulate is consistent under the tx snapshot (SQLite serializes writers).
	for _, bal := range st.Balances {
		if err := settleBalanceTx(ctx, tx, accountID, bal); err != nil {
			return err
		}
	}

	// Mirror engine-applied account blocks (the block UPDATE only; the audit row
	// stays a post-commit write owned by the caller). A block names its own
	// account, which may differ from the fill account in principle, so resolve it.
	for _, blk := range st.Blocks {
		blkAccountID, err := resolveAccountID(ctx, tx, blk.Account)
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE account SET blocked = ?, block_reason = ? WHERE id = ?`,
			true, blk.Reason, blkAccountID,
		); err != nil {
			return fmt.Errorf("store: settlement mirror block %q: %w", blk.Account, err)
		}
	}

	// Trade row.
	if st.Trade != nil {
		if _, _, err := r.insertTrade(ctx, tx, *st.Trade); err != nil {
			return err
		}
	}

	// The remaining writes touch the order row; an in-memory-only hold (zero
	// Order) carries no order row, so skip them and only the balance/block
	// effects above run.
	if st.Order.IsZero() {
		return nil
	}

	// Resolve the order surrogate id once; events, the optional lock rewrite and
	// the status advance all reuse it.
	orderID, err := lookupOrderID(ctx, tx, st.Order)
	if err != nil {
		return err
	}
	if attest != nil && len(st.Events) == 0 {
		return fmt.Errorf(
			"store: settlement has no event to attest: %w", domain.ErrInvalid,
		)
	}

	// Fill event(s).
	for _, ev := range st.Events {
		recorded, err := appendOrderEventReturningTx(ctx, tx, orderID, ev)
		if err != nil {
			return err
		}
		if err := attestOrderEventTx(ctx, tx, recorded, attest); err != nil {
			return err
		}
	}

	// Lock rewrite: only when explicitly requested (nil-vs-empty matters: an
	// empty non-nil slice clears the column, nil leaves it).
	if st.SetLock {
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE order_record SET lock = ? WHERE id = ?`,
			nullableBlob(st.Lock), orderID,
		); err != nil {
			return fmt.Errorf("store: settlement lock: %w", err)
		}
	}

	// Remaining open quantity: the caller carries the report's LeavesQty; an
	// empty value leaves the column untouched.
	if st.Leaves != "" {
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE order_record SET leaves_quantity = ? WHERE id = ?`,
			st.Leaves, orderID,
		); err != nil {
			return fmt.Errorf("store: settlement leaves: %w", err)
		}
	}

	// Status advance last; guarded only when AllowedFrom is set.
	if err := guardedOrderStatus(
		ctx, tx, orderID, st.Order, st.OrderStatus, st.AllowedFrom,
	); err != nil {
		return err
	}

	return nil
}

// guardedOrderStatus advances an order's status inside tx, addressing it by its
// already-resolved surrogate id. When allowedFrom is non-empty the UPDATE only
// matches rows already in one of those statuses; a 0-rows result then means
// either the order is missing (domain.ErrNotFound) or its current status is
// disallowed (domain.ErrConflict), distinguished by a follow-up SELECT in the
// same tx. When allowedFrom is empty the UPDATE is unguarded and 0 rows means a
// missing order. The order external id is carried for error messages only.
func guardedOrderStatus(
	ctx context.Context,
	tx *sql.Tx,
	orderID int64,
	order domain.ExternalID,
	status domain.OrderStatus,
	allowedFrom []domain.OrderStatus,
) error {
	args := []any{string(status), orderID}
	q := `UPDATE order_record SET status = ? WHERE id = ?`
	if len(allowedFrom) > 0 {
		placeholders := strings.TrimSuffix(strings.Repeat("?,", len(allowedFrom)), ",")
		q += fmt.Sprintf(` AND status IN (%s)`, placeholders)
		for _, s := range allowedFrom {
			args = append(args, string(s))
		}
	}
	res, err := tx.ExecContext(ctx, q, args...)
	if err != nil {
		return fmt.Errorf("store: resolve order %q status: %w", order.String(), err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("store: resolve order %q status rows: %w", order.String(), err)
	}
	if n > 0 {
		return nil
	}
	// No row advanced: distinguish a missing order from a disallowed status.
	var cur string
	err = tx.QueryRowContext(
		ctx, `SELECT status FROM order_record WHERE id = ?`, orderID,
	).Scan(&cur)
	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("order %q: %w", order.String(), domain.ErrNotFound)
	}
	if err != nil {
		return fmt.Errorf("store: resolve order %q status probe: %w", order.String(), err)
	}
	return fmt.Errorf(
		"store: resolve order %q: status %q: %w", order.String(), cur, domain.ErrConflict,
	)
}

func appendOrderEventReturningTx(
	ctx context.Context, tx *sql.Tx, orderID int64, ev domain.OrderEvent,
) (domain.OrderEvent, error) {
	principalID, err := resolveOptionalPrincipalID(ctx, tx, ev.Principal)
	if err != nil {
		return domain.OrderEvent{}, err
	}
	xid, err := newExternalID()
	if err != nil {
		return domain.OrderEvent{}, err
	}
	at := nowStr()
	payloadJSON, err := json.Marshal(ev.Payload)
	if err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: marshal event payload: %w", err)
	}
	if _, err := tx.ExecContext(
		ctx,
		`INSERT INTO order_event
		 (external_id, order_id, principal_id, at, type, source, payload)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, principalID, at,
		string(ev.Type), string(ev.Source), string(payloadJSON),
	); err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: append order event: %w", err)
	}
	ev.ExternalID = xid
	ev.At = mustParseTime(at)
	return ev, nil
}

func attestOrderEventTx(
	ctx context.Context,
	tx *sql.Tx,
	event domain.OrderEvent,
	attest fwstore.EventAttestor,
) error {
	if attest == nil {
		return nil
	}
	att, ok, err := attest(ctx, event)
	if err != nil {
		return err
	}
	if !ok {
		return fmt.Errorf(
			"store: event %s has no attestation payload: %w",
			event.Type, domain.ErrInvalid,
		)
	}
	return putEventAttestationTx(ctx, tx, event.ExternalID, att)
}

// settleBalanceTx applies one per-asset fill outcome inside tx. Available,
// held, and incoming are independent optional engine-returned absolutes; an
// absent result preserves the prior value. Realized P&L is accumulated from the
// engine delta. The balance table is owned by another store group; this method
// touches it with direct SQL (never the public balance methods) to keep the
// whole settlement atomic.
func settleBalanceTx(
	ctx context.Context,
	tx *sql.Tx,
	accountID int64,
	bal domain.BalanceSettlement,
) error {
	assetID, err := resolveAssetID(ctx, tx, bal.Asset)
	if err != nil {
		return err
	}
	var prevAvail, prevHeld, prevIncoming, prevRealized, prevAvgPx string
	err = tx.QueryRowContext(
		ctx,
		`SELECT available, held, incoming, realized_pnl, average_entry_price
		 FROM balance WHERE account_id = ? AND asset_id = ?`,
		accountID, assetID,
	).Scan(&prevAvail, &prevHeld, &prevIncoming, &prevRealized, &prevAvgPx)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("store: settle balance %q read: %w", bal.Asset, err)
	}

	realized, err := domain.AddDecimals(prevRealized, bal.Outcome.RealizedPnlDelta)
	if err != nil {
		return fmt.Errorf("store: settle balance %q realized_pnl: %w", bal.Asset, err)
	}
	available := settleOrZero(settlementResultOrPrevious(bal.Outcome.BalanceResult, prevAvail))
	held := settleOrZero(settlementResultOrPrevious(bal.Outcome.HeldResult, prevHeld))
	incoming := settleOrZero(settlementResultOrPrevious(bal.Outcome.IncomingResult, prevIncoming))
	realized = settleOrZero(realized)
	if _, err := tx.ExecContext(
		ctx,
		`INSERT OR REPLACE INTO balance
		 (account_id, asset_id, available, held,
		  incoming, realized_pnl, average_entry_price, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		accountID, assetID,
		available, held, incoming, realized, prevAvgPx,
		nowStr(),
	); err != nil {
		return fmt.Errorf("store: settle balance %q write: %w", bal.Asset, err)
	}
	if err := pruneEmptySettlementBalanceTx(
		ctx, tx, accountID, assetID, bal.Asset,
		available, held, incoming, realized, prevAvgPx,
	); err != nil {
		return err
	}
	return nil
}

func pruneEmptySettlementBalanceTx(
	ctx context.Context,
	tx *sql.Tx,
	accountID int64,
	assetID int64,
	asset string,
	available string,
	held string,
	incoming string,
	realized string,
	averageEntryPrice string,
) error {
	if !balanceAmountsEmpty(available, held, incoming, realized, averageEntryPrice) {
		return nil
	}
	if _, err := tx.ExecContext(
		ctx,
		`DELETE FROM balance WHERE account_id = ? AND asset_id = ?`,
		accountID, assetID,
	); err != nil {
		return fmt.Errorf("store: prune empty settlement balance %q: %w", asset, err)
	}
	return nil
}

func balanceAmountsEmpty(
	available string, held string, incoming string, realized string, averageEntryPrice string,
) bool {
	return decimalZeroOrEmpty(available) &&
		decimalZeroOrEmpty(held) &&
		decimalZeroOrEmpty(incoming) &&
		decimalZeroOrEmpty(realized) &&
		decimalZeroOrEmpty(averageEntryPrice)
}

func decimalZeroOrEmpty(value string) bool {
	if value == "" {
		return true
	}
	parsed, err := decimal.NewFromString(value)
	return err == nil && parsed.IsZero()
}

// --- Orders-group small helpers ---------------------------------------------

// lookupOrderID resolves an order's external id to its surrogate id, mapping a
// missing order onto domain.ErrNotFound. It is the orders-group analogue of the
// dictionary resolvers in sqlite.go; it joins the order's children and the
// settlement writes to the order without exposing the surrogate id.
func lookupOrderID(
	ctx context.Context, q sqlQueryer, id domain.ExternalID,
) (int64, error) {
	var orderID int64
	err := q.QueryRowContext(
		ctx, `SELECT id FROM order_record WHERE external_id = ?`, id.Bytes(),
	).Scan(&orderID)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, fmt.Errorf("order %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return 0, fmt.Errorf("store: resolve order %q: %w", id.String(), err)
	}
	return orderID, nil
}

// lookupOrderEventID resolves an event's external id to its surrogate id,
// mapping a missing event onto domain.ErrNotFound. It is the analogue of
// lookupOrderID for the event stream; it keys the 1:1 attestation onto the event
// without exposing the surrogate id.
func lookupOrderEventID(
	ctx context.Context, q sqlQueryer, id domain.ExternalID,
) (int64, error) {
	var eventID int64
	err := q.QueryRowContext(
		ctx, `SELECT id FROM order_event WHERE external_id = ?`, id.Bytes(),
	).Scan(&eventID)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, fmt.Errorf("order event %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return 0, fmt.Errorf("store: resolve order event %q: %w", id.String(), err)
	}
	return eventID, nil
}

// nullableBlob maps a nil byte slice to a NULL column value and a non-nil slice
// (including an empty one) to itself, so the lock column distinguishes "no lock"
// (NULL) from a present-but-empty serialized lock.
func nullableBlob(b []byte) any {
	if b == nil {
		return nil
	}
	return b
}

// mustParseTime parses an RFC3339Nano string the store itself just formatted via
// nowStr; the format is guaranteed, so a parse error is impossible and the zero
// time is returned defensively rather than panicking on the write path.
func mustParseTime(s string) time.Time {
	t, _ := time.Parse(time.RFC3339Nano, s)
	return t
}

// settleOrZero maps an empty amount string to "0" so a balance column is never
// written empty.
func settleOrZero(s string) string {
	if s == "" {
		return "0"
	}
	return s
}

func settlementResultOrPrevious(next, prev string) string {
	if next != "" {
		return next
	}
	return prev
}
