// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

// Adjustments group of the SQLite store. Adjustments are machine records
// addressed by their opaque external id (assigned at insert by the connector).
// Account and asset references cascade on delete; the
// optional principal reference is cleared (SET NULL) when the principal is
// removed. The request and outcome columns are opaque JSON stored whole; this
// package never decodes them — callers supply pre-marshalled JSON and receive
// it back byte-for-byte.

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"go.openpit.dev/officer/framework/domain"
	fwstore "go.openpit.dev/officer/framework/store"
)

// adjustmentSelect is the shared projection for adjustment reads. The JOINs
// surface the account, asset, and optional principal as their codes so the
// surrogate ids never leave the store. The LEFT JOIN on principal yields NULL
// when the reference was cleared or never set.
const adjustmentSelect = `
SELECT adj.external_id, a.code, ast.code, p.code,
       adj.at, adj.source, adj.status, adj.request, adj.outcome
FROM adjustment adj
JOIN account  a   ON a.id   = adj.account_id
JOIN asset    ast ON ast.id = adj.asset_id
LEFT JOIN principal p ON p.id = adj.principal_id`

// AppendAdjustment records one adjustment outcome and its timestamp. The caller
// populates the typed Request and Accepted/Rejected fields; the store marshals
// them to opaque JSON for the request and outcome columns. A caller-supplied
// rec.ExternalID is used verbatim so the operator owns the handle; a zero id is
// generated by the connector. A duplicate supplied id is rejected with
// domain.ErrAlreadyExists (the external_id UNIQUE constraint, no pre-insert
// probe). The stored record with ExternalID and At populated is returned.
func (r *realmStore) AppendAdjustment(
	ctx context.Context, rec domain.AccountAdjustmentRecord,
) (domain.AccountAdjustmentRecord, error) {
	db, err := r.db()
	if err != nil {
		return rec, err
	}
	return appendAdjustment(ctx, db, rec)
}

func appendAdjustment(
	ctx context.Context, q sqlQueryer, rec domain.AccountAdjustmentRecord,
) (domain.AccountAdjustmentRecord, error) {
	exec, ok := q.(sqlExecer)
	if !ok {
		return rec, fmt.Errorf("store: append adjustment: queryer cannot execute")
	}
	accountID, err := resolveAccountID(ctx, q, rec.Account)
	if err != nil {
		return rec, err
	}
	assetID, err := resolveAssetID(ctx, q, rec.Asset)
	if err != nil {
		return rec, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, q, rec.Principal)
	if err != nil {
		return rec, err
	}

	reqJSON, err := json.Marshal(rec.Request)
	if err != nil {
		return rec, fmt.Errorf("store: marshal adjustment request: %w", err)
	}
	outcomeJSON, err := marshalAdjustmentOutcome(rec)
	if err != nil {
		return rec, err
	}

	status := adjustmentStatus(rec)

	xid, err := externalIDForInsert(rec.ExternalID)
	if err != nil {
		return rec, err
	}
	at := nowStr()

	if _, err := exec.ExecContext(
		ctx,
		`INSERT INTO adjustment
		 (external_id, account_id, asset_id, principal_id,
		  at, source, status, request, outcome)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), accountID, assetID, principalID,
		at, string(rec.Source), string(status),
		string(reqJSON), string(outcomeJSON),
	); err != nil {
		if isSQLiteUnique(err) {
			return rec, fmt.Errorf(
				"adjustment %q: %w", xid.String(), domain.ErrAlreadyExists,
			)
		}
		return rec, fmt.Errorf("store: append adjustment: %w", err)
	}

	rec.ExternalID = xid
	rec.At = mustParseTime(at)
	return rec, nil
}

// RecordAccountAdjustment writes the balance snapshot command, adjustment
// record, and audit row in one SQLite transaction.
func (r *realmStore) RecordAccountAdjustment(
	ctx context.Context, in fwstore.AccountAdjustmentPersistence,
) (domain.AccountAdjustmentRecord, error) {
	return r.recordAccountAdjustment(ctx, in)
}

func (r *realmStore) recordAccountAdjustment(
	ctx context.Context, in fwstore.AccountAdjustmentPersistence,
) (domain.AccountAdjustmentRecord, error) {
	db, err := r.db()
	if err != nil {
		return domain.AccountAdjustmentRecord{}, err
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return domain.AccountAdjustmentRecord{},
			fmt.Errorf("store: begin account adjustment tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	if in.UpsertBalance != nil {
		if err := importBalances(ctx, tx, []domain.Balance{*in.UpsertBalance}); err != nil {
			return domain.AccountAdjustmentRecord{}, err
		}
	}
	if in.DeleteBalance != nil {
		if _, err := tx.ExecContext(
			ctx,
			`DELETE FROM balance
			 WHERE account_id = (SELECT id FROM account WHERE code = ?)
			   AND asset_id   = (SELECT id FROM asset   WHERE code = ?)`,
			in.DeleteBalance.Account.String(), in.DeleteBalance.Asset,
		); err != nil {
			return domain.AccountAdjustmentRecord{},
				fmt.Errorf("store: delete adjustment balance: %w", err)
		}
	}
	if in.RealizedPnl != nil {
		if err := setBalanceRealizedPnlTx(ctx, tx, *in.RealizedPnl); err != nil {
			return domain.AccountAdjustmentRecord{}, err
		}
	}

	stored, err := appendAdjustment(ctx, tx, in.Adjustment)
	if err != nil {
		return domain.AccountAdjustmentRecord{}, err
	}
	if err := importAudit(ctx, tx, []fwstore.AuditEntry{in.Audit}); err != nil {
		return domain.AccountAdjustmentRecord{}, err
	}
	if err := tx.Commit(); err != nil {
		return domain.AccountAdjustmentRecord{},
			fmt.Errorf("store: commit account adjustment tx: %w", err)
	}
	return stored, nil
}

func setBalanceRealizedPnlTx(
	ctx context.Context,
	tx *sql.Tx,
	in fwstore.BalanceRealizedPnlPersistence,
) error {
	accountID, err := resolveAccountID(ctx, tx, in.Account)
	if err != nil {
		return err
	}
	assetID, err := resolveAssetID(ctx, tx, in.Asset)
	if err != nil {
		return err
	}
	var available, held, incoming, averageEntryPrice string
	err = tx.QueryRowContext(
		ctx,
		`SELECT available, held, incoming, average_entry_price
		 FROM balance WHERE account_id = ? AND asset_id = ?`,
		accountID, assetID,
	).Scan(&available, &held, &incoming, &averageEntryPrice)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("store: read realized pnl balance %q: %w", in.Asset, err)
	}

	realizedPnl := settleOrZero(in.RealizedPnl)
	if balanceAmountsEmpty(available, held, incoming, realizedPnl, averageEntryPrice) {
		if _, err := tx.ExecContext(
			ctx,
			`DELETE FROM balance WHERE account_id = ? AND asset_id = ?`,
			accountID, assetID,
		); err != nil {
			return fmt.Errorf("store: delete realized pnl balance %q: %w", in.Asset, err)
		}
		return nil
	}
	if _, err := tx.ExecContext(
		ctx,
		`INSERT OR REPLACE INTO balance
		 (account_id, asset_id, available, held,
		  incoming, realized_pnl, average_entry_price, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		accountID, assetID,
		settleOrZero(available),
		settleOrZero(held),
		settleOrZero(incoming),
		realizedPnl,
		averageEntryPrice,
		nowStr(),
	); err != nil {
		return fmt.Errorf("store: write realized pnl balance %q: %w", in.Asset, err)
	}
	return nil
}

// ListAdjustments returns the most recent n adjustment, newest first. A
// non-empty account or source filters to that value; a non-positive n returns
// an empty slice.
func (r *realmStore) ListAdjustments(
	ctx context.Context,
	account domain.AccountID,
	source domain.Source,
	n int,
) ([]domain.AccountAdjustmentRecord, error) {
	if n <= 0 {
		return make([]domain.AccountAdjustmentRecord, 0), nil
	}

	q := adjustmentSelect + ` WHERE 1 = 1`
	args := make([]any, 0, 3)
	if account != "" {
		q += ` AND a.code = ?`
		args = append(args, account.String())
	}
	if source != "" {
		q += ` AND adj.source = ?`
		args = append(args, string(source))
	}
	q += ` ORDER BY adj.at DESC, adj.id DESC LIMIT ?`
	args = append(args, n)

	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list adjustments: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.AccountAdjustmentRecord, 0, n)
	for rows.Next() {
		rec, err := scanAdjustment(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, rec)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate adjustments: %w", err)
	}
	return result, nil
}

// ListAdjustmentRows returns adjustment rows matching filter, with total count
// before paging.
func (r *realmStore) ListAdjustmentRows(
	ctx context.Context, filter fwstore.AdjustmentListFilter,
) (fwstore.AdjustmentListPage, error) {
	clauses, args := adjustmentListClauses(filter)
	db, err := r.db()
	if err != nil {
		return fwstore.AdjustmentListPage{}, err
	}
	countQuery := `SELECT COUNT(*)
FROM adjustment adj
JOIN account  a   ON a.id   = adj.account_id
JOIN asset    ast ON ast.id = adj.asset_id
LEFT JOIN principal p ON p.id = adj.principal_id` + whereFromClauses(clauses)
	var total int
	if err := db.QueryRowContext(ctx, countQuery, args...).Scan(&total); err != nil {
		return fwstore.AdjustmentListPage{}, fmt.Errorf("store: count adjustments: %w", err)
	}

	queryArgs := append([]any{}, args...)
	sortColumn := adjustmentListSortColumn(filter.Sort)
	query := `
SELECT adj.external_id, a.code, ast.code, p.code,
       adj.at, adj.source, adj.status, adj.request, adj.outcome
FROM adjustment adj
JOIN account  a   ON a.id   = adj.account_id
JOIN asset    ast ON ast.id = adj.asset_id
LEFT JOIN principal p ON p.id = adj.principal_id` +
		whereFromClauses(clauses) +
		adjustmentListOrderBy(sortColumn, filter.Sort)
	if filter.Page.Limit > 0 {
		query += ` LIMIT ? OFFSET ?`
		queryArgs = append(queryArgs, filter.Page.Limit, max(filter.Page.Offset, 0))
	}
	rows, err := db.QueryContext(ctx, query, queryArgs...)
	if err != nil {
		return fwstore.AdjustmentListPage{}, fmt.Errorf("store: list adjustment rows: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.AccountAdjustmentRecord, 0)
	for rows.Next() {
		row, err := scanAdjustmentListRow(rows)
		if err != nil {
			return fwstore.AdjustmentListPage{}, err
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return fwstore.AdjustmentListPage{}, fmt.Errorf(
			"store: iterate adjustment rows: %w", err,
		)
	}
	return fwstore.AdjustmentListPage{
		Rows:  result,
		Total: total,
	}, nil
}

func adjustmentListClauses(filter fwstore.AdjustmentListFilter) ([]string, []any) {
	clauses := make([]string, 0)
	args := make([]any, 0)
	if !filter.ExternalID.IsZero() {
		clauses = append(clauses, "adj.external_id = ?")
		args = append(args, filter.ExternalID.Bytes())
	}
	appendMatcher(&clauses, &args, "a.code", filter.Account)
	appendMatcher(&clauses, &args, "ast.code", filter.Asset)
	if filter.Source != "" {
		clauses = append(clauses, "adj.source = ?")
		args = append(args, string(filter.Source))
	}
	if filter.Status != nil {
		clauses = append(clauses, "adj.status = ?")
		args = append(args, string(*filter.Status))
	}
	appendTimeRangeFilter(&clauses, &args, "adj.at", filter.At)
	return clauses, args
}

func adjustmentListSortColumn(sort fwstore.SortSpec) string {
	columns := map[string]string{
		"account":   "a.code",
		"asset":     "ast.code",
		"at":        "adj.at",
		"principal": "COALESCE(p.code, '')",
		"source":    "adj.source",
		"status":    "adj.status",
	}
	column := columns[sort.Column]
	if column == "" {
		column = "adj.at"
	}
	return column
}

func adjustmentListOrderBy(sortColumn string, sort fwstore.SortSpec) string {
	direction := "ASC"
	tieDirection := "ASC"
	if sort.Column == "" ||
		(sortColumn == "adj.at" && sort.Column != "at") ||
		sort.Descending {
		direction = "DESC"
		tieDirection = "DESC"
	}
	return "\nORDER BY " + sortColumn + " " + direction +
		", adj.id " + tieDirection
}

func scanAdjustmentListRow(
	rows *sql.Rows,
) (domain.AccountAdjustmentRecord, error) {
	var (
		extID                                      []byte
		accountCode, assetCode                     string
		principal                                  sql.NullString
		at, source, status, requestStr, outcomeStr string
	)
	if err := rows.Scan(
		&extID, &accountCode, &assetCode, &principal,
		&at, &source, &status, &requestStr, &outcomeStr,
	); err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: scan adjustment row: %w", err,
		)
	}
	rec, err := adjustmentFromScanned(
		extID, accountCode, assetCode, principal, at, source, status, requestStr, outcomeStr,
	)
	if err != nil {
		return domain.AccountAdjustmentRecord{}, err
	}
	return rec, nil
}

// --- Adjustment helpers ------------------------------------------------------

// adjustmentStatus returns the status string for a record whose outcome is
// determined by whether Accepted or Rejected is set.
func adjustmentStatus(rec domain.AccountAdjustmentRecord) domain.AdjustmentStatus {
	if rec.Rejected != nil {
		return domain.AdjustmentStatusRejected
	}
	return domain.AdjustmentStatusAccepted
}

// adjustmentOutcomeEnvelope is the JSON envelope written to the outcome column.
// Exactly one of Accepted and Rejected is non-nil; this shape is the opaque
// contract between AppendAdjustment and the ListAdjustments read-back path.
type adjustmentOutcomeEnvelope struct {
	Accepted *domain.AdjustmentOutcomeAccepted `json:"accepted,omitempty"`
	Rejected *domain.AdjustmentOutcomeRejected `json:"rejected,omitempty"`
}

// marshalAdjustmentOutcome marshals the outcome fields into the opaque JSON
// envelope that is stored in the outcome column.
func marshalAdjustmentOutcome(rec domain.AccountAdjustmentRecord) ([]byte, error) {
	env := adjustmentOutcomeEnvelope{
		Accepted: rec.Accepted,
		Rejected: rec.Rejected,
	}
	b, err := json.Marshal(env)
	if err != nil {
		return nil, fmt.Errorf("store: marshal adjustment outcome: %w", err)
	}
	return b, nil
}

// scanAdjustment scans one adjustment projection, decoding the external-id
// BLOB, the nullable principal code, the at timestamp, and the opaque JSON
// request and outcome columns.
func scanAdjustment(rows *sql.Rows) (domain.AccountAdjustmentRecord, error) {
	var (
		extID                                      []byte
		accountCode, assetCode                     string
		principal                                  sql.NullString
		at, source, status, requestStr, outcomeStr string
	)
	if err := rows.Scan(
		&extID, &accountCode, &assetCode, &principal,
		&at, &source, &status, &requestStr, &outcomeStr,
	); err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf("store: scan adjustment: %w", err)
	}
	return adjustmentFromScanned(
		extID, accountCode, assetCode, principal, at, source, status, requestStr, outcomeStr,
	)
}

func adjustmentFromScanned(
	extID []byte,
	accountCode string,
	assetCode string,
	principal sql.NullString,
	at string,
	source string,
	status string,
	requestStr string,
	outcomeStr string,
) (domain.AccountAdjustmentRecord, error) {
	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: decode adjustment external id: %w", err,
		)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: parse adjustment at %q: %w", at, err,
		)
	}

	var req domain.AdjustmentRequest
	if err := json.Unmarshal([]byte(requestStr), &req); err != nil {
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: unmarshal adjustment request: %w", err,
		)
	}

	var env adjustmentOutcomeEnvelope
	if err := json.Unmarshal([]byte(outcomeStr), &env); err != nil {
		// A malformed outcome column is a corrupt row; surface it as an error
		// rather than masking it.
		return domain.AccountAdjustmentRecord{}, fmt.Errorf(
			"store: unmarshal adjustment outcome: %w", err,
		)
	}

	rec := domain.AccountAdjustmentRecord{
		ExternalID: xid,
		Account:    domain.AccountID(accountCode),
		Asset:      assetCode,
		Principal:  principal.String,
		At:         parsedAt,
		Source:     domain.Source(source),
		Request:    req,
		Accepted:   env.Accepted,
		Rejected:   env.Rejected,
	}
	_ = status // status is derived from Accepted/Rejected; stored for indexing
	return rec, nil
}
