// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

// Market-data group of the SQLite store: instances, instruments, and quotes.
// Instances are machine records addressed by their opaque external id; the
// surrogate key joins instruments internally and never crosses the interface
// boundary. Instruments are addressed by (instance external id, external
// symbol); quotes are 1:1 with an instrument. Asset references are resolved
// by code on write and surfaced as code on read; the label COLLATE NOCASE
// UNIQUE constraint on instances is mapped to domain.ErrAlreadyExists.

package sqlite

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"go.openpit.dev/officer/framework/domain"
)

// --- Market-data instances --------------------------------------------------

// mdInstanceSelect is the shared projection for instance reads. The external_id
// is the only public handle; the surrogate id is never surfaced.
const mdInstanceSelect = `
SELECT external_id, provider, label, credentials, enabled
FROM market_data_instance`

// CreateMarketDataInstance persists a new instance and returns it with
// ExternalID populated. A caller-supplied instance.ExternalID is used verbatim
// so the operator owns the handle; a zero id is generated by the connector.
// Returns domain.ErrAlreadyExists on a duplicate external id or a duplicate
// label (NOCASE UNIQUE); the error names the offending value. Neither path
// probes the table first: the two external_id and label UNIQUE constraints are
// distinguished by the offending column in the violation text.
func (r *realmStore) CreateMarketDataInstance(
	ctx context.Context, instance domain.MarketDataInstance,
) (domain.MarketDataInstance, error) {
	xid, err := externalIDForInsert(instance.ExternalID)
	if err != nil {
		return instance, err
	}
	db, err := r.db()
	if err != nil {
		return instance, err
	}
	_, err = db.ExecContext(
		ctx,
		`INSERT INTO market_data_instance
		 (external_id, provider, label, credentials, enabled)
		 VALUES (?, ?, ?, ?, ?)`,
		xid.Bytes(), instance.Provider, instance.Label,
		instance.Credentials, instance.Enabled,
	)
	if err != nil {
		if isSQLiteUniqueOn(err, "market_data_instance", "external_id") {
			return instance, fmt.Errorf(
				"market data instance %q: %w", xid.String(), domain.ErrAlreadyExists,
			)
		}
		if isSQLiteUnique(err) {
			return instance,
				fmt.Errorf("market data instance label %q: %w", instance.Label, domain.ErrAlreadyExists)
		}
		return instance, fmt.Errorf("store: create market data instance: %w", err)
	}
	instance.ExternalID = xid
	return instance, nil
}

// GetMarketDataInstance returns the instance with the given external id. The
// bool is false when absent.
func (r *realmStore) GetMarketDataInstance(
	ctx context.Context, id domain.ExternalID,
) (domain.MarketDataInstance, bool, error) {
	db, err := r.db()
	if err != nil {
		return domain.MarketDataInstance{}, false, err
	}
	row := db.QueryRowContext(
		ctx, mdInstanceSelect+` WHERE external_id = ?`, id.Bytes(),
	)
	inst, err := scanMDInstanceRow(row)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.MarketDataInstance{}, false, nil
	}
	if err != nil {
		return domain.MarketDataInstance{}, false, fmt.Errorf("store: get market data instance: %w", err)
	}
	return inst, true, nil
}

// ListMarketDataInstances returns every instance, ordered by external id.
func (r *realmStore) ListMarketDataInstances(
	ctx context.Context,
) ([]domain.MarketDataInstance, error) {
	return r.queryMDInstances(ctx, mdInstanceSelect+` ORDER BY external_id`)
}

// ListEnabledMarketDataInstances returns the enabled instances, ordered by
// external id.
func (r *realmStore) ListEnabledMarketDataInstances(
	ctx context.Context,
) ([]domain.MarketDataInstance, error) {
	return r.queryMDInstances(
		ctx, mdInstanceSelect+` WHERE enabled = 1 ORDER BY external_id`,
	)
}

// queryMDInstances runs q and scans the result into a slice of instances.
func (r *realmStore) queryMDInstances(
	ctx context.Context, q string, args ...any,
) ([]domain.MarketDataInstance, error) {
	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list market data instances: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.MarketDataInstance, 0)
	for rows.Next() {
		inst, err := scanMDInstance(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, inst)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate market data instances: %w", err)
	}
	return result, nil
}

// SetMarketDataInstanceEnabled toggles the enabled flag of the identified
// instance. Returns domain.ErrNotFound when absent.
func (r *realmStore) SetMarketDataInstanceEnabled(
	ctx context.Context, id domain.ExternalID, enabled bool,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`UPDATE market_data_instance SET enabled = ? WHERE external_id = ?`,
		enabled, id.Bytes(),
	)
	if err != nil {
		return fmt.Errorf("store: set market data instance enabled: %w", err)
	}
	return notFoundIfNoRows(res, "market data instance", id.String())
}

// UpdateMarketDataInstanceSettings replaces the editable settings (label,
// credentials) of the identified instance. Returns domain.ErrNotFound when
// absent, or domain.ErrAlreadyExists on a duplicate label.
func (r *realmStore) UpdateMarketDataInstanceSettings(
	ctx context.Context, id domain.ExternalID, label, credentials string,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`UPDATE market_data_instance SET label = ?, credentials = ? WHERE external_id = ?`,
		label, credentials, id.Bytes(),
	)
	if err != nil {
		if isSQLiteUnique(err) {
			return fmt.Errorf("market data instance label %q: %w", label, domain.ErrAlreadyExists)
		}
		return fmt.Errorf("store: update market data instance settings: %w", err)
	}
	return notFoundIfNoRows(res, "market data instance", id.String())
}

// DeleteMarketDataInstance removes the source and its feed-owned instruments
// and quotes while preserving the referenced global assets.
func (r *realmStore) DeleteMarketDataInstance(
	ctx context.Context, id domain.ExternalID,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("store: begin delete market data instance: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	instanceID, err := resolveInstanceID(ctx, tx, id)
	if err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, `
		DELETE FROM market_data_quote
		WHERE instrument_id IN (
			SELECT id FROM market_data_instrument WHERE instance_id = ?
		)`, instanceID); err != nil {
		return fmt.Errorf("store: delete market data quotes for instance: %w", err)
	}
	if _, err := tx.ExecContext(ctx,
		`DELETE FROM market_data_instrument WHERE instance_id = ?`,
		instanceID,
	); err != nil {
		return fmt.Errorf("store: delete market data instruments for instance: %w", err)
	}
	res, err := tx.ExecContext(ctx, `DELETE FROM market_data_instance WHERE id = ?`, instanceID)
	if err != nil {
		return fmt.Errorf("store: delete market data instance: %w", err)
	}
	if err := notFoundIfNoRows(res, "market data instance", id.String()); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("store: commit delete market data instance: %w", err)
	}
	return nil
}

func scanMDInstance(rows *sql.Rows) (domain.MarketDataInstance, error) {
	var (
		inst  domain.MarketDataInstance
		rawID []byte
	)
	if err := rows.Scan(
		&rawID, &inst.Provider, &inst.Label, &inst.Credentials, &inst.Enabled,
	); err != nil {
		return domain.MarketDataInstance{}, fmt.Errorf("store: scan market data instance: %w", err)
	}
	xid, err := domain.ExternalIDFromBytes(rawID)
	if err != nil {
		return domain.MarketDataInstance{}, fmt.Errorf("store: decode instance external id: %w", err)
	}
	inst.ExternalID = xid
	return inst, nil
}

func scanMDInstanceRow(row *sql.Row) (domain.MarketDataInstance, error) {
	var (
		inst  domain.MarketDataInstance
		rawID []byte
	)
	if err := row.Scan(
		&rawID, &inst.Provider, &inst.Label, &inst.Credentials, &inst.Enabled,
	); err != nil {
		return domain.MarketDataInstance{}, err
	}
	xid, err := domain.ExternalIDFromBytes(rawID)
	if err != nil {
		return domain.MarketDataInstance{}, fmt.Errorf("store: decode instance external id: %w", err)
	}
	inst.ExternalID = xid
	return inst, nil
}

// resolveInstanceID resolves an instance external id to its surrogate id. A
// missing instance is reported as domain.ErrNotFound.
func resolveInstanceID(
	ctx context.Context, q sqlQueryer, id domain.ExternalID,
) (int64, error) {
	var sid int64
	err := q.QueryRowContext(
		ctx,
		`SELECT id FROM market_data_instance WHERE external_id = ?`,
		id.Bytes(),
	).Scan(&sid)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, fmt.Errorf("market data instance %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return 0, fmt.Errorf("store: resolve instance %q: %w", id.String(), err)
	}
	return sid, nil
}

// --- Market-data instruments ------------------------------------------------

// mdInstrumentSelect is the shared projection for instrument reads. The
// instance reference is surfaced as the instance external id; base/quote are
// surfaced as human codes with their stable internal identifiers for runtime
// consumers; the instrument surrogate id is never surfaced.
const mdInstrumentSelect = `
SELECT i.external_id AS instance_xid, mdi.external_symbol,
       ba.code, qa.code, ba.id, qa.id, mdi.enabled, mdi.manual_price
FROM market_data_instrument mdi
JOIN market_data_instance i ON i.id = mdi.instance_id
JOIN asset ba               ON ba.id = mdi.base_asset_id
JOIN asset qa               ON qa.id = mdi.quote_asset_id`

// UpsertMarketDataInstrument inserts or replaces one instrument of an instance,
// keyed by (instance, external symbol). Unknown asset codes or unknown instance
// external ids are an error wrapping domain.ErrInvalid / domain.ErrNotFound.
func (r *realmStore) UpsertMarketDataInstrument(
	ctx context.Context, instrument domain.MarketDataInstrument,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	instanceID, err := resolveInstanceID(ctx, db, instrument.Instance)
	if err != nil {
		return err
	}
	baseID, err := resolveAssetID(ctx, db, instrument.BaseAsset)
	if err != nil {
		return err
	}
	quoteID, err := resolveAssetID(ctx, db, instrument.QuoteAsset)
	if err != nil {
		return err
	}
	// ON CONFLICT(instance_id, external_symbol) DO UPDATE: mutates the row in
	// place (base/quote asset, enabled, manual_price), so the existing row's
	// dependents are untouched rather than re-firing delete cascades.
	if _, err := db.ExecContext(
		ctx,
		`INSERT INTO market_data_instrument
		 (instance_id, external_symbol, base_asset_id, quote_asset_id,
		  enabled, manual_price)
		 VALUES (?, ?, ?, ?, ?, ?)
		 ON CONFLICT(instance_id, external_symbol) DO UPDATE SET
		   base_asset_id  = excluded.base_asset_id,
		   quote_asset_id = excluded.quote_asset_id,
		   enabled        = excluded.enabled,
		   manual_price   = excluded.manual_price`,
		instanceID, instrument.ExternalSymbol,
		baseID, quoteID, instrument.Enabled, instrument.ManualPrice,
	); err != nil {
		return fmt.Errorf("store: upsert market data instrument: %w", err)
	}
	return nil
}

// ListMarketDataInstruments returns every instrument of the instance, ordered
// by external symbol.
func (r *realmStore) ListMarketDataInstruments(
	ctx context.Context, instance domain.ExternalID,
) ([]domain.MarketDataInstrument, error) {
	return r.queryMDInstruments(
		ctx,
		mdInstrumentSelect+` WHERE i.external_id = ? ORDER BY mdi.external_symbol`,
		instance.Bytes(),
	)
}

// ListEnabledMarketDataInstruments returns the enabled instruments of the
// instance, ordered by external symbol.
func (r *realmStore) ListEnabledMarketDataInstruments(
	ctx context.Context, instance domain.ExternalID,
) ([]domain.MarketDataInstrument, error) {
	return r.queryMDInstruments(
		ctx,
		mdInstrumentSelect+
			` WHERE i.external_id = ? AND mdi.enabled = 1 ORDER BY mdi.external_symbol`,
		instance.Bytes(),
	)
}

// queryMDInstruments runs q with args and scans the result into a slice.
func (r *realmStore) queryMDInstruments(
	ctx context.Context, q string, args ...any,
) ([]domain.MarketDataInstrument, error) {
	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list market data instruments: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.MarketDataInstrument, 0)
	for rows.Next() {
		instr, err := scanMDInstrument(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, instr)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate market data instruments: %w", err)
	}
	return result, nil
}

// SetMarketDataInstrumentEnabled toggles the enabled flag of one instrument.
// Returns domain.ErrNotFound when absent.
func (r *realmStore) SetMarketDataInstrumentEnabled(
	ctx context.Context, instance domain.ExternalID, externalSymbol string, enabled bool,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`UPDATE market_data_instrument
		 SET enabled = ?
		 WHERE instance_id = (
		   SELECT id FROM market_data_instance WHERE external_id = ?
		 ) AND external_symbol = ?`,
		enabled, instance.Bytes(), externalSymbol,
	)
	if err != nil {
		return fmt.Errorf("store: set market data instrument enabled: %w", err)
	}
	return notFoundIfNoRows(res, "market data instrument", externalSymbol)
}

// DeleteMarketDataInstrument removes one instrument of an instance. Returns
// domain.ErrNotFound when absent.
func (r *realmStore) DeleteMarketDataInstrument(
	ctx context.Context, instance domain.ExternalID, externalSymbol string,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`DELETE FROM market_data_instrument
		 WHERE instance_id = (
		   SELECT id FROM market_data_instance WHERE external_id = ?
		 ) AND external_symbol = ?`,
		instance.Bytes(), externalSymbol,
	)
	if err != nil {
		return fmt.Errorf("store: delete market data instrument: %w", err)
	}
	return notFoundIfNoRows(res, "market data instrument", externalSymbol)
}

func scanMDInstrument(rows *sql.Rows) (domain.MarketDataInstrument, error) {
	var (
		instr  domain.MarketDataInstrument
		rawXID []byte
	)
	if err := rows.Scan(
		&rawXID, &instr.ExternalSymbol,
		&instr.BaseAsset, &instr.QuoteAsset,
		&instr.BaseAssetID, &instr.QuoteAssetID,
		&instr.Enabled, &instr.ManualPrice,
	); err != nil {
		return domain.MarketDataInstrument{}, fmt.Errorf("store: scan market data instrument: %w", err)
	}
	xid, err := domain.ExternalIDFromBytes(rawXID)
	if err != nil {
		return domain.MarketDataInstrument{},
			fmt.Errorf("store: decode instrument instance external id: %w", err)
	}
	instr.Instance = xid
	return instr, nil
}

// --- Market-data quotes -----------------------------------------------------

// mdQuoteSelect is the shared projection for quote reads. The instrument is
// identified by (instance external id, external symbol) and the base/quote
// asset codes are joined so no surrogate ids escape the store.
const mdQuoteSelect = `
SELECT i.external_id AS instance_xid, mdi.external_symbol,
       ba.code, qa.code,
       q.mark, q.bid, q.ask, q.as_of, q.received_at
FROM market_data_quote q
JOIN market_data_instrument mdi ON mdi.id = q.instrument_id
JOIN market_data_instance   i   ON i.id   = mdi.instance_id
JOIN asset ba                   ON ba.id  = mdi.base_asset_id
JOIN asset qa                   ON qa.id  = mdi.quote_asset_id`

// UpsertMarketDataQuote records the latest normalized quote for one configured
// instrument, keyed by (instance, external symbol). The quote row is 1:1 with
// the instrument; it is replaced on every update.
func (r *realmStore) UpsertMarketDataQuote(
	ctx context.Context, quote domain.MarketDataQuote,
) error {
	// Resolve the instrument's surrogate id from (instance external id, symbol).
	db, err := r.db()
	if err != nil {
		return err
	}
	var instrumentID int64
	err = db.QueryRowContext(
		ctx,
		`SELECT mdi.id
		 FROM market_data_instrument mdi
		 JOIN market_data_instance i ON i.id = mdi.instance_id
		 WHERE i.external_id = ? AND mdi.external_symbol = ?`,
		quote.Instance.Bytes(), quote.ExternalSymbol,
	).Scan(&instrumentID)
	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf(
			"market data instrument %q/%q: %w",
			quote.Instance.String(), quote.ExternalSymbol, domain.ErrNotFound,
		)
	}
	if err != nil {
		return fmt.Errorf("store: resolve instrument for quote: %w", err)
	}

	if _, err := db.ExecContext(
		ctx,
		`INSERT INTO market_data_quote
		 (instrument_id, mark, bid, ask, as_of, received_at)
		 VALUES (?, ?, ?, ?, ?, ?)
		 ON CONFLICT(instrument_id) DO UPDATE SET
		   mark        = excluded.mark,
		   bid         = excluded.bid,
		   ask         = excluded.ask,
		   as_of       = excluded.as_of,
		   received_at = excluded.received_at`,
		instrumentID,
		quote.Mark, quote.Bid, quote.Ask,
		quote.AsOf.UTC().Format(time.RFC3339Nano),
		quote.ReceivedAt.UTC().Format(time.RFC3339Nano),
	); err != nil {
		return fmt.Errorf("store: upsert market data quote: %w", err)
	}
	return nil
}

// ListMarketDataQuotes returns the latest quotes for one instance, ordered by
// external symbol. A zero instance id returns quotes for all instances.
func (r *realmStore) ListMarketDataQuotes(
	ctx context.Context, instance domain.ExternalID,
) ([]domain.MarketDataQuote, error) {
	var (
		q    string
		args []any
	)
	if instance.IsZero() {
		q = mdQuoteSelect + ` ORDER BY mdi.external_symbol`
	} else {
		q = mdQuoteSelect + ` WHERE i.external_id = ? ORDER BY mdi.external_symbol`
		args = []any{instance.Bytes()}
	}

	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list market data quotes: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.MarketDataQuote, 0)
	for rows.Next() {
		quote, err := scanMDQuote(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, quote)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate market data quotes: %w", err)
	}
	return result, nil
}

func scanMDQuote(rows *sql.Rows) (domain.MarketDataQuote, error) {
	var (
		quote    domain.MarketDataQuote
		rawXID   []byte
		asOf     string
		received string
	)
	if err := rows.Scan(
		&rawXID, &quote.ExternalSymbol,
		&quote.BaseAsset, &quote.QuoteAsset,
		&quote.Mark, &quote.Bid, &quote.Ask,
		&asOf, &received,
	); err != nil {
		return domain.MarketDataQuote{}, fmt.Errorf("store: scan market data quote: %w", err)
	}
	xid, err := domain.ExternalIDFromBytes(rawXID)
	if err != nil {
		return domain.MarketDataQuote{}, fmt.Errorf("store: decode quote instance external id: %w", err)
	}
	quote.Instance = xid

	asOfTime, err := time.Parse(time.RFC3339Nano, asOf)
	if err != nil {
		return domain.MarketDataQuote{}, fmt.Errorf("store: parse quote as_of %q: %w", asOf, err)
	}
	quote.AsOf = asOfTime

	recTime, err := time.Parse(time.RFC3339Nano, received)
	if err != nil {
		return domain.MarketDataQuote{}, fmt.Errorf("store: parse quote received_at %q: %w", received, err)
	}
	quote.ReceivedAt = recTime

	return quote, nil
}
