// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

// Orders group of the SQLite store: orders and their 1:1 signed approval, the
// immutable order-event stream, per-fill trade ("reports"), order counts and
// the atomic fill/settlement write. Every record here is machine-generated and
// addressed by its opaque external id; the surrogate key joins rows internally
// and never crosses the interface boundary. Account, asset and principal
// references are resolved by code on write and surfaced as code on read, so a
// surrogate id never leaks. The SDK-serialized reservation lock is persisted
// verbatim as a BLOB and read back byte-identical; this package never decodes it.

package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/shopspring/decimal"

	"go.openpit.dev/officer/framework/domain"
	fwstore "go.openpit.dev/officer/framework/store"
)

// --- Orders -----------------------------------------------------------------

// orderSelect is the shared projection for order reads. The JOINs surface the
// account, base/quote asset and (optional) principal as their codes so the
// surrogate ids never leave the store; the LEFT JOIN on principal yields NULL
// when the reference was cleared or never set. The lock BLOB is read back
// verbatim into the domain []byte.
const orderSelect = `
SELECT o.external_id, a.code, ba.code, qa.code, p.code,
       o.at, o.source_id, o.side_id, o.amount_kind_id, o.amount_value,
       o.leaves_quantity, o.price, o.status_id, o.drop_copy, o.lock
FROM order_record o
JOIN account a       ON a.id = o.account_id
JOIN asset ba        ON ba.id = o.base_asset_id
JOIN asset qa        ON qa.id = o.quote_asset_id
LEFT JOIN principal p ON p.id = o.principal_id`

// orderListSelect extends orderSelect with a "signed" rollup so the paged list
// view can report whether the order carries at least one Ed25519-signed event
// attestation without a second query per order. The correlated subquery is 1
// when any of the order's events has a signed attestation, else 0.
const orderListSelect = `
SELECT o.external_id, a.code, ba.code, qa.code, p.code,
       o.at, o.source_id, o.side_id, o.amount_kind_id, o.amount_value,
       o.leaves_quantity, o.price, o.status_id, o.drop_copy, o.lock,
       EXISTS (
           SELECT 1 FROM order_event e
           JOIN event_attestation ea ON ea.event_id = e.id
           WHERE e.order_id = o.id AND ea.alg_id = 1
       ) AS signed
FROM order_record o
JOIN account a       ON a.id = o.account_id
JOIN asset ba        ON ba.id = o.base_asset_id
JOIN asset qa        ON qa.id = o.quote_asset_id
LEFT JOIN principal p ON p.id = o.principal_id`

// CreateOrder inserts a new order and its submission time. It resolves the
// account and both assets by code to their surrogate ids and the optional
// principal to a nullable id, then persists the SDK-serialized lock blob
// verbatim. A caller-supplied o.ExternalID is used verbatim so the operator owns
// the handle; a zero id is generated by the connector. A duplicate supplied id
// is rejected with domain.ErrAlreadyExists (the external_id UNIQUE constraint,
// no pre-insert probe). It returns the order with ExternalID and At populated;
// the surrogate id is never surfaced.
func (r *realmStore) CreateOrder(
	ctx context.Context, o domain.Order,
) (domain.Order, error) {
	db, err := r.db()
	if err != nil {
		return domain.Order{}, err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return domain.Order{}, err
	}
	return createOrderTx(ctx, dictionaries, db, o)
}

func createOrderTx(
	ctx context.Context,
	dictionaries *enumDictionaries,
	q sqlReadWriter,
	o domain.Order,
) (domain.Order, error) {
	accountID, err := resolveAccountID(ctx, q, o.Account)
	if err != nil {
		return o, err
	}
	baseID, err := resolveAssetID(ctx, q, o.BaseAsset)
	if err != nil {
		return o, err
	}
	quoteID, err := resolveAssetID(ctx, q, o.QuoteAsset)
	if err != nil {
		return o, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, q, o.Principal)
	if err != nil {
		return o, err
	}
	o.Source = storedSource(o.Source)
	sourceID, err := dictionaries.id(sourceKindTable, "source", string(o.Source))
	if err != nil {
		return o, err
	}
	sideID, err := dictionaries.id(orderSideTable, "order side", string(o.Side))
	if err != nil {
		return o, err
	}
	amountKindID, err := dictionaries.id(
		orderAmountKindTable, "order amount kind", string(o.AmountKind),
	)
	if err != nil {
		return o, err
	}
	statusID, err := dictionaries.id(orderStatusTable, "order status", string(o.Status))
	if err != nil {
		return o, err
	}
	xid, err := externalIDForInsert(o.ExternalID)
	if err != nil {
		return o, err
	}
	at := nowStr()
	if _, err := q.ExecContext(
		ctx,
		`INSERT INTO order_record
		 (external_id, account_id, base_asset_id, quote_asset_id, principal_id,
		  at, source_id, side_id, amount_kind_id, amount_value,
		  leaves_quantity, price, status_id, drop_copy, lock)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), accountID, baseID, quoteID, principalID,
		at, sourceID, sideID, amountKindID,
		o.AmountValue, o.Leaves, o.Price,
		statusID, o.DropCopy, nullableBlob(o.Lock),
	); err != nil {
		if isSQLiteUnique(err) {
			return o, fmt.Errorf(
				"order %q: %w", xid.String(), domain.ErrAlreadyExists,
			)
		}
		return o, fmt.Errorf("store: create order: %w", err)
	}
	o.ExternalID = xid
	o.At = mustParseTime(at)
	return o, nil
}

func (r *realmStore) RecordOrderSubmission(
	ctx context.Context,
	o domain.Order,
	submitted domain.OrderEvent,
	apply func(domain.Order) (domain.OrderSettlement, error),
) (domain.Order, error) {
	return r.recordOrderSubmission(ctx, o, submitted, apply, nil)
}

func (r *realmStore) RecordOrderSubmissionWithAttestation(
	ctx context.Context,
	o domain.Order,
	submitted domain.OrderEvent,
	apply func(domain.Order) (domain.OrderSettlement, error),
	attest fwstore.EventAttestor,
) (domain.Order, error) {
	return r.recordOrderSubmission(ctx, o, submitted, apply, attest)
}

func (r *realmStore) recordOrderSubmission(
	ctx context.Context,
	o domain.Order,
	submitted domain.OrderEvent,
	apply func(domain.Order) (domain.OrderSettlement, error),
	attest fwstore.EventAttestor,
) (domain.Order, error) {
	db, err := r.db()
	if err != nil {
		return domain.Order{}, err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return domain.Order{}, err
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return domain.Order{}, fmt.Errorf("store: begin order submission: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	order, err := createOrderTx(ctx, dictionaries, tx, o)
	if err != nil {
		return domain.Order{}, err
	}
	orderID, err := lookupOrderID(ctx, tx, order.ExternalID)
	if err != nil {
		return domain.Order{}, err
	}
	if submitted.Order.IsZero() {
		submitted.Order = order.ExternalID
	}
	recordedSubmitted, _, err := appendOrderEventReturningTx(
		ctx, dictionaries, tx, orderID, submitted,
	)
	if err != nil {
		return domain.Order{}, err
	}

	settlement, err := apply(order)
	if err != nil {
		return domain.Order{}, err
	}
	if err := attestOrderEventTx(ctx, dictionaries, tx, recordedSubmitted, attest); err != nil {
		return domain.Order{}, err
	}
	if settlement.Order.IsZero() {
		settlement.Order = order.ExternalID
	}
	if settlement.Account == "" {
		settlement.Account = order.Account
	}
	if _, err := r.recordOrderSettlementTx(ctx, dictionaries, tx, settlement, attest); err != nil {
		return domain.Order{}, err
	}
	if err := tx.Commit(); err != nil {
		return domain.Order{}, fmt.Errorf("store: commit order submission: %w", err)
	}

	order.Status = settlement.OrderStatus
	order.Lock = settlement.Lock
	if settlement.Leaves != "" {
		order.Leaves = settlement.Leaves
	}
	return order, nil
}

// UpdateOrderStatus updates the status of the order addressed by external id.
func (r *realmStore) UpdateOrderStatus(
	ctx context.Context, id domain.ExternalID, status domain.OrderStatus,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return err
	}
	statusID, err := dictionaries.id(orderStatusTable, "order status", string(status))
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`UPDATE order_record SET status_id = ? WHERE external_id = ?`,
		statusID, id.Bytes(),
	)
	if err != nil {
		return fmt.Errorf("store: update order status: %w", err)
	}
	return notFoundIfNoRows(res, "order", id.String())
}

// SetOrderLock replaces the persisted SDK-serialized lock blob of the order
// addressed by external id, writing the bytes verbatim. A nil lock clears the
// column.
func (r *realmStore) SetOrderLock(
	ctx context.Context, id domain.ExternalID, lock []byte,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	res, err := db.ExecContext(
		ctx,
		`UPDATE order_record SET lock = ? WHERE external_id = ?`,
		nullableBlob(lock), id.Bytes(),
	)
	if err != nil {
		return fmt.Errorf("store: set order lock: %w", err)
	}
	return notFoundIfNoRows(res, "order", id.String())
}

// PutEventAttestation stamps the attestation envelope onto the order-history
// event addressed by external id, write-once: it inserts the 1:1
// event_attestation row only when the event carries none yet (only event_id
// conflicts are ignored), so a retry or a later write never clobbers an
// already-issued envelope. An already-stamped event is a no-op; a missing event
// returns domain.ErrNotFound so callers cannot silently commit an unsigned
// event.
func (r *realmStore) PutEventAttestation(
	ctx context.Context, eventID domain.ExternalID, att domain.EventAttestation,
) error {
	db, err := r.db()
	if err != nil {
		return err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return err
	}
	return putEventAttestationTx(ctx, dictionaries, db, eventID, att)
}

func putEventAttestationTx(
	ctx context.Context,
	dictionaries *enumDictionaries,
	q sqlReadWriter,
	eventID domain.ExternalID,
	att domain.EventAttestation,
) error {
	surrogate, err := lookupOrderEventID(ctx, q, eventID)
	if err != nil {
		return err
	}
	var signingKeyID sql.NullInt64
	if att.KeyID != "" {
		id, err := resolveSigningKeyID(ctx, q, att.KeyID)
		if err != nil {
			return err
		}
		signingKeyID = sql.NullInt64{Int64: id, Valid: true}
	}
	algID, err := dictionaries.id(attestationAlgTable, "attestation algorithm", att.Alg)
	if err != nil {
		return err
	}
	requestTypeID, err := dictionaries.id(
		attestationRequestTypeTable, "attestation request type", string(att.RequestType),
	)
	if err != nil {
		return err
	}
	modeID, err := dictionaries.id(attestationModeTable, "attestation mode", att.Mode)
	if err != nil {
		return err
	}
	if _, err := q.ExecContext(
		ctx,
		`INSERT INTO event_attestation
		 (event_id, token, signing_key_id, alg_id, request_type_id, mode_id, issued_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?)
		 ON CONFLICT(event_id) DO NOTHING`,
		surrogate, att.Token, signingKeyID, algID, requestTypeID, modeID, att.IssuedAt,
	); err != nil {
		return fmt.Errorf("store: put event attestation: %w", err)
	}
	return nil
}

// GetOrder returns the order addressed by external id together with its events
// (each carrying its 1:1 signed attestation when one was issued) and trades.
// Returns domain.ErrNotFound when the order is absent.
//
// Each event's attestation is persisted in event_attestation (written by
// PutEventAttestation, write-once) and folded into OrderEvent.Attestation by the
// event read (nil when the event is unattested), so a caller presenting an order
// gets every event's envelope metadata without a second round-trip.
func (r *realmStore) GetOrder(
	ctx context.Context, id domain.ExternalID,
) (domain.OrderDetail, error) {
	db, err := r.db()
	if err != nil {
		return domain.OrderDetail{}, err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return domain.OrderDetail{}, err
	}
	row := db.QueryRowContext(ctx, orderSelect+` WHERE o.external_id = ?`, id.Bytes())
	o, err := scanOrderRow(dictionaries, row)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.OrderDetail{}, fmt.Errorf("order %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return domain.OrderDetail{}, fmt.Errorf("store: get order: %w", err)
	}

	events, err := r.ListOrderEvents(ctx, id)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	trades, err := r.listTradesByOrder(ctx, id)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	o.CommissionSubtotals, err = commissionSubtotals(id, trades, events)
	if err != nil {
		return domain.OrderDetail{}, err
	}
	return domain.OrderDetail{Order: o, Events: events, Trades: trades}, nil
}

// ListOrders returns the most recent n orders for an account, newest first. An
// empty account spans every account; an empty source spans every source; a
// non-positive n returns an empty slice.
func (r *realmStore) ListOrders(
	ctx context.Context, account domain.AccountID, source domain.Source, n int,
) ([]domain.Order, error) {
	if n <= 0 {
		return make([]domain.Order, 0), nil
	}
	return r.listOrders(ctx, account, source, n)
}

// ListAllOrders returns every order for an account, newest first. It is used by
// exports that must not inherit UI display limits.
func (r *realmStore) ListAllOrders(
	ctx context.Context, account domain.AccountID, source domain.Source,
) ([]domain.Order, error) {
	return r.listOrders(ctx, account, source, 0)
}

// ListOrderRows returns orders matching filter, with total count before paging.
func (r *realmStore) ListOrderRows(
	ctx context.Context, filter fwstore.OrderListFilter,
) (fwstore.OrderListPage, error) {
	dictionaries, err := r.dictionaries()
	if err != nil {
		return fwstore.OrderListPage{}, err
	}
	where, args, err := orderListWhere(dictionaries, filter)
	if err != nil {
		return fwstore.OrderListPage{}, err
	}
	countQuery := `SELECT COUNT(*)
FROM order_record o
JOIN account a       ON a.id = o.account_id
JOIN asset ba        ON ba.id = o.base_asset_id
JOIN asset qa        ON qa.id = o.quote_asset_id
LEFT JOIN principal p ON p.id = o.principal_id` + where
	db, err := r.db()
	if err != nil {
		return fwstore.OrderListPage{}, err
	}
	var total int
	if err := db.QueryRowContext(ctx, countQuery, args...).Scan(&total); err != nil {
		return fwstore.OrderListPage{}, fmt.Errorf("store: count order rows: %w", err)
	}

	queryArgs := append([]any{}, args...)
	query := orderListSelect + where + orderListOrderBy(filter.Sort)
	if filter.Page.Limit > 0 {
		query += ` LIMIT ? OFFSET ?`
		queryArgs = append(queryArgs, filter.Page.Limit, max(filter.Page.Offset, 0))
	}
	rows, err := db.QueryContext(ctx, query, queryArgs...)
	if err != nil {
		return fwstore.OrderListPage{}, fmt.Errorf("store: list order rows: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]fwstore.OrderListRow, 0)
	orderIDs := make([]domain.ExternalID, 0)
	for rows.Next() {
		o, signed, err := scanOrderListRow(dictionaries, rows)
		if err != nil {
			return fwstore.OrderListPage{}, err
		}
		result = append(result, fwstore.OrderListRow{Order: o, Signed: signed})
		orderIDs = append(orderIDs, o.ExternalID)
	}
	if err := rows.Err(); err != nil {
		return fwstore.OrderListPage{}, fmt.Errorf("store: iterate order rows: %w", err)
	}
	subtotals, err := commissionSubtotalsByOrder(ctx, dictionaries, db, orderIDs)
	if err != nil {
		return fwstore.OrderListPage{}, err
	}
	for i := range result {
		result[i].Order.CommissionSubtotals = subtotals[result[i].Order.ExternalID]
	}
	return fwstore.OrderListPage{Rows: result, Total: total}, nil
}

// listOrders is the shared order-list query: it filters by the non-empty
// account and source, orders newest first by (at, id) per the §9 index, and
// applies the optional positive limit.
func (r *realmStore) listOrders(
	ctx context.Context, account domain.AccountID, source domain.Source, limit int,
) ([]domain.Order, error) {
	page, err := r.ListOrderRows(ctx, fwstore.OrderListFilter{
		Account: account,
		Source:  source,
		Sort:    fwstore.SortSpec{Column: "at", Descending: true},
		Page:    fwstore.PageSpec{Limit: limit},
	})
	if err != nil {
		return nil, err
	}
	result := make([]domain.Order, 0, len(page.Rows))
	for _, row := range page.Rows {
		result = append(result, row.Order)
	}
	return result, nil
}

func orderListWhere(
	dictionaries *enumDictionaries,
	filter fwstore.OrderListFilter,
) (string, []any, error) {
	clauses := make([]string, 0)
	args := make([]any, 0)
	if filter.Account != "" {
		clauses = append(clauses, "a.code = ?")
		args = append(args, filter.Account.String())
	}
	if filter.Source != "" {
		id, err := dictionaries.id(sourceKindTable, "source", string(filter.Source))
		if err != nil {
			return "", nil, err
		}
		clauses = append(clauses, "o.source_id = ?")
		args = append(args, id)
	}
	if filter.Side != nil {
		id, err := dictionaries.id(orderSideTable, "order side", string(*filter.Side))
		if err != nil {
			return "", nil, err
		}
		clauses = append(clauses, "o.side_id = ?")
		args = append(args, id)
	}
	if len(filter.Status) > 0 {
		placeholders := strings.TrimRight(strings.Repeat("?,", len(filter.Status)), ",")
		clauses = append(clauses, "o.status_id IN ("+placeholders+")")
		for _, status := range filter.Status {
			id, err := dictionaries.id(orderStatusTable, "order status", string(status))
			if err != nil {
				return "", nil, err
			}
			args = append(args, id)
		}
	}
	appendMatcher(&clauses, &args, "ba.code", filter.BaseAsset)
	appendMatcher(&clauses, &args, "qa.code", filter.QuoteAsset)
	appendDecimalRangeFilter(&clauses, &args, "o.amount_value", filter.Amount)
	appendDecimalRangeFilter(&clauses, &args, "o.price", filter.Price)
	appendTimeRangeFilter(&clauses, &args, "o.at", filter.At)
	if len(clauses) == 0 {
		return "", args, nil
	}
	return "\nWHERE " + strings.Join(clauses, " AND "), args, nil
}

func orderListOrderBy(sort fwstore.SortSpec) string {
	columns := map[string]string{
		"account":     "a.code",
		"at":          "o.at",
		"baseAsset":   "ba.code",
		"price":       "o.price",
		"quoteAsset":  "qa.code",
		"side":        "o.side_id",
		"source":      "o.source_id",
		"status":      "o.status_id",
		"amountValue": "o.amount_value",
	}
	column := columns[sort.Column]
	if column == "" {
		column = "o.at"
		sort.Descending = true
	}
	direction := "ASC"
	tieDirection := "ASC"
	if sort.Descending {
		direction = "DESC"
		tieDirection = "DESC"
	}
	return "\nORDER BY " + column + " " + direction + ", o.id " + tieDirection
}

// CountOrders returns the total number of orders recorded in the realm.
func (r *realmStore) CountOrders(ctx context.Context) (int, error) {
	db, err := r.db()
	if err != nil {
		return 0, err
	}
	var n int
	if err := db.QueryRowContext(
		ctx, `SELECT COUNT(*) FROM order_record`,
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count orders: %w", err)
	}
	return n, nil
}

// CountActiveOrders returns orders in the working lifecycle set.
func (r *realmStore) CountActiveOrders(ctx context.Context) (int, error) {
	db, err := r.db()
	if err != nil {
		return 0, err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return 0, err
	}
	statuses := []domain.OrderStatus{
		domain.OrderStatusSubmitted,
		domain.OrderStatusAccepted,
		domain.OrderStatusCommitted,
		domain.OrderStatusPartiallyFilled,
	}
	statusIDs := make([]any, 0, len(statuses))
	for _, status := range statuses {
		id, err := dictionaries.id(orderStatusTable, "order status", string(status))
		if err != nil {
			return 0, err
		}
		statusIDs = append(statusIDs, id)
	}
	var n int
	if err := db.QueryRowContext(
		ctx,
		`SELECT COUNT(*) FROM order_record
		 WHERE status_id IN (?, ?, ?, ?)`,
		statusIDs...,
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count active orders: %w", err)
	}
	return n, nil
}

// CountOrdersSince returns the number of orders whose at timestamp is at or
// after since. The at column is RFC3339Nano UTC text, so the boundary is
// formatted the same way for a lexicographic comparison.
func (r *realmStore) CountOrdersSince(ctx context.Context, since time.Time) (int, error) {
	db, err := r.db()
	if err != nil {
		return 0, err
	}
	var n int
	if err := db.QueryRowContext(
		ctx,
		`SELECT COUNT(*) FROM order_record WHERE at >= ?`,
		since.UTC().Format(time.RFC3339Nano),
	).Scan(&n); err != nil {
		return 0, fmt.Errorf("store: count orders since: %w", err)
	}
	return n, nil
}

func (r *realmStore) ExecutionReportExists(
	ctx context.Context, id domain.ExternalID,
) (bool, error) {
	if id.IsZero() {
		return false, nil
	}
	db, err := r.db()
	if err != nil {
		return false, err
	}
	var one int
	err = db.QueryRowContext(
		ctx,
		`SELECT 1 FROM execution_report WHERE external_id = ?`,
		id.Bytes(),
	).Scan(&one)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("store: check execution report %q: %w", id, err)
	}
	return true, nil
}

func scanOrderRow(
	dictionaries *enumDictionaries,
	row *sql.Row,
) (domain.Order, error) {
	var o domain.Order
	if err := scanOrderInto(dictionaries, row.Scan, &o); err != nil {
		return domain.Order{}, err
	}
	return o, nil
}

// scanOrderListRow scans one orderListSelect projection, returning the order
// plus the "signed" rollup: whether any of its events carries an Ed25519-signed
// attestation. An order with no attestation, or only eSign-off ("none")
// attestations, reports false.
func scanOrderListRow(
	dictionaries *enumDictionaries,
	rows *sql.Rows,
) (domain.Order, bool, error) {
	var o domain.Order
	var signed bool
	if err := scanOrderInto(dictionaries, func(dest ...any) error {
		return rows.Scan(append(dest, &signed)...)
	}, &o); err != nil {
		return domain.Order{}, false, fmt.Errorf("store: scan order list row: %w", err)
	}
	return o, signed, nil
}

// scanOrderInto scans one order projection through scan into o, decoding the
// external-id BLOB, the nullable principal code and the nullable lock BLOB and
// parsing the submission time. The scan func is *sql.Row.Scan or *sql.Rows.Scan.
func scanOrderInto(
	dictionaries *enumDictionaries,
	scan func(...any) error,
	o *domain.Order,
) error {
	var (
		extID                          []byte
		principal                      sql.NullString
		at                             string
		sourceID, sideID, amountKindID int64
		statusID                       int64
		amountValue, leaves, price     string
		dropCopy                       bool
		lock                           []byte
	)
	if err := scan(
		&extID, &o.Account, &o.BaseAsset, &o.QuoteAsset, &principal,
		&at, &sourceID, &sideID, &amountKindID, &amountValue,
		&leaves, &price, &statusID, &dropCopy, &lock,
	); err != nil {
		return err
	}
	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return fmt.Errorf("store: decode order external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return fmt.Errorf("store: parse order at %q: %w", at, err)
	}
	source, err := dictionaries.code(sourceKindTable, "source", sourceID)
	if err != nil {
		return err
	}
	side, err := dictionaries.code(orderSideTable, "order side", sideID)
	if err != nil {
		return err
	}
	amountKind, err := dictionaries.code(
		orderAmountKindTable, "order amount kind", amountKindID,
	)
	if err != nil {
		return err
	}
	status, err := dictionaries.code(orderStatusTable, "order status", statusID)
	if err != nil {
		return err
	}
	o.ExternalID = xid
	o.At = parsedAt
	o.Principal = principal.String
	o.Source = domain.Source(source)
	o.Side = domain.OrderSide(side)
	o.AmountKind = domain.OrderAmountKind(amountKind)
	o.AmountValue = amountValue
	o.Leaves = leaves
	o.Price = price
	o.Status = domain.OrderStatus(status)
	o.DropCopy = dropCopy
	o.Lock = lock
	return nil
}

// --- Order events -----------------------------------------------------------

// orderEventSelect is the shared projection for event reads. The event links to
// its order through the surrogate FK internally; reads surface only the event's
// own fields plus the optional principal code and, when present, the event's 1:1
// signed attestation metadata (token verbatim, key UUID, alg, request type,
// mode, issued-at). A NULL token means the event carries no attestation.
const orderEventSelect = `
SELECT e.external_id, e.at, e.type_id, e.source_id, p.code, e.payload,
       ea.token, sk.key_id, ea.alg_id, ea.request_type_id, ea.mode_id,
       ea.issued_at
FROM order_event e
LEFT JOIN principal p ON p.id = e.principal_id
LEFT JOIN event_attestation ea ON ea.event_id = e.id
LEFT JOIN signing_key sk ON sk.id = ea.signing_key_id`

// AppendOrderEvent adds an event to the stream of the order named by ev.Order,
// assigning the event's external id and timestamp. The payload is marshalled to
// opaque JSON and stored whole.
func (r *realmStore) AppendOrderEvent(
	ctx context.Context, ev domain.OrderEvent,
) (domain.OrderEvent, error) {
	ev.Source = storedSource(ev.Source)
	db, err := r.db()
	if err != nil {
		return domain.OrderEvent{}, err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return domain.OrderEvent{}, err
	}
	orderID, err := lookupOrderID(ctx, db, ev.Order)
	if err != nil {
		return ev, err
	}
	typeID, err := dictionaries.id(orderEventTypeTable, "order event type", string(ev.Type))
	if err != nil {
		return ev, err
	}
	sourceID, err := dictionaries.id(sourceKindTable, "source", string(ev.Source))
	if err != nil {
		return ev, err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, db, ev.Principal)
	if err != nil {
		return ev, err
	}
	xid, err := newExternalID()
	if err != nil {
		return ev, err
	}
	payloadJSON, err := json.Marshal(ev.Payload)
	if err != nil {
		return ev, fmt.Errorf("store: marshal event payload: %w", err)
	}
	at := nowStr()
	if _, err := db.ExecContext(
		ctx,
		`INSERT INTO order_event
		 (external_id, order_id, principal_id, at, type_id, source_id, payload)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, principalID, at,
		typeID, sourceID, string(payloadJSON),
	); err != nil {
		return ev, fmt.Errorf("store: append order event: %w", err)
	}
	ev.ExternalID = xid
	ev.At = mustParseTime(at)
	return ev, nil
}

// ListOrderEvents returns all events for the order addressed by external id,
// oldest first by (at, id).
func (r *realmStore) ListOrderEvents(
	ctx context.Context, order domain.ExternalID,
) ([]domain.OrderEvent, error) {
	db, err := r.db()
	if err != nil {
		return nil, err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(
		ctx,
		orderEventSelect+`
		 JOIN order_record o ON o.id = e.order_id
		 WHERE o.external_id = ?
		 ORDER BY e.at ASC, e.id ASC`,
		order.Bytes(),
	)
	if err != nil {
		return nil, fmt.Errorf("store: list order events: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.OrderEvent, 0)
	for rows.Next() {
		ev, err := scanOrderEvent(dictionaries, rows, order)
		if err != nil {
			return nil, err
		}
		result = append(result, ev)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate order events: %w", err)
	}
	return result, nil
}

// scanOrderEvent scans one event projection, folding in the event's 1:1
// attestation when present. The parent order's external id is carried in by the
// caller (it is the query key) so it need not be re-selected.
func scanOrderEvent(
	dictionaries *enumDictionaries,
	rows *sql.Rows,
	order domain.ExternalID,
) (domain.OrderEvent, error) {
	var (
		extID                                 []byte
		at                                    string
		typeID, sourceID                      int64
		principal                             sql.NullString
		payloadStr                            string
		attToken, attKeyID                    sql.NullString
		attAlgID, attRequestTypeID, attModeID sql.NullInt64
		attIssuedAt                           sql.NullString
	)
	if err := rows.Scan(
		&extID, &at, &typeID, &sourceID, &principal, &payloadStr,
		&attToken, &attKeyID, &attAlgID, &attRequestTypeID, &attModeID,
		&attIssuedAt,
	); err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: scan order event: %w", err)
	}
	xid, err := domain.ExternalIDFromBytes(extID)
	if err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: decode event external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: parse event at %q: %w", at, err)
	}
	typ, err := dictionaries.code(orderEventTypeTable, "order event type", typeID)
	if err != nil {
		return domain.OrderEvent{}, err
	}
	source, err := dictionaries.code(sourceKindTable, "source", sourceID)
	if err != nil {
		return domain.OrderEvent{}, err
	}
	var payload domain.OrderEventPayload
	if err := json.Unmarshal([]byte(payloadStr), &payload); err != nil {
		return domain.OrderEvent{}, fmt.Errorf("store: unmarshal event payload: %w", err)
	}
	ev := domain.OrderEvent{
		ExternalID: xid,
		Order:      order,
		At:         parsedAt,
		Type:       domain.OrderEventType(typ),
		Source:     domain.Source(source),
		Principal:  principal.String,
		Payload:    payload,
	}
	if attToken.Valid {
		alg, err := dictionaries.code(attestationAlgTable, "attestation algorithm", attAlgID.Int64)
		if err != nil {
			return domain.OrderEvent{}, err
		}
		requestType, err := dictionaries.code(
			attestationRequestTypeTable, "attestation request type", attRequestTypeID.Int64,
		)
		if err != nil {
			return domain.OrderEvent{}, err
		}
		mode, err := dictionaries.code(attestationModeTable, "attestation mode", attModeID.Int64)
		if err != nil {
			return domain.OrderEvent{}, err
		}
		ev.Attestation = &domain.EventAttestation{
			Token:       attToken.String,
			KeyID:       attKeyID.String,
			Alg:         alg,
			RequestType: domain.AttestationRequestType(requestType),
			Mode:        mode,
			IssuedAt:    attIssuedAt.String,
		}
	}
	return ev, nil
}

// --- Trades -----------------------------------------------------------------

// tradeSelect is the shared projection for trade reads. The order reference is
// surfaced outward as the order's external id (order_external_id); the surrogate
// order id never leaves the store. Account, both assets and the optional
// principal are surfaced as codes.
const tradeSelect = `
SELECT t.external_id, o.external_id, a.code, ba.code, qa.code, p.code,
       t.at, t.source_id, t.side_id, t.quantity, t.price, t.lock_price,
       t.commission_amount, t.commission_currency
FROM trade t
JOIN order_record o          ON o.id = t.order_id
JOIN account a        ON a.id = t.account_id
JOIN asset ba         ON ba.id = t.base_asset_id
JOIN asset qa         ON qa.id = t.quote_asset_id
LEFT JOIN principal p ON p.id = t.principal_id`

// CreateTrade records a fill as a standalone trade row, assigning its external
// id and timestamp. It links to the originating order (surrogate id resolved
// from the order's external id), the account and both assets by code, and the
// optional principal.
func (r *realmStore) CreateTrade(
	ctx context.Context, t domain.Trade,
) (domain.Trade, error) {
	t.Source = storedSource(t.Source)
	db, err := r.db()
	if err != nil {
		return domain.Trade{}, err
	}
	xid, at, err := r.insertTrade(ctx, db, t)
	if err != nil {
		return t, err
	}
	t.ExternalID = xid
	t.At = mustParseTime(at)
	return t, nil
}

// insertTrade resolves a trade's foreign keys and inserts the row through exec
// (a *sql.DB or *sql.Tx), returning the assigned external id and timestamp text.
// It is shared by CreateTrade and the settlement transaction so both write an
// identical row.
func (r *realmStore) insertTrade(
	ctx context.Context, exec interface {
		sqlQueryer
		sqlExecer
	}, t domain.Trade,
) (domain.ExternalID, string, error) {
	if err := validateCommission(t.Commission); err != nil {
		return domain.ExternalID(""), "", err
	}
	orderID, err := lookupOrderID(ctx, exec, t.Order)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	accountID, err := resolveAccountID(ctx, exec, t.Account)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	baseID, err := resolveAssetID(ctx, exec, t.BaseAsset)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	quoteID, err := resolveAssetID(ctx, exec, t.QuoteAsset)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	principalID, err := resolveOptionalPrincipalID(ctx, exec, t.Principal)
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	sourceID, err := dictionaries.id(sourceKindTable, "source", string(storedSource(t.Source)))
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	sideID, err := dictionaries.id(orderSideTable, "order side", string(t.Side))
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	xid, err := newExternalID()
	if err != nil {
		return domain.ExternalID(""), "", err
	}
	at := nowStr()
	if _, err := exec.ExecContext(
		ctx,
		`INSERT INTO trade
	 (external_id, order_id, account_id, base_asset_id, quote_asset_id,
	  principal_id, at, source_id, side_id, quantity, price, lock_price,
	  commission_amount, commission_currency)
	 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, accountID, baseID, quoteID, principalID,
		at, sourceID, sideID, t.Quantity, t.Price, t.LockPrice,
		commissionAmount(t.Commission), commissionCurrency(t.Commission),
	); err != nil {
		return domain.ExternalID(""), "", fmt.Errorf("store: create trade: %w", err)
	}
	return xid, at, nil
}

// ListTrades returns the most recent n trade for an account, newest first. An
// empty account spans every account; an empty source spans every source; a
// non-positive n returns an empty slice.
func (r *realmStore) ListTrades(
	ctx context.Context, account domain.AccountID, source domain.Source, n int,
) ([]domain.Trade, error) {
	if n <= 0 {
		return make([]domain.Trade, 0), nil
	}
	return r.listTrades(ctx, account, source, n)
}

// ListAllTrades returns every trade for an account, newest first. It is used by
// exports that must not inherit UI display limits.
func (r *realmStore) ListAllTrades(
	ctx context.Context, account domain.AccountID, source domain.Source,
) ([]domain.Trade, error) {
	return r.listTrades(ctx, account, source, 0)
}

// ListTradeRows returns trade rows matching filter, with total count before
// paging.
func (r *realmStore) ListTradeRows(
	ctx context.Context, filter fwstore.TradeListFilter,
) (fwstore.TradeListPage, error) {
	dictionaries, err := r.dictionaries()
	if err != nil {
		return fwstore.TradeListPage{}, err
	}
	clauses, args, err := tradeListClauses(dictionaries, filter)
	if err != nil {
		return fwstore.TradeListPage{}, err
	}
	countQuery := `SELECT COUNT(*)
FROM trade t
JOIN order_record o          ON o.id = t.order_id
JOIN account a        ON a.id = t.account_id
JOIN asset ba         ON ba.id = t.base_asset_id
JOIN asset qa         ON qa.id = t.quote_asset_id
LEFT JOIN principal p ON p.id = t.principal_id` + whereFromClauses(clauses)
	db, err := r.db()
	if err != nil {
		return fwstore.TradeListPage{}, err
	}
	var total int
	if err := db.QueryRowContext(ctx, countQuery, args...).Scan(&total); err != nil {
		return fwstore.TradeListPage{}, fmt.Errorf("store: count trade rows: %w", err)
	}

	queryArgs := append([]any{}, args...)
	sortColumn := tradeListSortColumn(filter.Sort)
	query := `
SELECT t.external_id, o.external_id, a.code, ba.code, qa.code, p.code,
       t.at, t.source_id, t.side_id, t.quantity, t.price, t.lock_price,
       t.commission_amount, t.commission_currency
FROM trade t
JOIN order_record o          ON o.id = t.order_id
JOIN account a        ON a.id = t.account_id
JOIN asset ba         ON ba.id = t.base_asset_id
JOIN asset qa         ON qa.id = t.quote_asset_id
LEFT JOIN principal p ON p.id = t.principal_id` +
		whereFromClauses(clauses) +
		tradeListOrderBy(sortColumn, filter.Sort)
	if filter.Page.Limit > 0 {
		query += ` LIMIT ? OFFSET ?`
		queryArgs = append(queryArgs, filter.Page.Limit, max(filter.Page.Offset, 0))
	}
	rows, err := db.QueryContext(ctx, query, queryArgs...)
	if err != nil {
		return fwstore.TradeListPage{}, fmt.Errorf("store: list trade rows: %w", err)
	}
	defer func() { _ = rows.Close() }()

	result := make([]domain.Trade, 0)
	for rows.Next() {
		row, err := scanTradeListRow(dictionaries, rows)
		if err != nil {
			return fwstore.TradeListPage{}, err
		}
		result = append(result, row)
	}
	if err := rows.Err(); err != nil {
		return fwstore.TradeListPage{}, fmt.Errorf("store: iterate trade rows: %w", err)
	}
	return fwstore.TradeListPage{
		Rows:  result,
		Total: total,
	}, nil
}

func tradeListClauses(
	dictionaries *enumDictionaries,
	filter fwstore.TradeListFilter,
) ([]string, []any, error) {
	clauses := make([]string, 0)
	args := make([]any, 0)
	if !filter.ExternalID.IsZero() {
		clauses = append(clauses, "t.external_id = ?")
		args = append(args, filter.ExternalID.Bytes())
	}
	appendMatcher(&clauses, &args, "a.code", filter.Account)
	appendMatcher(&clauses, &args, "ba.code", filter.BaseAsset)
	appendMatcher(&clauses, &args, "qa.code", filter.QuoteAsset)
	if filter.Side != nil {
		id, err := dictionaries.id(orderSideTable, "order side", string(*filter.Side))
		if err != nil {
			return nil, nil, err
		}
		clauses = append(clauses, "t.side_id = ?")
		args = append(args, id)
	}
	if filter.Source != "" {
		id, err := dictionaries.id(sourceKindTable, "source", string(filter.Source))
		if err != nil {
			return nil, nil, err
		}
		clauses = append(clauses, "t.source_id = ?")
		args = append(args, id)
	}
	appendTimeRangeFilter(&clauses, &args, "t.at", filter.At)
	appendDecimalRangeFilter(&clauses, &args, "t.quantity COLLATE DECIMAL", filter.Quantity)
	appendDecimalRangeFilter(&clauses, &args, "t.price COLLATE DECIMAL", filter.Price)
	appendDecimalRangeFilter(&clauses, &args, "t.lock_price COLLATE DECIMAL", filter.LockPrice)
	return clauses, args, nil
}

func tradeListSortColumn(sort fwstore.SortSpec) string {
	columns := map[string]string{
		"account":    "a.code",
		"at":         "t.at",
		"baseAsset":  "ba.code",
		"lockPrice":  "t.lock_price COLLATE DECIMAL",
		"price":      "t.price COLLATE DECIMAL",
		"quantity":   "t.quantity COLLATE DECIMAL",
		"quoteAsset": "qa.code",
		"side":       "t.side_id",
		"source":     "t.source_id",
	}
	column := columns[sort.Column]
	if column == "" {
		column = "t.at"
	}
	return column
}

func tradeListOrderBy(sortColumn string, sort fwstore.SortSpec) string {
	direction := "ASC"
	tieDirection := "ASC"
	if sort.Column == "" ||
		(sortColumn == "t.at" && sort.Column != "at") ||
		sort.Descending {
		direction = "DESC"
		tieDirection = "DESC"
	}
	return "\nORDER BY " + sortColumn + " " + direction + ", t.id " + tieDirection
}

// listTrades is the shared trade-list query: it filters by the non-empty account
// and source, orders newest first by (at, id) per the §9 index, and applies the
// optional positive limit.
func (r *realmStore) listTrades(
	ctx context.Context, account domain.AccountID, source domain.Source, limit int,
) ([]domain.Trade, error) {
	q := tradeSelect + ` WHERE 1 = 1`
	args := make([]any, 0, 3)
	if account != "" {
		q += ` AND a.code = ?`
		args = append(args, account.String())
	}
	if source != "" {
		dictionaries, err := r.dictionaries()
		if err != nil {
			return nil, err
		}
		sourceID, err := dictionaries.id(sourceKindTable, "source", string(source))
		if err != nil {
			return nil, err
		}
		q += ` AND t.source_id = ?`
		args = append(args, sourceID)
	}
	q += ` ORDER BY t.at DESC, t.id DESC`
	if limit > 0 {
		q += ` LIMIT ?`
		args = append(args, limit)
	}

	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(ctx, q, args...)
	if err != nil {
		return nil, fmt.Errorf("store: list trades: %w", err)
	}
	defer func() { _ = rows.Close() }()
	dictionaries, err := r.dictionaries()
	if err != nil {
		return nil, err
	}
	return scanTrades(dictionaries, rows)
}

// listTradesByOrder returns all trade for one order (addressed by its external
// id), oldest first by (at, id). It backs GetOrder's trade list.
func (r *realmStore) listTradesByOrder(
	ctx context.Context, order domain.ExternalID,
) ([]domain.Trade, error) {
	db, err := r.db()
	if err != nil {
		return nil, err
	}
	rows, err := db.QueryContext(
		ctx,
		tradeSelect+` WHERE o.external_id = ? ORDER BY t.at ASC, t.id ASC`,
		order.Bytes(),
	)
	if err != nil {
		return nil, fmt.Errorf("store: list trades by order: %w", err)
	}
	defer func() { _ = rows.Close() }()
	dictionaries, err := r.dictionaries()
	if err != nil {
		return nil, err
	}
	return scanTrades(dictionaries, rows)
}

func scanTrades(dictionaries *enumDictionaries, rows *sql.Rows) ([]domain.Trade, error) {
	result := make([]domain.Trade, 0)
	for rows.Next() {
		tr, err := scanTrade(dictionaries, rows)
		if err != nil {
			return nil, err
		}
		result = append(result, tr)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("store: iterate trades: %w", err)
	}
	return result, nil
}

func scanTradeListRow(
	dictionaries *enumDictionaries,
	rows *sql.Rows,
) (domain.Trade, error) {
	var (
		tradeExtID, orderExtID               []byte
		account                              string
		baseAsset, quoteAsset                string
		principal                            sql.NullString
		at, quantity, price, lockPx          string
		sourceID, sideID                     int64
		commissionAmount, commissionCurrency string
	)
	if err := rows.Scan(
		&tradeExtID, &orderExtID, &account, &baseAsset,
		&quoteAsset, &principal, &at, &sourceID, &sideID, &quantity, &price, &lockPx,
		&commissionAmount, &commissionCurrency,
	); err != nil {
		return domain.Trade{}, fmt.Errorf("store: scan trade row: %w", err)
	}
	trade, err := tradeFromScanned(
		dictionaries, tradeExtID, orderExtID, account, baseAsset, quoteAsset,
		principal, at, sourceID, sideID, quantity, price, lockPx,
		commissionAmount, commissionCurrency,
	)
	if err != nil {
		return domain.Trade{}, err
	}
	return trade, nil
}

func scanTrade(dictionaries *enumDictionaries, rows *sql.Rows) (domain.Trade, error) {
	var (
		tradeExtID, orderExtID               []byte
		account                              string
		baseAsset, quoteAsset                string
		principal                            sql.NullString
		at, quantity, price, lockPx          string
		sourceID, sideID                     int64
		commissionAmount, commissionCurrency string
	)
	if err := rows.Scan(
		&tradeExtID, &orderExtID, &account, &baseAsset, &quoteAsset, &principal,
		&at, &sourceID, &sideID, &quantity, &price, &lockPx,
		&commissionAmount, &commissionCurrency,
	); err != nil {
		return domain.Trade{}, fmt.Errorf("store: scan trade: %w", err)
	}
	return tradeFromScanned(
		dictionaries, tradeExtID, orderExtID, account, baseAsset, quoteAsset,
		principal, at, sourceID, sideID, quantity, price, lockPx,
		commissionAmount, commissionCurrency,
	)
}

func tradeFromScanned(
	dictionaries *enumDictionaries,
	tradeExtID []byte,
	orderExtID []byte,
	account string,
	baseAsset string,
	quoteAsset string,
	principal sql.NullString,
	at string,
	sourceID int64,
	sideID int64,
	quantity string,
	price string,
	lockPx string,
	commissionAmount string,
	commissionCurrency string,
) (domain.Trade, error) {
	tradeXID, err := domain.ExternalIDFromBytes(tradeExtID)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: decode trade external id: %w", err)
	}
	orderXID, err := domain.ExternalIDFromBytes(orderExtID)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: decode trade order external id: %w", err)
	}
	parsedAt, err := time.Parse(time.RFC3339Nano, at)
	if err != nil {
		return domain.Trade{}, fmt.Errorf("store: parse trade at %q: %w", at, err)
	}
	source, err := dictionaries.code(sourceKindTable, "source", sourceID)
	if err != nil {
		return domain.Trade{}, err
	}
	side, err := dictionaries.code(orderSideTable, "order side", sideID)
	if err != nil {
		return domain.Trade{}, err
	}
	trade := domain.Trade{
		ExternalID: tradeXID,
		Order:      orderXID,
		Account:    domain.AccountID(account),
		BaseAsset:  baseAsset,
		QuoteAsset: quoteAsset,
		Principal:  principal.String,
		At:         parsedAt,
		Source:     domain.Source(source),
		Side:       domain.OrderSide(side),
		Quantity:   quantity,
		Price:      price,
		LockPrice:  lockPx,
	}
	if commissionAmount != "" || commissionCurrency != "" {
		trade.Commission = &domain.Commission{
			Amount:   commissionAmount,
			Currency: commissionCurrency,
		}
	}
	return trade, nil
}

func commissionAmount(c *domain.Commission) string {
	if c == nil {
		return ""
	}
	return c.Amount
}

func commissionCurrency(c *domain.Commission) string {
	if c == nil {
		return ""
	}
	return c.Currency
}

// validateCommission enforces the write-time Commission invariant shared by
// insertTrade and restoreTrade: a commission is either fully absent (both amount
// and currency empty) or fully present, and a present amount must be a valid
// decimal. A one-sided commission (exactly one of amount/currency set) would be
// silently dropped from the CommissionSubtotals rollup, understating the order
// commission, so it is rejected as invalid input rather than persisted.
func validateCommission(c *domain.Commission) error {
	amount := commissionAmount(c)
	currency := commissionCurrency(c)
	if (amount == "") != (currency == "") {
		return fmt.Errorf(
			"store: commission requires both amount and currency: %w",
			domain.ErrInvalid,
		)
	}
	if amount == "" {
		return nil
	}
	if _, err := decimal.NewFromString(amount); err != nil {
		return fmt.Errorf(
			"store: commission amount %q is not a valid decimal: %w",
			amount, domain.ErrInvalid,
		)
	}
	return nil
}

// commissionSubtotals rolls up the recorded commissions of the one order whose
// rows are already in memory. It folds them through the same commissionRollup
// the batched list read uses, so the detail and the list surface cannot report
// different totals for the same order.
func commissionSubtotals(
	order domain.ExternalID,
	trades []domain.Trade,
	events []domain.OrderEvent,
) ([]domain.Commission, error) {
	rollup := newCommissionRollup(1)
	for _, trade := range trades {
		if err := rollup.add(order, trade.Commission); err != nil {
			return nil, err
		}
	}
	for _, event := range events {
		if err := rollup.addEvent(order, event.Type, event.Payload); err != nil {
			return nil, err
		}
	}
	return rollup.subtotals(order), nil
}

// commissionRollup sums recorded order commissions per order and currency. It
// owns the rule that decides which commission counts, so the two order reads -
// the detail read folding in-memory rows and the batched list read folding SQL
// rows - share one implementation instead of two that must be kept in step.
// Currencies are grouped, never converted or collapsed, and amounts are summed
// as exact decimals.
type commissionRollup struct {
	byOrder map[domain.ExternalID]map[string]decimal.Decimal
}

func newCommissionRollup(orders int) *commissionRollup {
	return &commissionRollup{
		byOrder: make(map[domain.ExternalID]map[string]decimal.Decimal, orders),
	}
}

// add folds one recorded commission, the trade-row case. A commission missing
// either half is not a recorded commission and contributes nothing.
func (rollup *commissionRollup) add(
	order domain.ExternalID, commission *domain.Commission,
) error {
	if commission == nil || commission.Amount == "" || commission.Currency == "" {
		return nil
	}
	amount, err := decimal.NewFromString(commission.Amount)
	if err != nil {
		return fmt.Errorf(
			"store: parse commission amount %q: %w", commission.Amount, err)
	}
	amounts := rollup.byOrder[order]
	if amounts == nil {
		amounts = make(map[string]decimal.Decimal)
		rollup.byOrder[order] = amounts
	}
	amounts[commission.Currency] = amounts[commission.Currency].Add(amount)
	return nil
}

// addEvent folds one lifecycle event's commission, which counts only when no
// trade row already represents it.
func (rollup *commissionRollup) addEvent(
	order domain.ExternalID,
	eventType domain.OrderEventType,
	payload domain.OrderEventPayload,
) error {
	return rollup.add(
		order, feeOnlyExecutionReportCommission(eventType, payload))
}

// subtotals returns one order's per-currency subtotals; empty when the order
// has no recorded commission.
func (rollup *commissionRollup) subtotals(
	order domain.ExternalID,
) []domain.Commission {
	return commissionsFromAmountMap(rollup.byOrder[order])
}

// feeOnlyExecutionReportCommission returns the commission of an execution
// report that no trade row represents. A report without a fill writes no trade,
// so its lifecycle event is the only record of the fee and dropping it would
// lose the fee outright. Reports carrying a fill are accounted from their trade
// instead: the same report may persist both a fill event and a terminal-status
// event, so reading commission from those events would count it two or three
// times. Of the events one report writes, only its canonical status-change
// event contributes.
func feeOnlyExecutionReportCommission(
	eventType domain.OrderEventType,
	payload domain.OrderEventPayload,
) *domain.Commission {
	report := payload.ExecutionReport
	if report == nil || report.Commission == nil ||
		report.FillQuantity != "" || report.FillPrice != "" {
		return nil
	}
	canonicalEvent, ok := domain.ExecutionReportStatusChangeEvent(report.OrderStatus)
	if !ok || eventType != canonicalEvent {
		return nil
	}
	return report.Commission
}

// commissionSubtotalsByOrder rolls up recorded commissions for a list page. The
// order ids are chunked so the IN clauses stay inside the SQLite variable
// limit; every chunk feeds one rollup, which then answers per order.
func commissionSubtotalsByOrder(
	ctx context.Context,
	dictionaries *enumDictionaries,
	q sqlQueryer,
	orders []domain.ExternalID,
) (map[domain.ExternalID][]domain.Commission, error) {
	result := make(map[domain.ExternalID][]domain.Commission, len(orders))
	if len(orders) == 0 {
		return result, nil
	}

	rollup := newCommissionRollup(len(orders))
	for start := 0; start < len(orders); start += commissionSubtotalOrderBatchSize {
		end := start + commissionSubtotalOrderBatchSize
		if end > len(orders) {
			end = len(orders)
		}
		if err := accumulateCommissionSubtotalsByOrder(
			ctx, dictionaries, q, orders[start:end], rollup,
		); err != nil {
			return nil, err
		}
	}
	for _, order := range orders {
		result[order] = rollup.subtotals(order)
	}
	return result, nil
}

const commissionSubtotalOrderBatchSize = 500

func accumulateCommissionSubtotalsByOrder(
	ctx context.Context,
	dictionaries *enumDictionaries,
	q sqlQueryer,
	orders []domain.ExternalID,
	rollup *commissionRollup,
) error {
	placeholders := strings.TrimRight(strings.Repeat("?,", len(orders)), ",")
	args := make([]any, 0, len(orders))
	for _, order := range orders {
		args = append(args, order.Bytes())
	}
	rows, err := q.QueryContext(
		ctx,
		`SELECT o.external_id, t.commission_amount, t.commission_currency
FROM trade t
JOIN order_record o ON o.id = t.order_id
WHERE t.commission_amount <> ''
  AND t.commission_currency <> ''
  AND o.external_id IN (`+placeholders+`)`,
		args...,
	)
	if err != nil {
		return fmt.Errorf("store: list order commission subtotals: %w", err)
	}
	for rows.Next() {
		var orderBytes []byte
		var amountText, currency string
		if err := rows.Scan(&orderBytes, &amountText, &currency); err != nil {
			_ = rows.Close()
			return fmt.Errorf("store: scan order commission subtotal: %w", err)
		}
		order, err := domain.ExternalIDFromBytes(orderBytes)
		if err != nil {
			_ = rows.Close()
			return fmt.Errorf(
				"store: decode order commission external id: %w", err)
		}
		if err := rollup.add(
			order,
			&domain.Commission{Amount: amountText, Currency: currency},
		); err != nil {
			_ = rows.Close()
			return err
		}
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return fmt.Errorf("store: iterate order commission subtotals: %w", err)
	}
	if err := rows.Close(); err != nil {
		return fmt.Errorf("store: close order commission subtotals: %w", err)
	}

	eventRows, err := q.QueryContext(
		ctx,
		`SELECT o.external_id, e.type_id, e.payload
FROM order_event e
JOIN order_record o ON o.id = e.order_id
WHERE o.external_id IN (`+placeholders+`)`,
		args...,
	)
	if err != nil {
		return fmt.Errorf("store: list order event commission subtotals: %w", err)
	}
	for eventRows.Next() {
		var orderBytes []byte
		var eventTypeID int64
		var payloadJSON string
		if err := eventRows.Scan(&orderBytes, &eventTypeID, &payloadJSON); err != nil {
			_ = eventRows.Close()
			return fmt.Errorf("store: scan order event commission subtotal: %w", err)
		}
		order, err := domain.ExternalIDFromBytes(orderBytes)
		if err != nil {
			_ = eventRows.Close()
			return fmt.Errorf(
				"store: decode order event commission external id: %w", err)
		}
		var payload domain.OrderEventPayload
		if err := json.Unmarshal([]byte(payloadJSON), &payload); err != nil {
			_ = eventRows.Close()
			return fmt.Errorf("store: decode order event commission payload: %w", err)
		}
		eventType, err := dictionaries.code(orderEventTypeTable, "order event type", eventTypeID)
		if err != nil {
			_ = eventRows.Close()
			return err
		}
		if err := rollup.addEvent(
			order,
			domain.OrderEventType(eventType),
			payload,
		); err != nil {
			_ = eventRows.Close()
			return err
		}
	}
	if err := eventRows.Err(); err != nil {
		_ = eventRows.Close()
		return fmt.Errorf("store: iterate order event commission subtotals: %w", err)
	}
	if err := eventRows.Close(); err != nil {
		return fmt.Errorf("store: close order event commission subtotals: %w", err)
	}
	return nil
}

func commissionsFromAmountMap(amounts map[string]decimal.Decimal) []domain.Commission {
	if len(amounts) == 0 {
		return []domain.Commission{}
	}
	currencies := make([]string, 0, len(amounts))
	for currency := range amounts {
		currencies = append(currencies, currency)
	}
	sort.Strings(currencies)
	out := make([]domain.Commission, 0, len(currencies))
	for _, currency := range currencies {
		out = append(out, domain.Commission{
			Amount:   amounts[currency].String(),
			Currency: currency,
		})
	}
	return out
}

// --- Settlement -------------------------------------------------------------

// RecordOrderSettlement persists one fill/settlement atomically in a single
// transaction: the optional execution-report identity and all of its event
// links, per-asset engine balance snapshots, the engine-applied account blocks,
// the optional trade, the fill event(s),
// the optional lock rewrite and the order status advance commit or roll back
// together. When AllowedFrom is non-empty the status UPDATE is guarded and a
// disallowed current status yields domain.ErrConflict with nothing written;
// otherwise a missing order yields domain.ErrNotFound. The block-audit row is
// NOT part of this tx; callers write it separately after a successful commit.
func (r *realmStore) RecordOrderSettlement(
	ctx context.Context, st domain.OrderSettlement,
) (domain.ExternalID, error) {
	return r.recordOrderSettlement(ctx, st, nil)
}

func (r *realmStore) RecordOrderSettlementWithAttestation(
	ctx context.Context, st domain.OrderSettlement, attest fwstore.EventAttestor,
) (domain.ExternalID, error) {
	return r.recordOrderSettlement(ctx, st, attest)
}

func (r *realmStore) recordOrderSettlement(
	ctx context.Context, st domain.OrderSettlement, attest fwstore.EventAttestor,
) (domain.ExternalID, error) {
	db, err := r.db()
	if err != nil {
		return "", err
	}
	dictionaries, err := r.dictionaries()
	if err != nil {
		return "", err
	}
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return "", fmt.Errorf("store: begin record_order_settlement: %w", err)
	}
	defer func() { _ = tx.Rollback() }()

	reportID, err := r.recordOrderSettlementTx(ctx, dictionaries, tx, st, attest)
	if err != nil {
		return "", err
	}
	if err := tx.Commit(); err != nil {
		return "", fmt.Errorf("store: commit record_order_settlement: %w", err)
	}
	if st.ReportID != nil {
		*st.ReportID = reportID
	}
	return reportID, nil
}

func (r *realmStore) recordOrderSettlementTx(
	ctx context.Context,
	dictionaries *enumDictionaries,
	tx *sql.Tx,
	st domain.OrderSettlement,
	attest fwstore.EventAttestor,
) (domain.ExternalID, error) {
	if st.Order.IsZero() {
		return "", fmt.Errorf("store: settlement order is required: %w", domain.ErrInvalid)
	}
	// Resolve the settling account once; balance and blocks reuse it. The
	// account is the fill's account, always present on a settlement.
	accountID, err := resolveAccountID(ctx, tx, st.Account)
	if err != nil {
		return "", err
	}
	// Resolve the order surrogate id before any writes. Events, the optional
	// report, lock rewrite and status advance all reuse it.
	orderID, err := lookupOrderID(ctx, tx, st.Order)
	if err != nil {
		return "", err
	}
	if attest != nil && len(st.Events) == 0 {
		return "", fmt.Errorf(
			"store: settlement has no event to attest: %w", domain.ErrInvalid,
		)
	}
	if st.ReportID != nil && len(st.Events) == 0 {
		return "", fmt.Errorf(
			"store: execution report has no events: %w", domain.ErrInvalid,
		)
	}
	if st.AccountPnl != "" {
		if _, err := domain.AddDecimals("", st.AccountPnl); err != nil {
			return "", fmt.Errorf("store: settlement account pnl %q: %w", st.Account, err)
		}
	}
	reportID, reportRowID, err := insertExecutionReportTx(
		ctx, tx, orderID, st.ReportID,
	)
	if err != nil {
		return "", err
	}

	// The engine reports the P&L value and its halt as one fact, so both columns
	// move together. NULL is the absence of a value, which a halt always is; a
	// settlement reporting neither leaves the stored pair untouched.
	if st.AccountPnlHaltReason != "" || st.AccountPnl != "" {
		var storedPnl any
		if st.AccountPnl != "" && st.AccountPnlHaltReason == "" {
			storedPnl = st.AccountPnl
		}
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE account SET pnl = ?, pnl_halt_reason = ? WHERE id = ?`,
			storedPnl,
			st.AccountPnlHaltReason,
			accountID,
		); err != nil {
			return "", fmt.Errorf("store: settlement account pnl %q: %w", st.Account, err)
		}
	}

	// Per-asset balance snapshots are merged inside this transaction; fields the
	// engine omitted preserve their prior values.
	for _, bal := range st.Balances {
		if err := settleBalanceTx(ctx, tx, accountID, bal); err != nil {
			return "", err
		}
	}

	// Mirror engine-applied account blocks (the block UPDATE only; the audit row
	// stays a post-commit write owned by the caller). A block names its own
	// account, which may differ from the fill account in principle, so resolve it.
	for _, blk := range st.Blocks {
		blkAccountID, err := resolveAccountID(ctx, tx, blk.Account)
		if err != nil {
			return "", err
		}
		// The reason is engine-composed, never operator input: refusing it would
		// drop a real kill-switch record, so it is normalized to the rule the
		// restore path validates rather than rejected.
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE account SET blocked = ?, block_reason = ? WHERE id = ?`,
			true, domain.NormalizeReason(blk.Reason), blkAccountID,
		); err != nil {
			return "", fmt.Errorf("store: settlement mirror block %q: %w", blk.Account, err)
		}
	}

	// Trade row.
	if st.Trade != nil {
		if _, _, err := r.insertTrade(ctx, tx, *st.Trade); err != nil {
			return "", err
		}
	}

	// Fill event(s).
	for _, ev := range st.Events {
		if !reportID.IsZero() && ev.Payload.ExecutionReport != nil {
			request := *ev.Payload.ExecutionReport
			request.ExternalID = reportID
			ev.Payload.ExecutionReport = &request
		}
		recorded, eventRowID, err := appendOrderEventReturningTx(
			ctx, dictionaries, tx, orderID, ev,
		)
		if err != nil {
			return "", err
		}
		if reportRowID != 0 {
			if _, err := tx.ExecContext(
				ctx,
				`INSERT INTO execution_report_event (report_id, event_id) VALUES (?, ?)`,
				reportRowID,
				eventRowID,
			); err != nil {
				return "", fmt.Errorf("store: link execution report event: %w", err)
			}
		}
		if err := attestOrderEventTx(ctx, dictionaries, tx, recorded, attest); err != nil {
			return "", err
		}
	}

	// Lock rewrite: only when explicitly requested (nil-vs-empty matters: an
	// empty non-nil slice clears the column, nil leaves it).
	if st.SetLock {
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE order_record SET lock = ? WHERE id = ?`,
			nullableBlob(st.Lock), orderID,
		); err != nil {
			return "", fmt.Errorf("store: settlement lock: %w", err)
		}
	}

	// Remaining open quantity: the caller carries the report's LeavesQty; an
	// empty value leaves the column untouched.
	if st.Leaves != "" {
		if _, err := tx.ExecContext(
			ctx,
			`UPDATE order_record SET leaves_quantity = ? WHERE id = ?`,
			st.Leaves, orderID,
		); err != nil {
			return "", fmt.Errorf("store: settlement leaves: %w", err)
		}
	}

	// Status advance last; guarded only when AllowedFrom is set.
	if err := guardedOrderStatus(
		ctx, dictionaries, tx, orderID, st.Order, st.OrderStatus, st.AllowedFrom,
	); err != nil {
		return "", err
	}

	return reportID, nil
}

func insertExecutionReportTx(
	ctx context.Context,
	tx *sql.Tx,
	orderID int64,
	reportID *domain.ExternalID,
) (domain.ExternalID, int64, error) {
	if reportID == nil {
		return "", 0, nil
	}
	xid, err := externalIDForInsert(*reportID)
	if err != nil {
		return "", 0, err
	}
	result, err := tx.ExecContext(
		ctx,
		`INSERT INTO execution_report (external_id, order_id, at) VALUES (?, ?, ?)`,
		xid.Bytes(),
		orderID,
		nowStr(),
	)
	if err != nil {
		if isSQLiteUnique(err) {
			return "", 0, fmt.Errorf(
				"execution report %q: %w", xid.String(), domain.ErrAlreadyExists,
			)
		}
		return "", 0, fmt.Errorf("store: insert execution report: %w", err)
	}
	reportRowID, err := result.LastInsertId()
	if err != nil {
		return "", 0, fmt.Errorf("store: execution report row id: %w", err)
	}
	return xid, reportRowID, nil
}

// guardedOrderStatus advances an order's status inside tx, addressing it by its
// already-resolved surrogate id. When allowedFrom is non-empty the UPDATE only
// matches rows already in one of those statuses; a 0-rows result then means
// either the order is missing (domain.ErrNotFound) or its current status is
// disallowed (domain.ErrConflict), distinguished by a follow-up SELECT in the
// same tx. When allowedFrom is empty the UPDATE is unguarded and 0 rows means a
// missing order. The order external id is carried for error messages only.
func guardedOrderStatus(
	ctx context.Context,
	dictionaries *enumDictionaries,
	tx *sql.Tx,
	orderID int64,
	order domain.ExternalID,
	status domain.OrderStatus,
	allowedFrom []domain.OrderStatus,
) error {
	statusID, err := dictionaries.id(orderStatusTable, "order status", string(status))
	if err != nil {
		return err
	}
	args := []any{statusID, orderID}
	q := `UPDATE order_record SET status_id = ? WHERE id = ?`
	if len(allowedFrom) > 0 {
		placeholders := strings.TrimSuffix(strings.Repeat("?,", len(allowedFrom)), ",")
		q += fmt.Sprintf(` AND status_id IN (%s)`, placeholders)
		for _, s := range allowedFrom {
			id, err := dictionaries.id(orderStatusTable, "order status", string(s))
			if err != nil {
				return err
			}
			args = append(args, id)
		}
	}
	res, err := tx.ExecContext(ctx, q, args...)
	if err != nil {
		return fmt.Errorf("store: resolve order %q status: %w", order.String(), err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("store: resolve order %q status rows: %w", order.String(), err)
	}
	if n > 0 {
		return nil
	}
	// No row advanced: distinguish a missing order from a disallowed status.
	var curID int64
	err = tx.QueryRowContext(
		ctx, `SELECT status_id FROM order_record WHERE id = ?`, orderID,
	).Scan(&curID)
	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("order %q: %w", order.String(), domain.ErrNotFound)
	}
	if err != nil {
		return fmt.Errorf("store: resolve order %q status probe: %w", order.String(), err)
	}
	cur, err := dictionaries.code(orderStatusTable, "order status", curID)
	if err != nil {
		return err
	}
	return fmt.Errorf(
		"store: resolve order %q: status %q: %w", order.String(), cur, domain.ErrConflict,
	)
}

func appendOrderEventReturningTx(
	ctx context.Context,
	dictionaries *enumDictionaries,
	tx *sql.Tx,
	orderID int64,
	ev domain.OrderEvent,
) (domain.OrderEvent, int64, error) {
	ev.Source = storedSource(ev.Source)
	principalID, err := resolveOptionalPrincipalID(ctx, tx, ev.Principal)
	if err != nil {
		return domain.OrderEvent{}, 0, err
	}
	typeID, err := dictionaries.id(orderEventTypeTable, "order event type", string(ev.Type))
	if err != nil {
		return domain.OrderEvent{}, 0, err
	}
	sourceID, err := dictionaries.id(sourceKindTable, "source", string(ev.Source))
	if err != nil {
		return domain.OrderEvent{}, 0, err
	}
	xid, err := newExternalID()
	if err != nil {
		return domain.OrderEvent{}, 0, err
	}
	at := nowStr()
	payloadJSON, err := json.Marshal(ev.Payload)
	if err != nil {
		return domain.OrderEvent{}, 0, fmt.Errorf("store: marshal event payload: %w", err)
	}
	result, err := tx.ExecContext(
		ctx,
		`INSERT INTO order_event
		 (external_id, order_id, principal_id, at, type_id, source_id, payload)
		 VALUES (?, ?, ?, ?, ?, ?, ?)`,
		xid.Bytes(), orderID, principalID, at,
		typeID, sourceID, string(payloadJSON),
	)
	if err != nil {
		return domain.OrderEvent{}, 0, fmt.Errorf("store: append order event: %w", err)
	}
	eventRowID, err := result.LastInsertId()
	if err != nil {
		return domain.OrderEvent{}, 0, fmt.Errorf("store: order event row id: %w", err)
	}
	ev.ExternalID = xid
	ev.At = mustParseTime(at)
	return ev, eventRowID, nil
}

func attestOrderEventTx(
	ctx context.Context,
	dictionaries *enumDictionaries,
	tx *sql.Tx,
	event domain.OrderEvent,
	attest fwstore.EventAttestor,
) error {
	if attest == nil {
		return nil
	}
	att, ok, err := attest(ctx, event)
	if err != nil {
		return err
	}
	if !ok {
		return fmt.Errorf(
			"store: event %s has no attestation payload: %w",
			event.Type, domain.ErrInvalid,
		)
	}
	return putEventAttestationTx(ctx, dictionaries, tx, event.ExternalID, att)
}

// settleBalanceTx applies one per-asset fill outcome inside tx. Available,
// held, incoming, realized PnL, and average entry price are independent
// engine-returned absolutes; an absent result preserves the prior value. The
// balance table is owned by another store group; this method
// touches it with direct SQL (never the public balance methods) to keep the
// whole settlement atomic.
func settleBalanceTx(
	ctx context.Context,
	tx *sql.Tx,
	accountID int64,
	bal domain.BalanceSettlement,
) error {
	assetID, err := resolveAssetID(ctx, tx, bal.Asset)
	if err != nil {
		return err
	}
	var prevAvail, prevHeld, prevIncoming, prevPnlHaltReason, prevAvgPx string
	var prevRealized sql.NullString
	err = tx.QueryRowContext(
		ctx,
		`SELECT available, held, incoming, realized_pnl, realized_pnl_halt_reason, average_entry_price
		 FROM balance WHERE account_id = ? AND asset_id = ?`,
		accountID, assetID,
	).Scan(&prevAvail, &prevHeld, &prevIncoming, &prevRealized, &prevPnlHaltReason, &prevAvgPx)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("store: settle balance %q read: %w", bal.Asset, err)
	}

	available := settleOrZero(settlementResultOrPrevious(bal.Outcome.BalanceResult, prevAvail))
	held := settleOrZero(settlementResultOrPrevious(bal.Outcome.HeldResult, prevHeld))
	incoming := settleOrZero(settlementResultOrPrevious(bal.Outcome.IncomingResult, prevIncoming))
	realized := settlementResultOrPrevious(
		bal.Outcome.RealizedPnlResult, prevRealized.String)
	pnlHaltReason := settlementPnlHaltReason(
		bal.Outcome.RealizedPnlHaltReason,
		prevPnlHaltReason,
		bal.Outcome.RealizedPnlResult != "",
	)
	if pnlHaltReason != "" {
		realized = ""
	}
	averageEntryPrice := settlementResultOrPrevious(
		bal.Outcome.AverageEntryPrice, prevAvgPx)
	if decimalZeroOrEmpty(available) &&
		decimalZeroOrEmpty(held) &&
		decimalZeroOrEmpty(incoming) {
		// A closed position has no cost basis; realised PnL remains independent.
		averageEntryPrice = ""
	}
	if _, err := tx.ExecContext(
		ctx,
		`INSERT OR REPLACE INTO balance
		 (account_id, asset_id, available, held,
		  incoming, realized_pnl, realized_pnl_halt_reason, average_entry_price, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		accountID, assetID,
		available, held, incoming,
		nullablePnl(realized, domain.PnlHaltReason(pnlHaltReason)),
		pnlHaltReason, averageEntryPrice,
		nowStr(),
	); err != nil {
		return fmt.Errorf("store: settle balance %q write: %w", bal.Asset, err)
	}
	if err := pruneEmptySettlementBalanceTx(
		ctx, tx, accountID, assetID, bal.Asset,
		available, held, incoming, realized, pnlHaltReason, averageEntryPrice,
	); err != nil {
		return err
	}
	return nil
}

func pruneEmptySettlementBalanceTx(
	ctx context.Context,
	tx *sql.Tx,
	accountID int64,
	assetID int64,
	asset string,
	available string,
	held string,
	incoming string,
	realized string,
	pnlHaltReason string,
	averageEntryPrice string,
) error {
	if !balanceAmountsEmpty(available, held, incoming, realized, pnlHaltReason, averageEntryPrice) {
		return nil
	}
	if _, err := tx.ExecContext(
		ctx,
		`DELETE FROM balance WHERE account_id = ? AND asset_id = ?`,
		accountID, assetID,
	); err != nil {
		return fmt.Errorf("store: prune empty settlement balance %q: %w", asset, err)
	}
	return nil
}

func balanceAmountsEmpty(
	available string, held string, incoming string, realized string, pnlHaltReason string, averageEntryPrice string,
) bool {
	return decimalZeroOrEmpty(available) &&
		decimalZeroOrEmpty(held) &&
		decimalZeroOrEmpty(incoming) &&
		decimalZeroOrEmpty(realized) &&
		pnlHaltReason == "" &&
		decimalZeroOrEmpty(averageEntryPrice)
}

func settlementPnlHaltReason(next domain.PnlHaltReason, prev string, successfulPnlResult bool) string {
	if next != "" {
		return string(next)
	}
	if successfulPnlResult {
		return ""
	}
	return prev
}

func decimalZeroOrEmpty(value string) bool {
	if value == "" {
		return true
	}
	parsed, err := decimal.NewFromString(value)
	return err == nil && parsed.IsZero()
}

// --- Orders-group small helpers ---------------------------------------------

// lookupOrderID resolves an order's external id to its surrogate id, mapping a
// missing order onto domain.ErrNotFound. It is the orders-group analogue of the
// dictionary resolvers in store.go; it joins the order's children and the
// settlement writes to the order without exposing the surrogate id.
func lookupOrderID(
	ctx context.Context, q sqlQueryer, id domain.ExternalID,
) (int64, error) {
	var orderID int64
	err := q.QueryRowContext(
		ctx, `SELECT id FROM order_record WHERE external_id = ?`, id.Bytes(),
	).Scan(&orderID)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, fmt.Errorf("order %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return 0, fmt.Errorf("store: resolve order %q: %w", id.String(), err)
	}
	return orderID, nil
}

// lookupOrderEventID resolves an event's external id to its surrogate id,
// mapping a missing event onto domain.ErrNotFound. It is the analogue of
// lookupOrderID for the event stream; it keys the 1:1 attestation onto the event
// without exposing the surrogate id.
func lookupOrderEventID(
	ctx context.Context, q sqlQueryer, id domain.ExternalID,
) (int64, error) {
	var eventID int64
	err := q.QueryRowContext(
		ctx, `SELECT id FROM order_event WHERE external_id = ?`, id.Bytes(),
	).Scan(&eventID)
	if errors.Is(err, sql.ErrNoRows) {
		return 0, fmt.Errorf("order event %q: %w", id.String(), domain.ErrNotFound)
	}
	if err != nil {
		return 0, fmt.Errorf("store: resolve order event %q: %w", id.String(), err)
	}
	return eventID, nil
}

// nullableBlob maps a nil byte slice to a NULL column value and a non-nil slice
// (including an empty one) to itself, so the lock column distinguishes "no lock"
// (NULL) from a present-but-empty serialized lock.
func nullableBlob(b []byte) any {
	if b == nil {
		return nil
	}
	return b
}

// mustParseTime parses an RFC3339Nano string the store itself just formatted via
// nowStr; the format is guaranteed, so a parse error is impossible and the zero
// time is returned defensively rather than panicking on the write path.
func mustParseTime(s string) time.Time {
	t, _ := time.Parse(time.RFC3339Nano, s)
	return t
}

// settleOrZero maps an empty amount string to "0" so a balance column is never
// written empty.
func settleOrZero(s string) string {
	if s == "" {
		return "0"
	}
	return s
}

// nullablePnl stores an engine-reported P&L value only while it is
// authoritative. Empty and halted states are represented as SQL NULL, never as
// a zero Officer invented.
func nullablePnl(pnl string, haltReason domain.PnlHaltReason) any {
	if pnl == "" || haltReason != "" {
		return nil
	}
	return pnl
}

func settlementResultOrPrevious(next, prev string) string {
	if next != "" {
		return next
	}
	return prev
}
