// Copyright The Pit Project Owners. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Please see https://openpit.dev and the OWNERS file for details.

package domain

import (
	"encoding/base64"
	"fmt"
)

// ExternalIDByteLen is the fixed width of the raw external-id value: 128 bits
// of randomness in a uniform 16-byte form. The randomness budget makes
// collisions negligible without a per-insert existence check.
const ExternalIDByteLen = 16

// ExternalIDStringLen is the width of the encoded form: 16 bytes in base64url
// without padding render to exactly 22 characters.
const ExternalIDStringLen = 22

// externalIDCodec encodes the 16 raw bytes as URL-safe base64 with no padding,
// the single canonical wire form for every machine-record identity.
var externalIDCodec = base64.RawURLEncoding

// ExternalID is the non-guessable, opaque identity of a machine-generated
// record whose existence is exposed on the wire (orders, trades, order events,
// adjustments, audit rows, market-data instances, and the realm row). It backs
// a 128-bit random value held as 16 raw bytes; the encoded form is a 22-char
// URL-safe base64 string with no padding. It replaces the leaky autoincrement
// primary key on the wire: the internal surrogate key never leaves the store.
//
// The raw bytes are generated by the connector at insert time; this package
// only models the value and owns the single bytes-to-string codec. A zero value
// is invalid and means "unset".
type ExternalID [ExternalIDByteLen]byte

// String renders the external id as its 22-char URL-safe base64 form.
func (id ExternalID) String() string {
	return externalIDCodec.EncodeToString(id[:])
}

// IsZero reports whether the external id is the unset zero value.
func (id ExternalID) IsZero() bool {
	return id == ExternalID{}
}

// Bytes returns a copy of the raw 16-byte value for storage in a binary column.
func (id ExternalID) Bytes() []byte {
	out := make([]byte, ExternalIDByteLen)
	copy(out, id[:])
	return out
}

// ExternalIDFromBytes builds an ExternalID from raw bytes, which must be exactly
// 16 bytes long. It is the store-side decoder for the binary column.
func ExternalIDFromBytes(b []byte) (ExternalID, error) {
	var id ExternalID
	if len(b) != ExternalIDByteLen {
		return id, fmt.Errorf(
			"external id needs %d bytes, got %d: %w",
			ExternalIDByteLen, len(b), ErrInvalid,
		)
	}
	copy(id[:], b)
	return id, nil
}

// ParseExternalID decodes the 22-char URL-safe base64 wire form back into an
// ExternalID. It rejects any string that does not decode to exactly 16 bytes,
// including padded or standard-alphabet variants.
func ParseExternalID(s string) (ExternalID, error) {
	var id ExternalID
	if len(s) != ExternalIDStringLen {
		return id, fmt.Errorf(
			"external id %q must be %d chars: %w",
			s, ExternalIDStringLen, ErrInvalid,
		)
	}
	raw, err := externalIDCodec.DecodeString(s)
	if err != nil {
		return id, fmt.Errorf("external id %q is not valid base64url: %w", s, ErrInvalid)
	}
	if len(raw) != ExternalIDByteLen {
		return id, fmt.Errorf(
			"external id %q decodes to %d bytes, want %d: %w",
			s, len(raw), ExternalIDByteLen, ErrInvalid,
		)
	}
	copy(id[:], raw)
	return id, nil
}

// ValidateExternalID returns nil when s is a well-formed external-id wire form.
// It is the boundary format check the surfaces apply to a caller-supplied id; it
// never checks existence.
func ValidateExternalID(s string) error {
	_, err := ParseExternalID(s)
	return err
}
